package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
void die_at(const char *file, int line, int col, const char *fmt, ...);
enum TokenKind {
    TK_KW_PACKAGE,
    TK_KW_IMPORT,
    TK_KW_VOID,
    TK_KW_INT,
    TK_KW_FLOAT,
    TK_KW_DOUBLE,
    TK_KW_CHAR,
    TK_KW_SHORT,
    TK_KW_LONG,
    TK_KW_SIGNED,
    TK_KW_UNSIGNED,
    TK_KW_SIZEOF,
    TK_KW_RETURN,
    TK_KW_IF,
    TK_KW_ELSE,
    TK_KW_WHILE,
    TK_KW_FOR,
    TK_KW_GOTO,
    TK_KW_SWITCH,
    TK_KW_CASE,
    TK_KW_DEFAULT,
    TK_KW_BREAK,
    TK_KW_CONTINUE,
    TK_KW_CONST,
    TK_KW_UNION,
    TK_KW_DO,
    TK_KW_ENUM,
    TK_KW_STRUCT,
    TK_KW_TYPEDEF,
    TK_KW_STATIC,
    TK_KW_EXTERN,
    TK_KW_BOOL,
    TK_KW_VOLATILE,
    TK_KW_RESTRICT,
    TK_KW_INLINE,
    TK_KW_ALIGNOF,
    TK_KW_LONG_DOUBLE,
    TK_KW_COMPLEX,
    TK_KW_REAL,
    TK_KW_IMAG,
    TK_IDENT,
    TK_INT_LITERAL,
    TK_FLOAT_LITERAL,
    TK_CHAR_LITERAL,
    TK_STRING_LITERAL,
    TK_LPAREN,
    TK_RPAREN,
    TK_LBRACE,
    TK_RBRACE,
    TK_LBRACKET,
    TK_RBRACKET,
    TK_SEMICOLON,
    TK_COMMA,
    TK_PLUS,
    TK_MINUS,
    TK_STAR,
    TK_SLASH,
    TK_PERCENT,
    TK_AMP,
    TK_ANDAND,
    TK_OROR,
    TK_BITOR,
    TK_XOR,
    TK_TILDE,
    TK_NOT,
    TK_SHL,
    TK_SHR,
    TK_SHL_EQ,
    TK_SHR_EQ,
    TK_PLUS_EQ,
    TK_MINUS_EQ,
    TK_STAR_EQ,
    TK_SLASH_EQ,
    TK_PERCENT_EQ,
    TK_AMP_EQ,
    TK_BITOR_EQ,
    TK_XOR_EQ,
    TK_INC,
    TK_DEC,
    TK_QUESTION,
    TK_COLON,
    TK_DOT,
    TK_ELLIPSIS,
    TK_ARROW,
    TK_ASSIGN,
    TK_EQ,
    TK_NE,
    TK_LT,
    TK_LE,
    TK_GT,
    TK_GE,
    TK_EOF,
};typedef enum TokenKind TokenKind;
struct Token {
    TokenKind kind;
    char *text;
    SourceLoc loc;
};typedef struct Token Token;
struct TokenArray {
    Token *data;
    size_t len;
    size_t cap;
};typedef struct TokenArray TokenArray;
void token_array_init(TokenArray *a);
void token_array_free(TokenArray *a);
void token_array_push(TokenArray *a, Token t);
enum TypeKind {
    TY_VOID,
    TY_INT,
    TY_FLOAT,
    TY_PTR,
    TY_ARRAY,
    TY_STRUCT,
    TY_FUNC,
};typedef enum TypeKind TypeKind;
typedef struct Type Type;
struct Type {
    TypeKind kind;
    int width;
    int is_unsigned;
    unsigned is_const : 1;
    unsigned is_volatile : 1;
    unsigned is_restrict : 1;
    unsigned is_bool : 1;
    Type *pointee;
    Type *elem_type;
    int length;
    struct Expr *vla_dim;
    char *tag;
    Type *func_ret;
    Type *func_params;
    int func_nparams;
    int func_is_variadic;
    int enum_id;
    int bitfield_width;
    int is_vector;
};
static inline Type type_make_int(int width, int is_unsigned) {
    Type t; t.kind = TY_INT; t.width = width; t.is_unsigned = is_unsigned;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; return t;
}
static inline Type type_make_bool(void) {
    Type t = type_make_int(1, 1);
    t.is_bool = 1;
    return t;
}
static inline Type type_default_int(void) { return type_make_int(4, 0); }
static inline Type type_make_float(int width) {
    Type t; t.kind = TY_FLOAT; t.width = width; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; return t;
}
static inline Type type_make_void(void) {
    Type t; t.kind = TY_VOID; t.width = 0; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; return t;
}
Type type_clone(Type t);
void type_free(Type *t);
int type_size(Type t);
int type_align(Type t);
enum SysVRegClass {
    SYSV_CLS_INTEGER = 1,
    SYSV_CLS_SSE = 2
};typedef enum SysVRegClass SysVRegClass;
int sysv_classify_agg(Type t, SysVRegClass cls[2]);
Type type_make_ptr(Type pointee);
Type type_make_array(Type elem, int length);
Type type_make_vector(Type elem, int vec_size);
Type type_make_vla(Type elem, struct Expr *dim);
Type type_make_struct(const char *tag, int size);
Type type_make_func(Type ret, Type * *params, int nparams);
Type type_make_func_var(Type ret, Type * *params, int nparams, int is_variadic);
Type type_decay(Type t);
int type_is_ptr_or_array(Type t);
Type type_pointee_or_elem(Type t);
int type_funcs_equal(Type a, Type b);
struct Expr *expr_clone(const struct Expr *e);
enum ExprKind {
    EX_INT_LIT,
    EX_BINOP,
    EX_UNARY,
    EX_VAR,
    EX_ASSIGN,
    EX_CALL,
    EX_STR,
    EX_ADDR,
    EX_DEREF,
    EX_INDEX,
    EX_MEMBER,
    EX_CAST,
    EX_SIZEOF_TYPE,
    EX_SIZEOF_EXPR,
    EX_ALIGNOF_TYPE,
    EX_TERNARY,
    EX_INC_DEC,
    EX_COMPOUND_ASSIGN,
    EX_COMMA,
    EX_INIT_LIST,
    EX_FLOAT_LIT,
    EX_COMPOUND_LITERAL,
    EX_STMT_EXPR,
    EX_LABEL_ADDR,
};typedef enum ExprKind ExprKind;
enum BinOp {
    BOP_ADD,
    BOP_SUB,
    BOP_MUL,
    BOP_DIV,
    BOP_MOD,
    BOP_EQ,
    BOP_NE,
    BOP_LT,
    BOP_LE,
    BOP_GT,
    BOP_GE,
    BOP_AND,
    BOP_OR,
    BOP_BITAND,
    BOP_BITOR,
    BOP_BITXOR,
    BOP_SHL,
    BOP_SHR,
};typedef enum BinOp BinOp;
enum UnaryOp {
    UOP_NEG,
    UOP_POS,
    UOP_BITNOT,
    UOP_NOT,
};typedef enum UnaryOp UnaryOp;
typedef struct StmtArray StmtArray;
typedef struct Expr Expr;
int fold_const_int(const Expr *e, long long *out);
struct ExprArray {
    Expr **data;
    size_t len;
    size_t cap;
};typedef struct ExprArray ExprArray;
union __anon_u_1 {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
        struct { StmtArray *stmts; } stmt_expr;
        struct { char *label; } label_addr;
    };struct Expr {
    ExprKind kind;
    SourceLoc loc;
    Type type;
    Type va_arg_type;
    union {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
        struct { StmtArray *stmts; } stmt_expr;
        struct { char *label; } label_addr;
    } u;
};
Expr *expr_new_int(long long v, SourceLoc loc);
Expr *expr_new_int_typed(long long v, int width, int is_unsigned, SourceLoc loc);
Expr *expr_new_binop(BinOp op, Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_unary(UnaryOp op, Expr *operand, SourceLoc loc);
Expr *expr_new_var(const char *name, SourceLoc loc);
Expr *expr_new_var_qual(const char *pkg, const char *name, SourceLoc loc);
Expr *expr_new_assign(Expr *lvalue, Expr *rvalue, SourceLoc loc);
Expr *expr_new_call(Expr *callee, SourceLoc loc);
Expr *expr_new_str(const char *bytes, int len, SourceLoc loc);
Expr *expr_new_addr(Expr *operand, SourceLoc loc);
Expr *expr_new_deref(Expr *operand, SourceLoc loc);
Expr *expr_new_index(Expr *array, Expr *index, SourceLoc loc);
Expr *expr_new_member(Expr *obj, const char *name, SourceLoc loc);
Expr *expr_new_cast(Type target, Expr *operand, SourceLoc loc);
Expr *expr_new_sizeof_type(Type t, SourceLoc loc);
Expr *expr_new_sizeof_expr(Expr *operand, SourceLoc loc);
Expr *expr_new_alignof_type(Type t, SourceLoc loc);
Expr *expr_new_ternary(Expr *cond, Expr *then, Expr *else_, SourceLoc loc);
Expr *expr_new_inc_dec(Expr *operand, int is_inc, int is_prefix, SourceLoc loc);
Expr *expr_new_compound_assign(Expr *lvalue, Expr *rvalue, BinOp op, SourceLoc loc);
Expr *expr_new_comma(Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_init_list(Expr **elements, int num_elements, SourceLoc loc);
Expr *expr_new_float_lit(const char *text, int width, SourceLoc loc);
Expr *expr_new_compound_literal(Type target_type, Expr *init, SourceLoc loc);
Expr *expr_new_stmt_expr(StmtArray *stmts, SourceLoc loc);
Expr *expr_new_label_addr(const char *label, SourceLoc loc);
void expr_call_push_arg(Expr *e, Expr *arg);
void expr_call_set_callee(Expr *e, Expr *callee);
void expr_free(Expr *e);
void expr_set_type(Expr *e, Type t);
enum StmtKind {
    ST_DECL,
    ST_EXPR,
    ST_RETURN,
    ST_IF,
    ST_WHILE,
    ST_FOR,
    ST_BREAK,
    ST_CONTINUE,
    ST_BLOCK,
    ST_DO_WHILE,
    ST_GOTO,
    ST_LABEL,
    ST_SWITCH,
};typedef enum StmtKind StmtKind;
typedef struct Stmt Stmt;
struct StmtArray {
    Stmt *data;
    size_t len;
    size_t cap;
};
struct SwitchCase {
    int is_default;
    int value;
    char *label_name;
    StmtArray stmts;
};typedef struct SwitchCase SwitchCase;
union __anon_u_2 {
        struct { char *name; Type type; Expr *init; int storage_class; char *alias_target; int align; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; Expr *target_expr; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; Stmt *body; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    };struct Stmt {
    StmtKind kind;
    SourceLoc loc;
    union {
        struct { char *name; Type type; Expr *init; int storage_class; char *alias_target; int align; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; Expr *target_expr; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; Stmt *body; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    } u;
};
void stmt_array_init(StmtArray *a);
void stmt_array_push(StmtArray *a, Stmt s);
void stmt_array_free(StmtArray *a);
void stmt_free(Stmt *s);
Stmt *stmt_alloc(void);
void stmt_free_ptr(Stmt *s);
void switch_push_case(Stmt *s, int is_default, int value, const char *label_name);
struct Param {
    char *name;
    Type type;
    SourceLoc loc;
};typedef struct Param Param;
struct ParamArray {
    Param *data;
    size_t len;
    size_t cap;
};typedef struct ParamArray ParamArray;
void param_array_init(ParamArray *a);
void param_array_push(ParamArray *a, const char *name, Type type, SourceLoc loc);
void param_array_free(ParamArray *a);
struct FunctionDecl {
    char *name;
    Type ret_type;
    ParamArray params;
    StmtArray body;
    SourceLoc loc;
    int is_variadic;
    int is_unprototyped;
    int is_extern;
    int is_static;
    char *alias_target;
    int align;
};typedef struct FunctionDecl FunctionDecl;
struct PackageDecl {
    char *name;
    SourceLoc loc;
};typedef struct PackageDecl PackageDecl;
struct ImportDecl {
    char *name;
    SourceLoc loc;
};typedef struct ImportDecl ImportDecl;
struct ImportArray {
    ImportDecl *data;
    size_t len;
    size_t cap;
};typedef struct ImportArray ImportArray;
void import_array_init(ImportArray *a);
void import_array_push(ImportArray *a, const char *name, SourceLoc loc);
void import_array_free(ImportArray *a);
struct StructMember {
    char *name;
    Type type;
    int offset;
    int bit_width;
    int bit_offset;
};typedef struct StructMember StructMember;
struct StructDef {
    char *tag;
    int is_union;
    int is_big_endian;
    StructMember *members;
    int num_members;
    int cap_members;
    int size;
    int align;
    int is_packed;
    SourceLoc loc;
    Type *canonical_type;
    int bf_unit_type;
    int bf_unit_used;
    int bf_unit_offset;
};typedef struct StructDef StructDef;
struct StructRegistry {
    StructDef *data;
    size_t len;
    size_t cap;
};typedef struct StructRegistry StructRegistry;
void struct_registry_init(StructRegistry *r);
void struct_registry_free(StructRegistry *r);
StructDef *struct_registry_add(StructRegistry *r, const char *tag, SourceLoc loc);
StructDef *struct_registry_find(StructRegistry *r, const char *tag);
const StructDef *struct_registry_find_c(const StructRegistry *r, const char *tag);
void struct_def_push_member(StructDef *sd, const char *name, Type ty, int bit_width);
void struct_def_finish(StructDef *sd);
void struct_def_apply_sso(StructDef *sd, int is_big_endian);
void struct_def_fixup_self_types(StructDef *sd);
const StructMember *struct_lookup_member(const StructRegistry *reg,
                                         const StructDef *sd,
                                         const char *name,
                                         int *offset_out);
struct FunctionArray {
    FunctionDecl *data;
    size_t len;
    size_t cap;
};typedef struct FunctionArray FunctionArray;
struct EnumConstant {
    char *name;
    int value;
};typedef struct EnumConstant EnumConstant;
struct EnumDef {
    char *tag;
    EnumConstant *constants;
    int num_constants;
    int cap_constants;
    SourceLoc loc;
};typedef struct EnumDef EnumDef;
struct EnumRegistry {
    EnumDef *data;
    size_t len;
    size_t cap;
};typedef struct EnumRegistry EnumRegistry;
void enum_registry_init(EnumRegistry *r);
void enum_registry_free(EnumRegistry *r);
EnumDef *enum_registry_add(EnumRegistry *r, const char *tag, SourceLoc loc);
EnumDef *enum_registry_find(EnumRegistry *r, const char *tag);
int enum_def_push_constant(EnumDef *ed, const char *name, int has_value,
                            int value, SourceLoc loc);
const EnumConstant *enum_registry_find_constant(const EnumRegistry *r,
                                                const char *name);
struct TypedefEntry {
    char *name;
    Type type;
};typedef struct TypedefEntry TypedefEntry;
struct TypedefRegistry {
    TypedefEntry *data;
    size_t len;
    size_t cap;
};typedef struct TypedefRegistry TypedefRegistry;
void typedef_registry_init(TypedefRegistry *r);
void typedef_registry_free(TypedefRegistry *r);
TypedefEntry *typedef_registry_add(TypedefRegistry *r, const char *name, Type type);
const Type *typedef_registry_find(const TypedefRegistry *r, const char *name);
struct TranslationUnit {
    PackageDecl package;
    ImportArray imports;
    StmtArray globals;
    FunctionArray functions;
    StructRegistry structs;
    EnumRegistry enums;
    TypedefRegistry typedefs;
};typedef struct TranslationUnit TranslationUnit;
void tu_init(TranslationUnit *tu);
void tu_free(TranslationUnit *tu);
typedef struct FILE FILE;
typedef long fpos_t;
Type type_clone(Type t) {
    Type r = t;
    if (t.kind == TY_PTR && t.pointee) {
        if (t.pointee->kind == TY_STRUCT) {
            r.pointee = t.pointee;
        } else {
            r.pointee = runtime.malloc(sizeof(Type));
            if (!r.pointee) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
            *r.pointee = type_clone(*t.pointee);
        }
    } else {
        r.pointee = ((void*)0);
    }
    if ((t.kind == TY_ARRAY || t.is_vector) && t.elem_type) {
        if (t.elem_type->kind == TY_STRUCT) {
            r.elem_type = t.elem_type;
        } else {
            r.elem_type = runtime.malloc(sizeof(Type));
            if (!r.elem_type) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
            *r.elem_type = type_clone(*t.elem_type);
        }
    } else {
        r.elem_type = ((void*)0);
    }
    r.vla_dim = t.vla_dim ? expr_clone(t.vla_dim) : ((void*)0);
    r.tag = t.tag ? xstrdup(t.tag) : ((void*)0);
    if (t.kind == TY_FUNC && t.func_ret) {
        if (t.func_ret->kind == TY_STRUCT) {
            r.func_ret = t.func_ret;
        } else {
            r.func_ret = runtime.malloc(sizeof(Type));
            if (!r.func_ret) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
            *r.func_ret = type_clone(*t.func_ret);
        }
    } else {
        r.func_ret = ((void*)0);
    }
    if (t.kind == TY_FUNC && t.func_nparams > 0 && t.func_params) {
        r.func_params = runtime.malloc(t.func_nparams * sizeof(Type));
        if (!r.func_params) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        for (int i = 0; i < t.func_nparams; i++)
            r.func_params[i] = type_clone(t.func_params[i]);
    } else {
        r.func_params = ((void*)0);
    }
    r.func_is_variadic = t.func_is_variadic;
    return r;
}
void type_free(Type *t) {
    if (!t) return;
    if (t->pointee) {
        if (t->pointee->kind != TY_STRUCT) {
            type_free(t->pointee); runtime.free(t->pointee);
        }
        t->pointee = ((void*)0);
    }
    if (t->elem_type) {
        if (t->elem_type->kind != TY_STRUCT) {
            type_free(t->elem_type); runtime.free(t->elem_type);
        }
        t->elem_type = ((void*)0);
    }
    if (t->vla_dim) {
        expr_free(t->vla_dim);
        t->vla_dim = ((void*)0);
    }
    if (t->tag) { runtime.free(t->tag); t->tag = ((void*)0); }
    if (t->func_ret) {
        if (t->func_ret->kind != TY_STRUCT) {
            type_free(t->func_ret); runtime.free(t->func_ret);
        }
        t->func_ret = ((void*)0);
    }
    if (t->func_params) {
        for (int i = 0; i < t->func_nparams; i++) type_free(&t->func_params[i]);
        runtime.free(t->func_params); t->func_params = ((void*)0);
    }
}
int type_size(Type t) {
    if (t.is_vector) return t.width;
    const Type *p = &t;
    int count = 1;
    while (p->kind == TY_ARRAY && p->elem_type) {
        count *= p->length;
        p = p->elem_type;
    }
    if (p->is_vector) return count * p->width;
    switch (p->kind) {
    case TY_VOID: return 0;
    case TY_INT: return count * p->width;
    case TY_FLOAT: return count * p->width;
    case TY_PTR: return count * 8;
    case TY_ARRAY: return 0;
    case TY_STRUCT: {
        if (p->tag) {
            const StructRegistry *reg = get_ir_structs();
            if (!reg) reg = get_parser_structs();
            if (reg) {
                const StructDef *sd = struct_registry_find_c(reg, p->tag);
                if (sd && sd->size > 0) return count * sd->size;
            }
        }
        return count * p->width;
    }
    case TY_FUNC: return 0;
    }
    return 0;
}
Type type_make_vector(Type elem, int vec_size) {
    Type t = elem;
    t.is_vector = 1;
    t.width = vec_size;
    t.elem_type = runtime.malloc(sizeof(Type));
    if (!t.elem_type) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    *t.elem_type = type_clone(elem);
    int esz = type_size(elem);
    t.length = esz > 0 ? vec_size / esz : 1;
    return t;
}
Type type_make_ptr(Type pointee) {
    Type t; t.kind = TY_PTR; t.width = 8; t.is_unsigned = 1;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0;
    t.pointee = runtime.malloc(sizeof(Type));
    if (!t.pointee) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    *t.pointee = type_clone(pointee);
    return t;
}
static void type_fixup_struct_width(Type *t, const char *tag, int final_width) {
    if (!t || !tag) return;
    if (t->kind == TY_STRUCT && t->tag && runtime.strcmp(t->tag, tag) == 0) {
        t->width = final_width;
    }
    if (t->pointee) type_fixup_struct_width(t->pointee, tag, final_width);
    if (t->elem_type) type_fixup_struct_width(t->elem_type, tag, final_width);
    if (t->func_ret) type_fixup_struct_width(t->func_ret, tag, final_width);
    if (t->func_params) {
        for (int i = 0; i < t->func_nparams; i++)
            type_fixup_struct_width(&t->func_params[i], tag, final_width);
    }
}
const StructMember *struct_lookup_member(const StructRegistry *reg,
                                         const StructDef *sd,
                                         const char *name,
                                         int *offset_out) {
    if (!sd || !name) return ((void*)0);
    for (int i = 0; i < sd->num_members; i++) {
        const StructMember *m = &sd->members[i];
        if (m->name && m->name[0] && runtime.strcmp(m->name, name) == 0) {
            if (offset_out) *offset_out = m->offset;
            return m;
        }
        if ((!m->name || !m->name[0]) && m->type.kind == TY_STRUCT
            && m->type.tag && reg) {
            const StructDef *nested = struct_registry_find_c(reg, m->type.tag);
            int inner = 0;
            const StructMember *found =
                struct_lookup_member(reg, nested, name, &inner);
            if (found) {
                if (offset_out) *offset_out = m->offset + inner;
                return found;
            }
        }
    }
    return ((void*)0);
}
void struct_def_fixup_self_types(StructDef *sd) {
    if (!sd || !sd->tag) return;
    for (int i = 0; i < sd->num_members; i++) {
        type_fixup_struct_width(&sd->members[i].type, sd->tag, sd->size);
    }
}
Type type_make_array(Type elem, int length) {
    Type t; t.kind = TY_ARRAY; t.width = elem.width;
    t.is_unsigned = elem.is_unsigned;
    t.is_const = elem.is_const; t.is_volatile = elem.is_volatile; t.is_restrict = elem.is_restrict;
    t.is_bool = 0; t.length = length; t.vla_dim = ((void*)0);
    t.pointee = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0;
    t.elem_type = runtime.malloc(sizeof(Type));
    if (!t.elem_type) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    *t.elem_type = type_clone(elem);
    return t;
}
Type type_make_vla(Type elem, Expr *dim) {
    Type t = type_make_array(elem, -1);
    t.vla_dim = dim;
    return t;
}
Type type_make_struct(const char *tag, int size) {
    Type t; t.kind = TY_STRUCT; t.width = size; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0;
    t.tag = xstrdup(tag);
    return t;
}
Type type_make_func_var(Type ret, Type * *params, int nparams, int is_variadic) {
    Type t; t.kind = TY_FUNC; t.width = 0; t.is_unsigned = 0; t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0); t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0;
    t.func_is_variadic = is_variadic;
    t.func_ret = runtime.malloc(sizeof(Type));
    if (!t.func_ret) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    *t.func_ret = type_clone(ret);
    t.func_nparams = nparams;
    if (nparams > 0) {
        t.func_params = runtime.malloc(nparams * sizeof(Type));
        if (!t.func_params) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        for (int i = 0; i < nparams; i++)
            t.func_params[i] = type_clone(*params[i]);
    } else {
        t.func_params = ((void*)0);
    }
    return t;
}
Type type_make_func(Type ret, Type * *params, int nparams) {
    return type_make_func_var(ret, params, nparams, 0);
}
static int types_equal(Type a, Type b);
int type_funcs_equal(Type a, Type b) {
    if (a.kind != TY_FUNC || b.kind != TY_FUNC) return 0;
    if (!types_equal(*a.func_ret, *b.func_ret)) return 0;
    if (a.func_nparams != b.func_nparams) return 0;
    for (int i = 0; i < a.func_nparams; i++)
        if (!types_equal(a.func_params[i], b.func_params[i])) return 0;
    return 1;
}
static int types_equal(Type a, Type b) {
    if (a.kind != b.kind) return 0;
    switch (a.kind) {
    case TY_VOID: return 1;
    case TY_INT: return a.width == b.width && a.is_unsigned == b.is_unsigned;
    case TY_FLOAT: return a.width == b.width;
    case TY_PTR: return types_equal(*a.pointee, *b.pointee);
    case TY_ARRAY: return a.length == b.length && types_equal(*a.elem_type, *b.elem_type);
    case TY_STRUCT: return a.tag && b.tag && runtime.strcmp(a.tag, b.tag) == 0;
    case TY_FUNC: return type_funcs_equal(a, b);
    }
    return 0;
}
Type type_decay(Type t) {
    if (t.kind == TY_ARRAY) {
        Type r = type_make_ptr(*t.elem_type);
        return r;
    }
    return type_clone(t);
}
int type_is_ptr_or_array(Type t) {
    return t.kind == TY_PTR || t.kind == TY_ARRAY;
}
Type type_pointee_or_elem(Type t) {
    if (t.kind == TY_PTR) return type_clone(*t.pointee);
    if (t.kind == TY_ARRAY) return type_clone(*t.elem_type);
    return type_default_int();
}
void expr_set_type(Expr *e, Type t) {
    if (!e) { type_free(&t); return; }
    type_free(&e->type);
    e->type = t;
}
void struct_registry_init(StructRegistry *r) {
    r->data = ((void*)0); r->len = 0; r->cap = 0;
}
void struct_registry_free(StructRegistry *r) {
    for (size_t i = 0; i < r->len; i++) {
        StructDef *sd = &r->data[i];
        runtime.free(sd->tag);
        for (int j = 0; j < sd->num_members; j++) {
            runtime.free(sd->members[j].name);
            type_free(&sd->members[j].type);
        }
        runtime.free(sd->members);
    }
    runtime.free(r->data);
    r->data = ((void*)0); r->len = 0; r->cap = 0;
}
StructDef *struct_registry_add(StructRegistry *r, const char *tag, SourceLoc loc) {
    if (r->len >= r->cap) {
        size_t nc = r->cap ? r->cap * 2 : 4;
        r->data = runtime.realloc(r->data, nc * sizeof(StructDef));
        if (!r->data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        r->cap = nc;
    }
    StructDef *sd = &r->data[r->len++];
    runtime.memset(sd, 0, sizeof(StructDef));
    sd->tag = xstrdup(tag);
    sd->align = 1;
    sd->loc = loc;
    return sd;
}
StructDef *struct_registry_find(StructRegistry *r, const char *tag) {
    for (size_t i = 0; i < r->len; i++)
        if (runtime.strcmp(r->data[i].tag, tag) == 0) return &r->data[i];
    return ((void*)0);
}
const StructDef *struct_registry_find_c(const StructRegistry *r, const char *tag) {
    return struct_registry_find((StructRegistry *)r, tag);
}
static int align_up(int x, int align) {
    if (align <= 1) return x;
    return (x + align - 1) & ~(align - 1);
}
int type_align(Type t) {
    if (t.is_vector) return t.width > 16 ? 16 : (t.width > 0 ? t.width : 1);
    const Type *p = &t;
    while (p->kind == TY_ARRAY && p->elem_type) p = p->elem_type;
    if (p->is_vector) return p->width > 16 ? 16 : (p->width > 0 ? p->width : 1);
    switch (p->kind) {
    case TY_VOID: return 1;
    case TY_INT: return p->width;
    case TY_FLOAT: return p->width;
    case TY_PTR: return 8;
    case TY_ARRAY: return 1;
    case TY_STRUCT: {
        if (p->tag) {
            const StructRegistry *reg = get_ir_structs();
            if (!reg) reg = get_parser_structs();
            if (reg) {
                const StructDef *sd = struct_registry_find_c(reg, p->tag);
                if (sd && sd->align > 0) return sd->align;
            }
        }
        return 8;
    }
    case TY_FUNC: return 1;
    }
    return 1;
}
enum { SV_NO = 0, SV_INT = 1, SV_SSE = 2, SV_MEM = 3 };
static int sysv_merge(int a, int b) {
    if (a == b) return a;
    if (a == SV_NO) return b;
    if (b == SV_NO) return a;
    if (a == SV_MEM || b == SV_MEM) return SV_MEM;
    if (a == SV_INT || b == SV_INT) return SV_INT;
    return SV_SSE;
}
static int sysv_field_class(Type t) {
    switch (t.kind) {
    case TY_INT:
    case TY_PTR:
    case TY_ARRAY:
        return SV_INT;
    case TY_FLOAT:
        if (t.width == 16) return SV_MEM;
        return SV_SSE;
    case TY_STRUCT:
        return SV_MEM;
    default:
        return SV_MEM;
    }
}
int sysv_classify_agg(Type t, SysVRegClass cls[2]) {
    cls[0] = SYSV_CLS_INTEGER;
    cls[1] = SYSV_CLS_INTEGER;
    if (t.is_vector) {
        if (t.width == 16) {
            cls[0] = SYSV_CLS_SSE;
            cls[1] = SYSV_CLS_SSE;
            return 2;
        }
        if (t.width == 8) {
            cls[0] = SYSV_CLS_INTEGER;
            return 1;
        }
        if (t.width <= 4) {
            cls[0] = SYSV_CLS_INTEGER;
            return 1;
        }
        return 0;
    }
    if (t.kind != TY_STRUCT || !t.tag) return 0;
    int sz = type_size(t);
    if (sz <= 0 || sz > 16) return 0;
    const StructRegistry *reg = get_ir_structs();
    const StructDef *sd = ((void*)0);
    if (reg) sd = struct_registry_find_c(reg, t.tag);
    if (!sd) {
        int n = (sz + 7) / 8;
        cls[0] = SYSV_CLS_INTEGER;
        if (n > 1) cls[1] = SYSV_CLS_INTEGER;
        return n;
    }
    int eight[2] = { SV_NO, SV_NO };
    for (int mi = 0; mi < sd->num_members; mi++) {
        const StructMember *m = &sd->members[mi];
        int msz = m->bit_width > 0
                  ? (m->bit_width <= 8 ? 1 : m->bit_width <= 16 ? 2
                     : m->bit_width <= 32 ? 4 : 8)
                  : type_size(m->type);
        if (msz <= 0) continue;
        int start = m->offset;
        int end = start + msz;
        int fc = sysv_field_class(m->type);
        if (m->bit_width > 0) fc = SV_INT;
        if (fc == SV_MEM) return 0;
        for (int eb = 0; eb < 2; eb++) {
            int lo = eb * 8, hi = lo + 8;
            if (end <= lo || start >= hi) continue;
            eight[eb] = sysv_merge(eight[eb], fc);
            if (eight[eb] == SV_MEM) return 0;
        }
    }
    int n = (sz + 7) / 8;
    if (n < 1) n = 1;
    if (n > 2) return 0;
    for (int i = 0; i < n; i++) {
        int c = eight[i] == SV_NO ? SV_INT : eight[i];
        if (c == SV_MEM) return 0;
        cls[i] = (c == SV_SSE) ? SYSV_CLS_SSE : SYSV_CLS_INTEGER;
    }
    return n;
}
void struct_def_push_member(StructDef *sd, const char *name, Type ty, int bit_width) {
    if (sd->num_members >= sd->cap_members) {
        int nc = sd->cap_members ? sd->cap_members * 2 : 4;
        sd->members = runtime.realloc(sd->members, nc * sizeof(StructMember));
        if (!sd->members) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        sd->cap_members = nc;
    }
    int a = sd->is_packed ? 1 : type_align(ty);
    int sz = type_size(ty);
    if (!sd->is_packed && a > sd->align) sd->align = a;
    int off;
    if (sd->is_union) {
        off = 0;
    } else if (bit_width > 0 && ty.kind == TY_INT) {
        int unit_bits = sz * 8;
        if (sd->bf_unit_type == sz && sd->bf_unit_used + bit_width <= unit_bits) {
            off = sd->bf_unit_offset;
        } else {
            if (sd->bf_unit_used > 0)
                sd->size = sd->bf_unit_offset + sd->bf_unit_type;
            sd->bf_unit_type = sz;
            sd->bf_unit_used = 0;
            sd->bf_unit_offset = align_up(sd->size, a);
            off = sd->bf_unit_offset;
        }
        sd->members[sd->num_members].bit_offset = sd->bf_unit_used;
        sd->bf_unit_used += bit_width;
        sd->members[sd->num_members].offset = off;
        sd->members[sd->num_members].bit_width = bit_width;
        int unit_end = sd->bf_unit_offset + sz;
        if (unit_end > sd->size) sd->size = unit_end;
        sd->members[sd->num_members].name = xstrdup(name);
        sd->members[sd->num_members].type = type_clone(ty);
        sd->num_members++;
        return;
    } else {
        if (sd->bf_unit_used > 0) {
            sd->size = sd->bf_unit_offset + sd->bf_unit_type;
            sd->bf_unit_type = 0; sd->bf_unit_used = 0;
        }
        off = align_up(sd->size, a);
    }
    sd->members[sd->num_members].name = xstrdup(name);
    sd->members[sd->num_members].type = type_clone(ty);
    sd->members[sd->num_members].offset = off;
    sd->members[sd->num_members].bit_width = bit_width;
    sd->members[sd->num_members].bit_offset = 0;
    sd->num_members++;
    if (sd->is_union) {
        if (sz > sd->size) sd->size = sz;
    } else {
        sd->size = off + sz;
    }
}
void struct_def_finish(StructDef *sd) {
    if (sd->is_packed) sd->align = 1;
    sd->size = align_up(sd->size, sd->align);
}
void struct_def_apply_sso(StructDef *sd, int is_big_endian) {
    if (!sd) return;
    if (sd->is_big_endian == is_big_endian) return;
    sd->is_big_endian = is_big_endian;
    if (is_big_endian) {
        for (int i = 0; i < sd->num_members; i++) {
            StructMember *m = &sd->members[i];
            if (m->bit_width > 0) {
                int uw = type_size(m->type);
                if (uw > 8) uw = 8;
                if (uw < 1) uw = 1;
                int unit_bits = uw * 8;
                m->bit_offset = unit_bits - m->bit_offset - m->bit_width;
            }
        }
    }
}
void switch_push_case(Stmt *s, int is_default, int value, const char *label_name) {
    if (s->u.switch_s.num_cases >= s->u.switch_s.cap_cases) {
        int nc = s->u.switch_s.cap_cases ? s->u.switch_s.cap_cases * 2 : 4;
        s->u.switch_s.cases = runtime.realloc(s->u.switch_s.cases,
                                      nc * sizeof(SwitchCase));
        if (!s->u.switch_s.cases) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        s->u.switch_s.cap_cases = nc;
    }
    SwitchCase *c = &s->u.switch_s.cases[s->u.switch_s.num_cases++];
    c->is_default = is_default;
    c->value = value;
    c->label_name = label_name ? xstrdup(label_name) : ((void*)0);
    stmt_array_init(&c->stmts);
}
void enum_registry_init(EnumRegistry *r) {
    r->data = ((void*)0); r->len = 0; r->cap = 0;
}
void enum_registry_free(EnumRegistry *r) {
    for (size_t i = 0; i < r->len; i++) {
        EnumDef *ed = &r->data[i];
        runtime.free(ed->tag);
        for (int j = 0; j < ed->num_constants; j++)
            runtime.free(ed->constants[j].name);
        runtime.free(ed->constants);
    }
    runtime.free(r->data);
    r->data = ((void*)0); r->len = 0; r->cap = 0;
}
EnumDef *enum_registry_add(EnumRegistry *r, const char *tag, SourceLoc loc) {
    if (r->len >= r->cap) {
        size_t nc = r->cap ? r->cap * 2 : 4;
        r->data = runtime.realloc(r->data, nc * sizeof(EnumDef));
        if (!r->data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        r->cap = nc;
    }
    EnumDef *ed = &r->data[r->len++];
    ed->tag = tag ? xstrdup(tag) : ((void*)0);
    ed->constants = ((void*)0); ed->num_constants = 0; ed->cap_constants = 0;
    ed->loc = loc;
    return ed;
}
EnumDef *enum_registry_find(EnumRegistry *r, const char *tag) {
    if (!tag) return ((void*)0);
    for (size_t i = 0; i < r->len; i++)
        if (r->data[i].tag && runtime.strcmp(r->data[i].tag, tag) == 0) return &r->data[i];
    return ((void*)0);
}
int enum_def_push_constant(EnumDef *ed, const char *name, int has_value,
                           int value, SourceLoc loc) {
    (void)loc;
    if (ed->num_constants >= ed->cap_constants) {
        int nc = ed->cap_constants ? ed->cap_constants * 2 : 4;
        ed->constants = runtime.realloc(ed->constants, nc * sizeof(EnumConstant));
        if (!ed->constants) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        ed->cap_constants = nc;
    }
    int assigned;
    if (has_value) {
        assigned = value;
    } else {
        assigned = (ed->num_constants > 0)
            ? ed->constants[ed->num_constants - 1].value + 1 : 0;
    }
    ed->constants[ed->num_constants].name = xstrdup(name);
    ed->constants[ed->num_constants].value = assigned;
    ed->num_constants++;
    return assigned;
}
const EnumConstant *enum_registry_find_constant(const EnumRegistry *r,
                                                const char *name) {
    for (size_t i = 0; i < r->len; i++) {
        const EnumDef *ed = &r->data[i];
        for (int j = 0; j < ed->num_constants; j++)
            if (runtime.strcmp(ed->constants[j].name, name) == 0)
                return &ed->constants[j];
    }
    return ((void*)0);
}
void typedef_registry_init(TypedefRegistry *r) {
    r->data = ((void*)0); r->len = 0; r->cap = 0;
}
void typedef_registry_free(TypedefRegistry *r) {
    for (size_t i = 0; i < r->len; i++) {
        runtime.free(r->data[i].name);
        type_free(&r->data[i].type);
    }
    runtime.free(r->data);
    r->data = ((void*)0); r->len = 0; r->cap = 0;
}
TypedefEntry *typedef_registry_add(TypedefRegistry *r, const char *name, Type type) {
    if (r->len >= r->cap) {
        size_t nc = r->cap ? r->cap * 2 : 4;
        r->data = runtime.realloc(r->data, nc * sizeof(TypedefEntry));
        if (!r->data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        r->cap = nc;
    }
    TypedefEntry *e = &r->data[r->len++];
    e->name = xstrdup(name);
    e->type = type;
    return e;
}
const Type *typedef_registry_find(const TypedefRegistry *r, const char *name) {
    for (size_t i = 0; i < r->len; i++)
        if (runtime.strcmp(r->data[i].name, name) == 0) return &r->data[i].type;
    return ((void*)0);
}
Expr *expr_new_int(long long v, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    e->kind = EX_INT_LIT;
    e->loc = loc;
    e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    e->u.int_val = v;
    return e;
}
Expr *expr_new_int_typed(long long v, int width, int is_unsigned, SourceLoc loc) {
    Expr *e = expr_new_int(v, loc);
    e->type = type_make_int(width, is_unsigned);
    return e;
}
Expr *expr_new_binop(BinOp op, Expr *l, Expr *r, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    e->kind = EX_BINOP;
    e->loc = loc;
    e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    e->u.bin.op = op;
    e->u.bin.l = l;
    e->u.bin.r = r;
    return e;
}
Expr *expr_new_unary(UnaryOp op, Expr *operand, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    e->kind = EX_UNARY;
    e->loc = loc;
    e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    e->u.un.op = op;
    e->u.un.operand = operand;
    return e;
}
Expr *expr_new_var(const char *name, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    e->kind = EX_VAR;
    e->loc = loc;
    e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    e->u.var.name = xstrdup(name);
    e->u.var.pkg = ((void*)0);
    return e;
}
Expr *expr_new_var_qual(const char *pkg, const char *name, SourceLoc loc) {
    Expr *e = expr_new_var(name, loc);
    e->u.var.pkg = xstrdup(pkg);
    return e;
}
Expr *expr_new_assign(Expr *lvalue, Expr *rvalue, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    e->kind = EX_ASSIGN;
    e->loc = loc;
    e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    e->u.assign.lvalue = lvalue;
    e->u.assign.rvalue = rvalue;
    return e;
}
Expr *expr_new_call(Expr *callee, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    e->kind = EX_CALL;
    e->loc = loc;
    e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    e->u.call.callee = callee;
    e->u.call.args.data = ((void*)0);
    e->u.call.args.len = 0;
    e->u.call.args.cap = 0;
    return e;
}
void expr_call_set_callee(Expr *e, Expr *callee) {
    if (!e || e->kind != EX_CALL) return;
    if (e->u.call.callee) expr_free(e->u.call.callee);
    e->u.call.callee = callee;
}
Expr *expr_new_str(const char *bytes, int len, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    e->kind = EX_STR;
    e->loc = loc;
    e->type = type_default_int();
    e->u.str.bytes = runtime.malloc(len + 1);
    if (!e->u.str.bytes) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    runtime.memcpy(e->u.str.bytes, bytes, len);
    e->u.str.bytes[len] = '\0';
    e->u.str.len = len;
    return e;
}
static Expr *expr_alloc(ExprKind k, SourceLoc loc);
Expr *expr_new_float_lit(const char *text, int width, SourceLoc loc) {
    Expr *e = expr_alloc(EX_FLOAT_LIT, loc);
    e->u.float_text = xstrdup(text);
    e->type = type_make_float(width);
    return e;
}
void expr_call_push_arg(Expr *e, Expr *arg) {
    ExprArray *a = &e->u.call.args;
    if (a->len >= a->cap) {
        a->cap = a->cap ? a->cap * 2 : 4;
        a->data = runtime.realloc(a->data, a->cap * sizeof(Expr *));
        if (!a->data) { runtime.fprintf(runtime.stderr, "fakecc: out of memory\n"); runtime.exit(1); }
    }
    a->data[a->len++] = arg;
}
static Expr *expr_alloc(ExprKind k, SourceLoc loc) {
    Expr *e = runtime.malloc(sizeof(Expr));
    if (!e) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    e->kind = k; e->loc = loc; e->type = type_default_int();
    runtime.memset(&e->va_arg_type, 0, sizeof(e->va_arg_type));
    return e;
}
Expr *expr_new_addr(Expr *operand, SourceLoc loc) {
    Expr *e = expr_alloc(EX_ADDR, loc); e->u.addr.operand = operand; return e;
}
Expr *expr_new_deref(Expr *operand, SourceLoc loc) {
    Expr *e = expr_alloc(EX_DEREF, loc); e->u.deref.operand = operand; return e;
}
Expr *expr_new_index(Expr *array, Expr *index, SourceLoc loc) {
    Expr *e = expr_alloc(EX_INDEX, loc);
    e->u.idx.array = array; e->u.idx.index = index; return e;
}
Expr *expr_new_member(Expr *obj, const char *name, SourceLoc loc) {
    Expr *e = expr_alloc(EX_MEMBER, loc);
    e->u.member.obj = obj;
    e->u.member.name = xstrdup(name);
    return e;
}
Expr *expr_new_cast(Type target, Expr *operand, SourceLoc loc) {
    Expr *e = expr_alloc(EX_CAST, loc);
    e->u.cast.target = type_clone(target); e->u.cast.operand = operand; return e;
}
Expr *expr_new_sizeof_type(Type t, SourceLoc loc) {
    Expr *e = expr_alloc(EX_SIZEOF_TYPE, loc);
    e->u.sizeof_t.target = type_clone(t); return e;
}
Expr *expr_new_sizeof_expr(Expr *operand, SourceLoc loc) {
    Expr *e = expr_alloc(EX_SIZEOF_EXPR, loc);
    e->u.sizeof_e.operand = operand; return e;
}
Expr *expr_new_alignof_type(Type t, SourceLoc loc) {
    Expr *e = expr_alloc(EX_ALIGNOF_TYPE, loc);
    e->u.alignof_t.target = type_clone(t); return e;
}
Expr *expr_new_ternary(Expr *cond, Expr *then, Expr *else_, SourceLoc loc) {
    Expr *e = expr_alloc(EX_TERNARY, loc);
    e->u.tern.cond = cond; e->u.tern.then = then; e->u.tern.else_ = else_; return e;
}
Expr *expr_new_inc_dec(Expr *operand, int is_inc, int is_prefix, SourceLoc loc) {
    Expr *e = expr_alloc(EX_INC_DEC, loc);
    e->u.incdec.operand = operand; e->u.incdec.is_inc = is_inc;
    e->u.incdec.is_prefix = is_prefix; return e;
}
Expr *expr_new_compound_assign(Expr *lvalue, Expr *rvalue, BinOp op, SourceLoc loc) {
    Expr *e = expr_alloc(EX_COMPOUND_ASSIGN, loc);
    e->u.comp.lvalue = lvalue; e->u.comp.rvalue = rvalue; e->u.comp.op = op; return e;
}
Expr *expr_new_comma(Expr *l, Expr *r, SourceLoc loc) {
    Expr *e = expr_alloc(EX_COMMA, loc);
    e->u.comma.lhs = l; e->u.comma.rhs = r; return e;
}
Expr *expr_new_init_list(Expr **elements, int num_elements, SourceLoc loc) {
    Expr *e = expr_alloc(EX_INIT_LIST, loc);
    e->u.init_list.elements = elements;
    e->u.init_list.num_elements = num_elements;
    e->u.init_list.desig_kind = runtime.malloc(num_elements * sizeof(int));
    e->u.init_list.desig_index = runtime.malloc(num_elements * sizeof(int));
    e->u.init_list.desig_member = runtime.calloc(num_elements, sizeof(char *));
    for (int i = 0; i < num_elements; i++) {
        e->u.init_list.desig_kind[i] = -1;
        e->u.init_list.desig_index[i] = -1;
    }
    return e;
}
Expr *expr_new_compound_literal(Type target_type, Expr *init, SourceLoc loc) {
    Expr *e = expr_alloc(EX_COMPOUND_LITERAL, loc);
    e->u.compound.target_type = type_clone(target_type);
    e->u.compound.init = init;
    return e;
}
Expr *expr_new_stmt_expr(StmtArray *stmts, SourceLoc loc) {
    Expr *e = expr_alloc(EX_STMT_EXPR, loc);
    e->u.stmt_expr.stmts = runtime.malloc(sizeof(StmtArray));
    if (!e->u.stmt_expr.stmts) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    *e->u.stmt_expr.stmts = *stmts;
    return e;
}
Expr *expr_new_label_addr(const char *label, SourceLoc loc) {
    Expr *e = expr_alloc(EX_LABEL_ADDR, loc);
    e->u.label_addr.label = xstrdup(label);
    return e;
}
void expr_free(Expr *e) {
    if (!e) return;
    switch (e->kind) {
    case EX_INT_LIT:
        break;
    case EX_BINOP:
        expr_free(e->u.bin.l);
        expr_free(e->u.bin.r);
        break;
    case EX_UNARY:
        expr_free(e->u.un.operand);
        break;
    case EX_VAR:
        runtime.free(e->u.var.name);
        runtime.free(e->u.var.pkg);
        break;
    case EX_ASSIGN:
        expr_free(e->u.assign.lvalue);
        expr_free(e->u.assign.rvalue);
        break;
    case EX_CALL:
        expr_free(e->u.call.callee);
        for (size_t i = 0; i < e->u.call.args.len; i++)
            expr_free(e->u.call.args.data[i]);
        runtime.free(e->u.call.args.data);
        type_free(&e->va_arg_type);
        break;
    case EX_STR:
        runtime.free(e->u.str.bytes);
        break;
    case EX_FLOAT_LIT:
        runtime.free(e->u.float_text);
        break;
    case EX_ADDR: expr_free(e->u.addr.operand); break;
    case EX_DEREF: expr_free(e->u.deref.operand); break;
    case EX_INDEX:
        expr_free(e->u.idx.array); expr_free(e->u.idx.index); break;
    case EX_MEMBER:
        expr_free(e->u.member.obj);
        runtime.free(e->u.member.name);
        break;
    case EX_CAST:
        type_free(&e->u.cast.target);
        expr_free(e->u.cast.operand);
        break;
    case EX_SIZEOF_TYPE:
        type_free(&e->u.sizeof_t.target); break;
    case EX_SIZEOF_EXPR:
        expr_free(e->u.sizeof_e.operand); break;
    case EX_TERNARY:
        expr_free(e->u.tern.cond);
        expr_free(e->u.tern.then);
        expr_free(e->u.tern.else_);
        break;
    case EX_INC_DEC:
        expr_free(e->u.incdec.operand);
        break;
    case EX_COMPOUND_ASSIGN:
        expr_free(e->u.comp.lvalue);
        expr_free(e->u.comp.rvalue);
        break;
    case EX_COMMA:
        expr_free(e->u.comma.lhs);
        expr_free(e->u.comma.rhs);
        break;
    case EX_INIT_LIST: {
        for (int i = 0; i < e->u.init_list.num_elements; i++)
            expr_free(e->u.init_list.elements[i]);
        runtime.free(e->u.init_list.elements);
        if (e->u.init_list.desig_member) {
            for (int i = 0; i < e->u.init_list.num_elements; i++)
                runtime.free(e->u.init_list.desig_member[i]);
        }
        runtime.free(e->u.init_list.desig_kind);
        runtime.free(e->u.init_list.desig_index);
        runtime.free(e->u.init_list.desig_member);
        break;
    }
    case EX_COMPOUND_LITERAL:
        type_free(&e->u.compound.target_type);
        expr_free(e->u.compound.init);
        break;
    case EX_ALIGNOF_TYPE:
        type_free(&e->u.alignof_t.target);
        break;
    case EX_STMT_EXPR:
        if (e->u.stmt_expr.stmts) {
            stmt_array_free(e->u.stmt_expr.stmts);
            runtime.free(e->u.stmt_expr.stmts);
        }
        break;
    case EX_LABEL_ADDR:
        runtime.free(e->u.label_addr.label);
        break;
    }
    type_free(&e->type);
    runtime.free(e);
}
void stmt_free(Stmt *s) {
    if (!s) return;
    switch (s->kind) {
    case ST_DECL:
        runtime.free(s->u.decl.name);
        type_free(&s->u.decl.type);
        expr_free(s->u.decl.init);
        runtime.free(s->u.decl.alias_target);
        break;
    case ST_EXPR:
        expr_free(s->u.expr);
        break;
    case ST_RETURN:
        expr_free(s->u.value);
        break;
    case ST_IF:
        expr_free(s->u.if_s.cond);
        stmt_free_ptr(s->u.if_s.then_s);
        stmt_free_ptr(s->u.if_s.else_s);
        break;
    case ST_WHILE:
        expr_free(s->u.while_s.cond);
        stmt_free_ptr(s->u.while_s.body);
        break;
    case ST_DO_WHILE:
        expr_free(s->u.do_s.cond);
        stmt_free_ptr(s->u.do_s.body);
        break;
    case ST_GOTO:
        runtime.free(s->u.goto_s.target);
        expr_free(s->u.goto_s.target_expr);
        break;
    case ST_LABEL:
        runtime.free(s->u.label_s.name);
        stmt_free_ptr(s->u.label_s.stmt);
        break;
    case ST_SWITCH:
        expr_free(s->u.switch_s.cond);
        stmt_free_ptr(s->u.switch_s.body);
        for (int i = 0; i < s->u.switch_s.num_cases; i++) {
            runtime.free(s->u.switch_s.cases[i].label_name);
            stmt_array_free(&s->u.switch_s.cases[i].stmts);
        }
        runtime.free(s->u.switch_s.cases);
        break;
    case ST_FOR:
        stmt_free_ptr(s->u.for_s.init);
        expr_free(s->u.for_s.cond);
        expr_free(s->u.for_s.step);
        stmt_free_ptr(s->u.for_s.body);
        break;
    case ST_BREAK:
    case ST_CONTINUE:
        break;
    case ST_BLOCK:
        stmt_array_free(&s->u.block);
        break;
    }
}
Stmt *stmt_alloc(void) {
    Stmt *s = runtime.malloc(sizeof(Stmt));
    if (!s) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    return s;
}
void stmt_free_ptr(Stmt *s) {
    if (!s) return;
    stmt_free(s);
    runtime.free(s);
}
void stmt_array_init(StmtArray *a) {
    a->data = ((void*)0);
    a->len = 0;
    a->cap = 0;
}
void stmt_array_push(StmtArray *a, Stmt s) {
    if (a->len >= a->cap) {
        size_t new_cap = a->cap ? a->cap * 2 : 8;
        a->data = runtime.realloc(a->data, new_cap * sizeof(Stmt));
        if (!a->data) {
            runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
            runtime.exit(1);
        }
        a->cap = new_cap;
    }
    a->data[a->len++] = s;
}
void stmt_array_free(StmtArray *a) {
    for (size_t i = 0; i < a->len; i++) {
        stmt_free(&a->data[i]);
    }
    runtime.free(a->data);
    a->data = ((void*)0);
    a->len = 0;
    a->cap = 0;
}
void import_array_init(ImportArray *a) {
    a->data = ((void*)0);
    a->len = 0;
    a->cap = 0;
}
void import_array_push(ImportArray *a, const char *name, SourceLoc loc) {
    if (a->len >= a->cap) {
        a->cap = a->cap ? a->cap * 2 : 4;
        a->data = runtime.realloc(a->data, a->cap * sizeof(ImportDecl));
        if (!a->data) { runtime.fprintf(runtime.stderr, "fakecc: out of memory\n"); runtime.exit(1); }
    }
    a->data[a->len].name = xstrdup(name);
    a->data[a->len].loc = loc;
    a->len++;
}
void import_array_free(ImportArray *a) {
    for (size_t i = 0; i < a->len; i++)
        runtime.free(a->data[i].name);
    runtime.free(a->data);
    a->data = ((void*)0);
    a->len = 0;
    a->cap = 0;
}
void tu_init(TranslationUnit *tu) {
    tu->package.name = ((void*)0);
    tu->package.loc.file = ((void*)0);
    tu->package.loc.line = 0;
    tu->package.loc.col = 0;
    import_array_init(&tu->imports);
    stmt_array_init(&tu->globals);
    tu->functions.data = ((void*)0);
    tu->functions.len = 0;
    tu->functions.cap = 0;
    struct_registry_init(&tu->structs);
    enum_registry_init(&tu->enums);
    typedef_registry_init(&tu->typedefs);
    SourceLoc vloc = {0};
    StructDef *va = struct_registry_add(&tu->structs, "__va_list_tag", vloc);
    struct_def_push_member(va, "gp_offset", type_make_int(4, 1), 0);
    struct_def_push_member(va, "fp_offset", type_make_int(4, 1), 0);
    struct_def_push_member(va, "overflow_arg_area", type_make_ptr(type_make_void()), 0);
    struct_def_push_member(va, "reg_save_area", type_make_ptr(type_make_void()), 0);
    struct_def_finish(va);
    Type va_type = type_make_struct("__va_list_tag", va->size);
    typedef_registry_add(&tu->typedefs, "va_list", va_type);
    typedef_registry_add(&tu->typedefs, "__builtin_va_list", type_clone(va_type));
    typedef_registry_add(&tu->typedefs, "__INT8_TYPE__", type_make_int(1, 0));
    typedef_registry_add(&tu->typedefs, "__UINT8_TYPE__", type_make_int(1, 1));
    typedef_registry_add(&tu->typedefs, "__INT16_TYPE__", type_make_int(2, 0));
    typedef_registry_add(&tu->typedefs, "__UINT16_TYPE__", type_make_int(2, 1));
    typedef_registry_add(&tu->typedefs, "__INT32_TYPE__", type_make_int(4, 0));
    typedef_registry_add(&tu->typedefs, "__UINT32_TYPE__", type_make_int(4, 1));
    typedef_registry_add(&tu->typedefs, "__INT64_TYPE__", type_make_int(8, 0));
    typedef_registry_add(&tu->typedefs, "__UINT64_TYPE__", type_make_int(8, 1));
    typedef_registry_add(&tu->typedefs, "__INTMAX_TYPE__", type_make_int(8, 0));
    typedef_registry_add(&tu->typedefs, "__UINTMAX_TYPE__", type_make_int(8, 1));
    typedef_registry_add(&tu->typedefs, "__SIZE_TYPE__", type_make_int(8, 1));
    typedef_registry_add(&tu->typedefs, "__PTRDIFF_TYPE__", type_make_int(8, 0));
    typedef_registry_add(&tu->typedefs, "__WCHAR_TYPE__", type_make_int(4, 0));
}
void tu_free(TranslationUnit *tu) {
    runtime.free(tu->package.name);
    import_array_free(&tu->imports);
    stmt_array_free(&tu->globals);
    for (size_t i = 0; i < tu->functions.len; i++) {
        runtime.free(tu->functions.data[i].name);
        type_free(&tu->functions.data[i].ret_type);
        param_array_free(&tu->functions.data[i].params);
        stmt_array_free(&tu->functions.data[i].body);
        runtime.free(tu->functions.data[i].alias_target);
    }
    runtime.free(tu->functions.data);
    struct_registry_free(&tu->structs);
    enum_registry_free(&tu->enums);
    typedef_registry_free(&tu->typedefs);
}
void param_array_init(ParamArray *a) {
    a->data = ((void*)0); a->len = 0; a->cap = 0;
}
void param_array_push(ParamArray *a, const char *name, Type type, SourceLoc loc) {
    if (a->len >= a->cap) {
        a->cap = a->cap ? a->cap * 2 : 4;
        a->data = runtime.realloc(a->data, a->cap * sizeof(Param));
        if (!a->data) { runtime.fprintf(runtime.stderr, "fakecc: out of memory\n"); runtime.exit(1); }
    }
    a->data[a->len].name = xstrdup(name);
    a->data[a->len].type = type;
    a->data[a->len].loc = loc;
    a->len++;
}
void param_array_free(ParamArray *a) {
    for (size_t i = 0; i < a->len; i++) {
        runtime.free(a->data[i].name);
        type_free(&a->data[i].type);
    }
    runtime.free(a->data);
    a->data = ((void*)0); a->len = 0; a->cap = 0;
}
int fold_const_int(const Expr *e, long long *out) {
    if (!e) return 0;
    if (e->kind == EX_INT_LIT) {
        *out = e->u.int_val;
        return 1;
    }
    if (e->kind == EX_VAR && runtime.strcmp(e->u.var.name, "__CHAR_BIT__") == 0) {
        *out = 8;
        return 1;
    }
    if (e->kind == EX_CAST) {
        return fold_const_int(e->u.cast.operand, out);
    }
    if (e->kind == EX_UNARY) {
        long long v;
        if (!fold_const_int(e->u.un.operand, &v)) return 0;
        switch (e->u.un.op) {
        case UOP_NEG: *out = -v; return 1;
        case UOP_POS: *out = v; return 1;
        case UOP_BITNOT: *out = ~v; return 1;
        case UOP_NOT: *out = !v ? 1 : 0; return 1;
        default: return 0;
        }
    }
    if (e->kind == EX_BINOP) {
long long l;
long long r;
        if (!fold_const_int(e->u.bin.l, &l)) return 0;
        if (!fold_const_int(e->u.bin.r, &r)) return 0;
        switch (e->u.bin.op) {
        case BOP_ADD: *out = l + r; return 1;
        case BOP_SUB: *out = l - r; return 1;
        case BOP_MUL: *out = l * r; return 1;
        case BOP_DIV: if (r == 0) { *out = 0; return 1; } *out = l / r; return 1;
        case BOP_MOD: if (r == 0) { *out = 0; return 1; } *out = l % r; return 1;
        case BOP_BITAND: *out = l & r; return 1;
        case BOP_BITOR: *out = l | r; return 1;
        case BOP_BITXOR: *out = l ^ r; return 1;
        case BOP_SHL: *out = l << r; return 1;
        case BOP_SHR: *out = l >> r; return 1;
        case BOP_EQ: *out = (l == r) ? 1 : 0; return 1;
        case BOP_NE: *out = (l != r) ? 1 : 0; return 1;
        case BOP_LT: *out = (l < r) ? 1 : 0; return 1;
        case BOP_LE: *out = (l <= r) ? 1 : 0; return 1;
        case BOP_GT: *out = (l > r) ? 1 : 0; return 1;
        case BOP_GE: *out = (l >= r) ? 1 : 0; return 1;
        default: return 0;
        }
    }
    if (e->kind == EX_SIZEOF_TYPE) {
        *out = type_size(e->u.sizeof_t.target);
        return 1;
    }
    if (e->kind == EX_ALIGNOF_TYPE) {
        *out = type_align(e->u.alignof_t.target);
        return 1;
    }
    return 0;
}
Expr *expr_clone(const Expr *e) {
    if (!e) return ((void*)0);
    Expr *r = runtime.malloc(sizeof(Expr));
    if (!r) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    *r = *e;
    r->type = type_clone(e->type);
    r->va_arg_type = type_clone(e->va_arg_type);
    switch (e->kind) {
    case EX_BINOP:
        r->u.bin.l = expr_clone(e->u.bin.l);
        r->u.bin.r = expr_clone(e->u.bin.r);
        break;
    case EX_UNARY:
        r->u.un.operand = expr_clone(e->u.un.operand);
        break;
    case EX_VAR:
        r->u.var.name = e->u.var.name ? xstrdup(e->u.var.name) : ((void*)0);
        r->u.var.pkg = e->u.var.pkg ? xstrdup(e->u.var.pkg) : ((void*)0);
        break;
    case EX_ASSIGN:
        r->u.assign.lvalue = expr_clone(e->u.assign.lvalue);
        r->u.assign.rvalue = expr_clone(e->u.assign.rvalue);
        break;
    case EX_CALL:
        r->u.call.callee = expr_clone(e->u.call.callee);
        r->u.call.args.len = e->u.call.args.len;
        r->u.call.args.cap = e->u.call.args.len;
        if (e->u.call.args.len > 0) {
            r->u.call.args.data = runtime.malloc(e->u.call.args.len * sizeof(Expr*));
            for (size_t i = 0; i < e->u.call.args.len; i++)
                r->u.call.args.data[i] = expr_clone(e->u.call.args.data[i]);
        } else {
            r->u.call.args.data = ((void*)0);
        }
        break;
    case EX_STR:
        r->u.str.bytes = e->u.str.bytes ? runtime.malloc(e->u.str.len + 1) : ((void*)0);
        if (r->u.str.bytes) {
            runtime.memcpy(r->u.str.bytes, e->u.str.bytes, e->u.str.len);
            r->u.str.bytes[e->u.str.len] = '\0';
        }
        break;
    case EX_ADDR:
        r->u.addr.operand = expr_clone(e->u.addr.operand);
        break;
    case EX_DEREF:
        r->u.deref.operand = expr_clone(e->u.deref.operand);
        break;
    case EX_INDEX:
        r->u.idx.array = expr_clone(e->u.idx.array);
        r->u.idx.index = expr_clone(e->u.idx.index);
        break;
    case EX_MEMBER:
        r->u.member.obj = expr_clone(e->u.member.obj);
        r->u.member.name = e->u.member.name ? xstrdup(e->u.member.name) : ((void*)0);
        break;
    case EX_CAST:
        r->u.cast.target = type_clone(e->u.cast.target);
        r->u.cast.operand = expr_clone(e->u.cast.operand);
        break;
    case EX_SIZEOF_TYPE:
        r->u.sizeof_t.target = type_clone(e->u.sizeof_t.target);
        break;
    case EX_SIZEOF_EXPR:
        r->u.sizeof_e.operand = expr_clone(e->u.sizeof_e.operand);
        break;
    case EX_ALIGNOF_TYPE:
        r->u.alignof_t.target = type_clone(e->u.alignof_t.target);
        break;
    case EX_TERNARY:
        r->u.tern.cond = expr_clone(e->u.tern.cond);
        r->u.tern.then = expr_clone(e->u.tern.then);
        r->u.tern.else_ = expr_clone(e->u.tern.else_);
        break;
    case EX_INC_DEC:
        r->u.incdec.operand = expr_clone(e->u.incdec.operand);
        break;
    case EX_COMPOUND_ASSIGN:
        r->u.comp.lvalue = expr_clone(e->u.comp.lvalue);
        r->u.comp.rvalue = expr_clone(e->u.comp.rvalue);
        break;
    case EX_COMMA:
        r->u.comma.lhs = expr_clone(e->u.comma.lhs);
        r->u.comma.rhs = expr_clone(e->u.comma.rhs);
        break;
    case EX_FLOAT_LIT:
        r->u.float_text = e->u.float_text ? xstrdup(e->u.float_text) : ((void*)0);
        break;
    case EX_LABEL_ADDR:
        r->u.label_addr.label = e->u.label_addr.label ? xstrdup(e->u.label_addr.label) : ((void*)0);
        break;
    default:
        break;
    }
    return r;
}
