package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
void die_at(const char *file, int line, int col, const char *fmt, ...);

typedef struct FILE FILE;
typedef long fpos_t;
void buffer_init(Buffer *b) {
    b->data = ((void*)0);
    b->len = 0;
    b->cap = 0;
}
void buffer_free(Buffer *b) {
    runtime.free(b->data);
    b->data = ((void*)0);
    b->len = 0;
    b->cap = 0;
}
static void buffer_grow(Buffer *b, size_t need) {
    if (b->len + need <= b->cap) return;
    size_t new_cap = b->cap ? b->cap * 2 : 256;
    while (new_cap < b->len + need) new_cap *= 2;
    b->data = runtime.realloc(b->data, new_cap);
    if (!b->data) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    b->cap = new_cap;
}
void buffer_append(Buffer *b, const char *s, size_t n) {
    buffer_grow(b, n);
    runtime.memcpy(b->data + b->len, s, n);
    b->len += n;
}
void buffer_appendf(Buffer *b, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    va_list ap2;
    __fakecc_va_copy((ap2), (ap));
    int n = runtime.vsnprintf(((void*)0), 0, fmt, ap2);
    va_end(ap2);
    if (n < 0) {
        runtime.fprintf(runtime.stderr, "fakecc: vsnprintf failed\n");
        runtime.exit(1);
    }
    size_t need = (size_t)n;
    buffer_grow(b, need + 1);
    runtime.vsnprintf(b->data + b->len, need + 1, fmt, ap);
    b->len += need;
    va_end(ap);
}
void *xmalloc(size_t n) {
    void *p = runtime.malloc(n);
    if (!p) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    return p;
}
void *xrealloc(void *p, size_t n) {
    void *q = runtime.realloc(p, n);
    if (!q) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    return q;
}
char *xstrdup(const char *s) {
    size_t len = runtime.strlen(s) + 1;
    char *d = runtime.malloc(len);
    if (!d) {
        runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
        runtime.exit(1);
    }
    runtime.memcpy(d, s, len);
    return d;
}
void die_at(const char *file, int line, int col, const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    runtime.fprintf(runtime.stderr, "%s:%d:%d: error: ", file ? file : "(unknown)", line, col);
    runtime.vfprintf(runtime.stderr, fmt, ap);
    runtime.fprintf(runtime.stderr, "\n");
    va_end(ap);
    runtime.exit(1);
}
