package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct FakeccOptions {
    int opt_level;
    int want_debug;
    int nostdlib;
    const char *rt_dir;
    const char **needed;
    size_t num_needed;
    const char **lib_paths;
    size_t num_lib_paths;
};typedef struct FakeccOptions FakeccOptions;
void fakecc_options_init(FakeccOptions *opts);
int fakecc_compile_string_to_so(const char *source,
                                const char *output_so_path,
                                const FakeccOptions *opts);
int fakecc_compile_string_to_executable(const char *source,
                                        const char *output_path,
                                        const FakeccOptions *opts);
int fakecc_compile_string_to_obj(const char *source,
                                 const char *output_obj_path,
                                 const FakeccOptions *opts);
int fakecc_compile_file_to_so(const char *source_path,
                              const char *output_so_path,
                              const FakeccOptions *opts);
int fakecc_compile_file_to_executable(const char *source_path,
                                      const char *output_path,
                                      const FakeccOptions *opts);
int fakecc_compile_file_to_obj(const char *source_path,
                               const char *output_obj_path,
                               const FakeccOptions *opts);
int fakecc_compile_files(const char **input_paths,
                         size_t num_inputs,
                         const char *output_path,
                         int is_shared,
                         const FakeccOptions *opts);
enum {
    FAKECC_OK = 0,
    FAKECC_ERR = 1
};
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
int die_at(const char *file, int line, int col, const char *fmt, ...);
void fakecc_clear_error(void);
int fakecc_had_error(void);
int fakecc_error_code(void);
const char *fakecc_error_message(void);
SourceLoc fakecc_error_loc(void);
enum TokenKind {
    TK_KW_PACKAGE,
    TK_KW_IMPORT,
    TK_KW_VOID,
    TK_KW_INT,
    TK_KW_FLOAT,
    TK_KW_DOUBLE,
    TK_KW_CHAR,
    TK_KW_SHORT,
    TK_KW_LONG,
    TK_KW_SIGNED,
    TK_KW_UNSIGNED,
    TK_KW_SIZEOF,
    TK_KW_RETURN,
    TK_KW_IF,
    TK_KW_ELSE,
    TK_KW_WHILE,
    TK_KW_FOR,
    TK_KW_GOTO,
    TK_KW_SWITCH,
    TK_KW_CASE,
    TK_KW_DEFAULT,
    TK_KW_BREAK,
    TK_KW_CONTINUE,
    TK_KW_CONST,
    TK_KW_UNION,
    TK_KW_DO,
    TK_KW_ENUM,
    TK_KW_STRUCT,
    TK_KW_TYPEDEF,
    TK_KW_STATIC,
    TK_KW_EXTERN,
    TK_KW_BOOL,
    TK_KW_VOLATILE,
    TK_KW_RESTRICT,
    TK_KW_INLINE,
    TK_KW_ALIGNOF,
    TK_KW_LONG_DOUBLE,
    TK_KW_COMPLEX,
    TK_KW_REAL,
    TK_KW_IMAG,
    TK_IDENT,
    TK_INT_LITERAL,
    TK_FLOAT_LITERAL,
    TK_CHAR_LITERAL,
    TK_STRING_LITERAL,
    TK_LPAREN,
    TK_RPAREN,
    TK_LBRACE,
    TK_RBRACE,
    TK_LBRACKET,
    TK_RBRACKET,
    TK_SEMICOLON,
    TK_COMMA,
    TK_PLUS,
    TK_MINUS,
    TK_STAR,
    TK_SLASH,
    TK_PERCENT,
    TK_AMP,
    TK_ANDAND,
    TK_OROR,
    TK_BITOR,
    TK_XOR,
    TK_TILDE,
    TK_NOT,
    TK_SHL,
    TK_SHR,
    TK_SHL_EQ,
    TK_SHR_EQ,
    TK_PLUS_EQ,
    TK_MINUS_EQ,
    TK_STAR_EQ,
    TK_SLASH_EQ,
    TK_PERCENT_EQ,
    TK_AMP_EQ,
    TK_BITOR_EQ,
    TK_XOR_EQ,
    TK_INC,
    TK_DEC,
    TK_QUESTION,
    TK_COLON,
    TK_DOT,
    TK_ELLIPSIS,
    TK_ARROW,
    TK_ASSIGN,
    TK_EQ,
    TK_NE,
    TK_LT,
    TK_LE,
    TK_GT,
    TK_GE,
    TK_EOF,
};typedef enum TokenKind TokenKind;
struct Token {
    TokenKind kind;
    char *text;
    SourceLoc loc;
};typedef struct Token Token;
struct TokenArray {
    Token *data;
    size_t len;
    size_t cap;
};typedef struct TokenArray TokenArray;
void token_array_init(TokenArray *a);
void token_array_free(TokenArray *a);
void token_array_push(TokenArray *a, Token t);
enum TypeKind {
    TY_VOID,
    TY_INT,
    TY_FLOAT,
    TY_PTR,
    TY_ARRAY,
    TY_STRUCT,
    TY_FUNC,
};typedef enum TypeKind TypeKind;
typedef struct Type Type;
struct Type {
    TypeKind kind;
    long long width;
    int is_unsigned;
    unsigned is_const : 1;
    unsigned is_volatile : 1;
    unsigned is_restrict : 1;
    unsigned is_bool : 1;
    Type *pointee;
    Type *elem_type;
    long long length;
    struct Expr *vla_dim;
    char *tag;
    Type *func_ret;
    Type *func_params;
    int func_nparams;
    int func_is_variadic;
    int func_is_unprototyped;
    int enum_id;
    int bitfield_width;
    int is_vector;
    unsigned is_decimal : 1;
};
static inline Type type_make_int(long long width, int is_unsigned) {
    Type t; t.kind = TY_INT; t.width = width; t.is_unsigned = is_unsigned;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0;
    t.func_is_unprototyped = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; t.is_decimal = 0; return t;
}
static inline Type type_make_bool(void) {
    Type t = type_make_int(1, 1);
    t.is_bool = 1;
    return t;
}
static inline Type type_default_int(void) { return type_make_int(4, 0); }
static inline Type type_make_float(long long width) {
    Type t; t.kind = TY_FLOAT; t.width = width; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0;
    t.func_is_unprototyped = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; t.is_decimal = 0; return t;
}
static inline Type type_make_decimal(long long width) {
    Type t = type_make_float(width);
    t.is_decimal = 1;
    return t;
}
static inline int type_is_decimal(Type t) {
    return t.kind == TY_FLOAT && t.is_decimal && !t.is_vector;
}
static inline int type_is_decimal128(Type t) {
    return type_is_decimal(t) && t.width == 16;
}
static inline Type type_make_void(void) {
    Type t; t.kind = TY_VOID; t.width = 0; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0;
    t.func_is_unprototyped = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; t.is_decimal = 0; return t;
}
Type type_clone(Type t);
void type_free(Type *t);
long long type_size(Type t);
long long type_align(Type t);
int type_is_complex_ldouble(Type t);
int type_is_empty_struct(Type t);
int type_needs_stack_align16(Type t);
int type_stack_align(Type t);
int host_has_avx512f(void);
enum SysVRegClass {
    SYSV_CLS_INTEGER = 1,
    SYSV_CLS_SSE = 2
};typedef enum SysVRegClass SysVRegClass;
int sysv_classify_agg(Type t, SysVRegClass cls[2]);
int sysv_agg_ret_x87(Type t);
int sysv_memory_pass_as_pointer(Type t);
Type type_make_ptr(Type pointee);
Type type_make_array(Type elem, long long length);
Type type_make_vector(Type elem, long long vec_size);
Type type_make_vla(Type elem, struct Expr *dim);
Type type_make_struct(const char *tag, long long size);
Type type_make_func(Type ret, Type * *params, int nparams);
Type type_make_func_var(Type ret, Type * *params, int nparams, int is_variadic);
Type type_decay(Type t);
int type_is_ptr_or_array(Type t);
Type type_pointee_or_elem(Type t);
int type_funcs_equal(Type a, Type b);
int type_is_vla(Type t);
int type_same_typedef(Type a, Type b);
struct Expr *expr_clone(const struct Expr *e);
enum ExprKind {
    EX_INT_LIT,
    EX_BINOP,
    EX_UNARY,
    EX_VAR,
    EX_ASSIGN,
    EX_CALL,
    EX_STR,
    EX_ADDR,
    EX_DEREF,
    EX_INDEX,
    EX_MEMBER,
    EX_CAST,
    EX_SIZEOF_TYPE,
    EX_SIZEOF_EXPR,
    EX_ALIGNOF_TYPE,
    EX_ALIGNOF_EXPR,
    EX_TERNARY,
    EX_INC_DEC,
    EX_COMPOUND_ASSIGN,
    EX_COMMA,
    EX_INIT_LIST,
    EX_FLOAT_LIT,
    EX_COMPOUND_LITERAL,
    EX_STMT_EXPR,
    EX_LABEL_ADDR,
};typedef enum ExprKind ExprKind;
enum BinOp {
    BOP_ADD,
    BOP_SUB,
    BOP_MUL,
    BOP_DIV,
    BOP_MOD,
    BOP_EQ,
    BOP_NE,
    BOP_LT,
    BOP_LE,
    BOP_GT,
    BOP_GE,
    BOP_AND,
    BOP_OR,
    BOP_BITAND,
    BOP_BITOR,
    BOP_BITXOR,
    BOP_SHL,
    BOP_SHR,
};typedef enum BinOp BinOp;
enum UnaryOp {
    UOP_NEG,
    UOP_POS,
    UOP_BITNOT,
    UOP_NOT,
};typedef enum UnaryOp UnaryOp;
typedef struct StmtArray StmtArray;
typedef struct Expr Expr;
int fold_const_int(const Expr *e, long long *out);
int fold_const_int128(const Expr *e, unsigned long long *lo, unsigned long long *hi);
struct ExprArray {
    Expr **data;
    size_t len;
    size_t cap;
};typedef struct ExprArray ExprArray;
union __anon_u_1 {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *operand; } alignof_e;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
        struct { StmtArray *stmts; } stmt_expr;
        struct { char *label; } label_addr;
    };struct Expr {
    ExprKind kind;
    SourceLoc loc;
    Type type;
    Type va_arg_type;
    union {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *operand; } alignof_e;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
        struct { StmtArray *stmts; } stmt_expr;
        struct { char *label; } label_addr;
    } u;
    unsigned long long int_hi;
};
Expr *expr_new_int(long long v, SourceLoc loc);
Expr *expr_new_int_typed(long long v, int width, int is_unsigned, SourceLoc loc);
Expr *expr_new_int_bits(unsigned long long lo, unsigned long long hi,
                       int width, int is_unsigned, SourceLoc loc);
Expr *expr_new_binop(BinOp op, Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_unary(UnaryOp op, Expr *operand, SourceLoc loc);
Expr *expr_new_var(const char *name, SourceLoc loc);
Expr *expr_new_var_qual(const char *pkg, const char *name, SourceLoc loc);
Expr *expr_new_assign(Expr *lvalue, Expr *rvalue, SourceLoc loc);
Expr *expr_new_call(Expr *callee, SourceLoc loc);
Expr *expr_new_str(const char *bytes, int len, SourceLoc loc);
Expr *expr_new_addr(Expr *operand, SourceLoc loc);
Expr *expr_new_deref(Expr *operand, SourceLoc loc);
Expr *expr_new_index(Expr *array, Expr *index, SourceLoc loc);
Expr *expr_new_member(Expr *obj, const char *name, SourceLoc loc);
Expr *expr_new_cast(Type target, Expr *operand, SourceLoc loc);
Expr *expr_new_sizeof_type(Type t, SourceLoc loc);
Expr *expr_new_sizeof_expr(Expr *operand, SourceLoc loc);
Expr *expr_new_alignof_type(Type t, SourceLoc loc);
Expr *expr_new_alignof_expr(Expr *operand, SourceLoc loc);
Expr *expr_new_ternary(Expr *cond, Expr *then, Expr *else_, SourceLoc loc);
Expr *expr_new_inc_dec(Expr *operand, int is_inc, int is_prefix, SourceLoc loc);
Expr *expr_new_compound_assign(Expr *lvalue, Expr *rvalue, BinOp op, SourceLoc loc);
Expr *expr_new_comma(Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_init_list(Expr **elements, int num_elements, SourceLoc loc);
Expr *expr_new_float_lit(const char *text, int width, SourceLoc loc);
Expr *expr_new_compound_literal(Type target_type, Expr *init, SourceLoc loc);
Expr *expr_new_stmt_expr(StmtArray *stmts, SourceLoc loc);
Expr *expr_new_label_addr(const char *label, SourceLoc loc);
void expr_call_push_arg(Expr *e, Expr *arg);
void expr_call_set_callee(Expr *e, Expr *callee);
void expr_free(Expr *e);
void expr_set_type(Expr *e, Type t);
enum StmtKind {
    ST_DECL,
    ST_EXPR,
    ST_RETURN,
    ST_IF,
    ST_WHILE,
    ST_FOR,
    ST_BREAK,
    ST_CONTINUE,
    ST_BLOCK,
    ST_DO_WHILE,
    ST_GOTO,
    ST_LABEL,
    ST_SWITCH,
};typedef enum StmtKind StmtKind;
typedef struct Stmt Stmt;
struct StmtArray {
    Stmt *data;
    size_t len;
    size_t cap;
};
struct SwitchCase {
    int is_default;
    long long value;
    long long high_value;
    int is_range;
    char *label_name;
    StmtArray stmts;
};typedef struct SwitchCase SwitchCase;
union __anon_u_2 {
        struct { char *name; Type type; Expr *init; int storage_class; char *alias_target; int align; int is_tls; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; Expr *target_expr; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; Stmt *body; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    };struct Stmt {
    StmtKind kind;
    SourceLoc loc;
    union {
        struct { char *name; Type type; Expr *init; int storage_class; char *alias_target; int align; int is_tls; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; Expr *target_expr; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; Stmt *body; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    } u;
};
void stmt_array_init(StmtArray *a);
void stmt_array_push(StmtArray *a, Stmt s);
void stmt_array_free(StmtArray *a);
void stmt_free(Stmt *s);
Stmt stmt_clone(const Stmt *s);
Stmt *stmt_alloc(void);
void stmt_free_ptr(Stmt *s);
void switch_push_case(Stmt *s, int is_default, long long value, const char *label_name);
void switch_push_case_range(Stmt *s, int is_default, long long value, long long high_value, int is_range, const char *label_name);
struct Param {
    char *name;
    Type type;
    SourceLoc loc;
};typedef struct Param Param;
struct ParamArray {
    Param *data;
    size_t len;
    size_t cap;
};typedef struct ParamArray ParamArray;
void param_array_init(ParamArray *a);
void param_array_push(ParamArray *a, const char *name, Type type, SourceLoc loc);
void param_array_free(ParamArray *a);
struct FunctionDecl {
    char *name;
    Type ret_type;
    ParamArray params;
    StmtArray body;
    SourceLoc loc;
    int is_variadic;
    int is_unprototyped;
    int is_extern;
    int is_static;
    char *alias_target;
    int align;
    int no_instrument;
    int is_constructor;
    int is_destructor;
    int ctor_prio;
    int dtor_prio;
};typedef struct FunctionDecl FunctionDecl;
struct PackageDecl {
    char *name;
    SourceLoc loc;
};typedef struct PackageDecl PackageDecl;
struct ImportDecl {
    char *name;
    SourceLoc loc;
};typedef struct ImportDecl ImportDecl;
struct ImportArray {
    ImportDecl *data;
    size_t len;
    size_t cap;
};typedef struct ImportArray ImportArray;
void import_array_init(ImportArray *a);
void import_array_push(ImportArray *a, const char *name, SourceLoc loc);
void import_array_free(ImportArray *a);
struct StructMember {
    char *name;
    Type type;
    long long offset;
    int bit_width;
    int bit_offset;
    int align;
};typedef struct StructMember StructMember;
struct StructDef {
    char *tag;
    int is_union;
    int is_big_endian;
    StructMember *members;
    int num_members;
    int cap_members;
    long long size;
    long long align;
    int is_packed;
    SourceLoc loc;
    Type *canonical_type;
    long long bf_unit_type;
    int bf_unit_used;
    long long bf_unit_offset;
};typedef struct StructDef StructDef;
struct StructRegistry {
    StructDef *data;
    size_t len;
    size_t cap;
};typedef struct StructRegistry StructRegistry;
void struct_registry_init(StructRegistry *r);
void struct_registry_free(StructRegistry *r);
StructDef *struct_registry_add(StructRegistry *r, const char *tag, SourceLoc loc);
StructDef *struct_registry_find(StructRegistry *r, const char *tag);
const StructDef *struct_registry_find_c(const StructRegistry *r, const char *tag);
void struct_def_push_member(StructDef *sd, const char *name, Type ty, int bit_width);
void struct_def_push_member_aligned(StructDef *sd, const char *name, Type ty, int bit_width, int align);
void struct_def_finish(StructDef *sd);
void struct_def_apply_sso(StructDef *sd, int is_big_endian);
void struct_def_fixup_self_types(StructDef *sd);
const StructMember *struct_lookup_member(const StructRegistry *reg,
                                         const StructDef *sd,
                                         const char *name,
                                         long long *offset_out);
struct FunctionArray {
    FunctionDecl *data;
    size_t len;
    size_t cap;
};typedef struct FunctionArray FunctionArray;
struct EnumConstant {
    char *name;
    int value;
};typedef struct EnumConstant EnumConstant;
struct EnumDef {
    char *tag;
    EnumConstant *constants;
    int num_constants;
    int cap_constants;
    SourceLoc loc;
    int has_underlying_type;
    Type underlying_type;
};typedef struct EnumDef EnumDef;
struct EnumRegistry {
    EnumDef *data;
    size_t len;
    size_t cap;
};typedef struct EnumRegistry EnumRegistry;
void enum_registry_init(EnumRegistry *r);
void enum_registry_free(EnumRegistry *r);
EnumDef *enum_registry_add(EnumRegistry *r, const char *tag, SourceLoc loc);
EnumDef *enum_registry_find(EnumRegistry *r, const char *tag);
int enum_def_push_constant(EnumDef *ed, const char *name, int has_value,
                            int value, SourceLoc loc);
const EnumConstant *enum_registry_find_constant(const EnumRegistry *r,
                                                const char *name);
Type enum_def_as_type(const EnumDef *ed, int enum_id);
struct TypedefEntry {
    char *name;
    Type type;
};typedef struct TypedefEntry TypedefEntry;
struct TypedefRegistry {
    TypedefEntry *data;
    size_t len;
    size_t cap;
};typedef struct TypedefRegistry TypedefRegistry;
void typedef_registry_init(TypedefRegistry *r);
void typedef_registry_free(TypedefRegistry *r);
TypedefEntry *typedef_registry_add(TypedefRegistry *r, const char *name, Type type);
const Type *typedef_registry_find(const TypedefRegistry *r, const char *name);
TypedefEntry *typedef_registry_get(TypedefRegistry *r, const char *name);
void typedef_registry_truncate(TypedefRegistry *r, size_t len);
struct TranslationUnit {
    PackageDecl package;
    ImportArray imports;
    StmtArray globals;
    FunctionArray functions;
    StructRegistry structs;
    EnumRegistry enums;
    TypedefRegistry typedefs;
};typedef struct TranslationUnit TranslationUnit;
void tu_init(TranslationUnit *tu);
void tu_free(TranslationUnit *tu);
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long uint64_t;
typedef char int8_t;
typedef short int16_t;
typedef int int32_t;
typedef long int64_t;
typedef int bool;
struct EmitSymbol {
    char *name;
    uint8_t binding;
    uint8_t type;
    uint16_t shndx;
    size_t value;
    size_t size;
};typedef struct EmitSymbol EmitSymbol;
struct EmitReloc {
    size_t offset;
    uint32_t type;
    uint32_t sym;
    int32_t addend;
    uint16_t shndx;
};typedef struct EmitReloc EmitReloc;
enum DebugVarKind {
    DBG_VAR_PARAM = 0,
    DBG_VAR_LOCAL = 1,
    DBG_VAR_GLOBAL = 2
};typedef enum DebugVarKind DebugVarKind;
enum DebugTypeTag {
    DBG_TY_VOID = 0,
    DBG_TY_INT = 1,
    DBG_TY_FLOAT = 2,
    DBG_TY_PTR = 3,
    DBG_TY_ARRAY = 4,
    DBG_TY_STRUCT = 5,
    DBG_TY_BOOL = 6
};typedef enum DebugTypeTag DebugTypeTag;
enum DebugLocKind {
    DBG_LOC_NONE = 0,
    DBG_LOC_FBREG = 1,
    DBG_LOC_REG = 2,
    DBG_LOC_ADDR = 3,
    DBG_LOC_ENTRY_VALUE = 4
};typedef enum DebugLocKind DebugLocKind;
struct DebugLocRange {
    size_t pc_start;
    size_t pc_end;
    DebugLocKind loc_kind;
    int rbp_offset;
    int dwarf_reg;
};typedef struct DebugLocRange DebugLocRange;
struct DebugMember {
    char *name;
    int offset;
    int bit_width;
    int bit_offset;
    DebugTypeTag type_tag;
    int width;
    int is_unsigned;
};typedef struct DebugMember DebugMember;
struct DebugVar {
    char *name;
    char *file;
    int line;
    DebugVarKind kind;
    DebugTypeTag type_tag;
    int width;
    int is_unsigned;
    int array_len;
    char *type_name;
    int struct_size;
    DebugMember *members;
    size_t num_members;
    DebugLocKind loc_kind;
    int rbp_offset;
    int dwarf_reg;
    char *sym_name;
    DebugLocRange *ranges;
    size_t num_ranges;
    size_t cap_ranges;
    int alloca_ssa;
    int param_idx;
    int entry_dwarf_reg;
};typedef struct DebugVar DebugVar;
struct DebugCallSiteParam {
    int dwarf_reg;
    unsigned char *value_expr;
    size_t value_expr_len;
};typedef struct DebugCallSiteParam DebugCallSiteParam;
struct DebugCallSite {
    size_t call_pc;
    size_t return_pc;
    char *callee_name;
    DebugCallSiteParam *params;
    size_t num_params;
};typedef struct DebugCallSite DebugCallSite;
struct DebugLineEntry {
    char *file;
    int line;
    int col;
    size_t pc_off;
};typedef struct DebugLineEntry DebugLineEntry;
struct DebugFunc {
    char *name;
    char *file;
    int line;
    size_t start_pc;
    size_t end_pc;
    size_t prologue_end_pc;
    size_t after_push_rbp_pc;
    size_t after_mov_rbp_pc;
    DebugVar *vars;
    size_t num_vars;
    size_t cap_vars;
    DebugCallSite *call_sites;
    size_t num_call_sites;
    size_t cap_call_sites;
};typedef struct DebugFunc DebugFunc;
struct EmitModule {
    Buffer text;
    Buffer rodata;
    Buffer data;
    size_t bss_size;
    Buffer tdata;
    size_t tbss_size;
    size_t text_align;
    size_t rodata_align;
    size_t data_align;
    size_t bss_align;
    size_t tdata_align;
    size_t tbss_align;
    Buffer init_array;
    size_t init_array_align;
    int *init_prio;
    Buffer fini_array;
    size_t fini_array_align;
    int *fini_prio;
    EmitSymbol *syms;
    size_t num_syms;
    size_t cap_syms;
    EmitReloc *relocs;
    size_t num_relocs;
    size_t cap_relocs;
    EmitReloc *data_relocs;
    size_t num_data_relocs;
    size_t cap_data_relocs;
    char *dbg_tu_name;
    DebugLineEntry *dbg_lines;
    size_t num_dbg_lines;
    size_t cap_dbg_lines;
    DebugFunc *dbg_funcs;
    size_t num_dbg_funcs;
    size_t cap_dbg_funcs;
    DebugVar *dbg_globals;
    size_t num_dbg_globals;
    size_t cap_dbg_globals;
};typedef struct EmitModule EmitModule;
void emit_module_init(EmitModule *m);
void emit_module_free(EmitModule *m);
int emit_module_add_symbol(EmitModule *m, const char *name,
                            uint8_t binding, uint8_t type,
                            uint16_t shndx, size_t value, size_t size);
int emit_module_find_symbol(EmitModule *m, const char *name);
int emit_module_add_undefined(EmitModule *m, const char *name);
int emit_module_add_undefined_type(EmitModule *m, const char *name,
                                   uint8_t st_type);
void emit_module_add_reloc(EmitModule *m, size_t offset, uint32_t type,
                           int sym, int32_t addend);
void emit_module_add_data_reloc(EmitModule *m, size_t offset, uint32_t type,
                                int sym, int32_t addend);
void emit_obj(const EmitModule *m, const char *path);
int emit_obj_read(const char *path, EmitModule *m);
void emit_link(EmitModule **mods, size_t n, const char *path,
               const char **needed, size_t num_needed, int nodefaultlibs,
               const char **lib_paths, size_t num_lib_paths,
               int want_debug, int is_shared);
void emit_elf(const EmitModule *m, const char *path);
typedef int IRValue;
enum IROpcode {
    IR_CONST,
    IR_ADD,
    IR_SUB,
    IR_MUL,
    IR_DIV,
    IR_MOD,
    IR_NEG,
    IR_BAND,
    IR_BOR,
    IR_BXOR,
    IR_BNOT,
    IR_SHL,
    IR_SHR,
    IR_ROL,
    IR_EQ,
    IR_NE,
    IR_FADD,
    IR_FSUB,
    IR_FMUL,
    IR_FDIV,
    IR_FCMP,
    IR_VADD,
    IR_VSUB,
    IR_VMUL,
    IR_VDIV,
    IR_VBAND,
    IR_VBOR,
    IR_VBXOR,
    IR_SITOFP,
    IR_FPTOSI,
    IR_FPEXT,
    IR_FPTRUNC,
    IR_LT,
    IR_LE,
    IR_GT,
    IR_GE,
    IR_ALLOCA,
    IR_LOAD,
    IR_STORE,
    IR_ADDR,
    IR_LOAD_PTR,
    IR_STORE_PTR,
    IR_COPY,
    IR_LABEL,
    IR_BR,
    IR_CBR,
    IR_PARAM,
    IR_CALL,
    IR_RETURN,
    IR_SEXT,
    IR_ZEXT,
    IR_TRUNC,
    IR_GADDR,
    IR_GADDR_TLS,
    IR_FADDR,
    IR_LADDR,
    IR_JMP_PTR,
    IR_FRAME_ADDR,
    IR_RETURN_ADDR,
    IR_DYN_ALLOCA,
    IR_STACK_SAVE,
    IR_STACK_RESTORE,
    IR_LONGJMP,
    IR_DBG_VALUE,
};typedef enum IROpcode IROpcode;
struct IRInst {
    IROpcode op;
    IRValue dst;
    IRValue a;
    IRValue b;
    int64_t imm;
    SourceLoc loc;
    char *call_name;
    IRValue *call_args;
    int call_nargs;
    IRValue call_callee;
    int width;
    int is_unsigned;
    int64_t float_imm;
    int is_float;
    int force_stack;
    int align16;
    int x87_pair;
    unsigned char *call_arg_on_stack;
    int *call_arg_nbytes;
    int alloca_bytes;
    int is_volatile;
};typedef struct IRInst IRInst;
struct IRInstArray {
    IRInst *data;
    size_t len;
    size_t cap;
};typedef struct IRInstArray IRInstArray;
enum IRDebugVarKind {
    IR_DBG_PARAM = 0,
    IR_DBG_LOCAL = 1
};typedef enum IRDebugVarKind IRDebugVarKind;
struct IRDebugMember {
    char *name;
    int offset;
    int bit_width;
    int bit_offset;
    int type_kind;
    int width;
    int is_unsigned;
    int is_bool;
};typedef struct IRDebugMember IRDebugMember;
struct IRDebugVar {
    char *name;
    SourceLoc loc;
    IRDebugVarKind kind;
    int type_kind;
    int width;
    int is_unsigned;
    int is_bool;
    int array_len;
    char *struct_tag;
    int struct_size;
    IRDebugMember *members;
    int num_members;
    int alloca_ssa;
    int param_idx;
};typedef struct IRDebugVar IRDebugVar;
struct ExtractedMarker {
    int var;
    int value;
    int pos;
};typedef struct ExtractedMarker ExtractedMarker;
struct IRFunction {
    char *name;
    IRInstArray insts;
    int next_value_id;
    int next_label_id;
    SourceLoc loc;
    void *ra;
    void *ra_xmm;
    int *value_width;
    int *value_is_unsigned;
    int value_meta_cap;
    int *value_is_float;
    int ret_width;
    int ret_is_unsigned;
    int ret_is_float;
    int ret_is_struct;
    int ret_reg_n;
    int ret_reg_cls[2];
    int ret_is_bool;
    int ret_is_complex_ld;
    int ret_x87_bytes;
    int is_variadic;
    int is_static;
    int is_constructor;
    int is_destructor;
    int ctor_prio;
    int dtor_prio;
    int has_dyn_alloca;
    int needs_apply_args;
    int needs_apply;
    IRValue sret_value;
    IRDebugVar *dbg_vars;
    size_t num_dbg_vars;
    size_t cap_dbg_vars;
};typedef struct IRFunction IRFunction;
struct IRFunctionArray {
    IRFunction *data;
    size_t len;
    size_t cap;
};typedef struct IRFunctionArray IRFunctionArray;
struct GlobalFixup {
    int offset;
    char *sym;
    int addend;
};typedef struct GlobalFixup GlobalFixup;
struct IRGlobal {
    char *name;
    int size;
    char *init_bytes;
    int is_readonly;
    int is_static;
    int is_tls;
    int align;
    SourceLoc loc;
    GlobalFixup *fixups;
    int num_fixups;
    int cap_fixups;
};typedef struct IRGlobal IRGlobal;
struct IRGlobalArray {
    IRGlobal *data;
    size_t len;
    size_t cap;
};typedef struct IRGlobalArray IRGlobalArray;
struct IRAlias {
    char *name;
    char *target;
    int is_static;
    SourceLoc loc;
};typedef struct IRAlias IRAlias;
struct IRAliasArray {
    IRAlias *data;
    size_t len;
    size_t cap;
};typedef struct IRAliasArray IRAliasArray;
struct IRModule {
    IRFunctionArray functions;
    IRGlobalArray globals;
    IRAliasArray aliases;
};typedef struct IRModule IRModule;
void ir_module_init(IRModule *m);
void ir_module_free(IRModule *m);
void ir_module_push_alias(IRModule *m, const char *name, const char *target,
                          int is_static, SourceLoc loc);
int ir_generate(const TranslationUnit *tu, IRModule *ir, int pin_locals);
void ir_disable_builtin(const char *name);
int ir_builtin_disabled(const char *name);
const StructRegistry *get_ir_structs(void);
void codegen(const IRModule *ir, EmitModule *out, int want_debug);
int lex(const char *source, const char *filename, TokenArray *out);
void opt(IRModule *ir, int opt_level, int want_debug);
struct PkgContext;
int parse(const TokenArray *tokens, TranslationUnit *tu);
int parse_in_pkg(const TokenArray *tokens, TranslationUnit *tu,
                 struct PkgContext *ctx);
typedef struct Package Package;
typedef struct PkgContext PkgContext;
struct PkgFuncExport {
    char *name;
    Type ret_type;
    Type *param_types;
    int param_cap;
    int arity;
    int is_variadic;
    int is_extern;
    SourceLoc loc;
    TranslationUnit *tu;
};typedef struct PkgFuncExport PkgFuncExport;
struct PkgGlobalExport {
    char *name;
    Type type;
    int is_extern;
    SourceLoc loc;
    TranslationUnit *tu;
};typedef struct PkgGlobalExport PkgGlobalExport;
struct Package {
    char *name;
    char *dir;
    TranslationUnit *files;
    size_t nfiles;
    int owns_files;
    PkgFuncExport *funcs;
    size_t nfuncs;
    PkgGlobalExport *globals;
    size_t nglobals;
    TypedefRegistry typedefs;
    StructRegistry structs;
    EnumRegistry enums;
};
struct PkgContext {
    char **search_paths;
    int npaths;
    Package **pkgs;
    size_t npkgs;
    size_t cap_pkgs;
    char **loading;
    size_t nloading;
    size_t cap_loading;
};
void pkg_ctx_init(PkgContext *ctx);
void pkg_ctx_free(PkgContext *ctx);
void pkg_ctx_add_path(PkgContext *ctx, const char *dir);
Package *pkg_load(PkgContext *ctx, const char *name, SourceLoc loc);
Package *pkg_register_tus(PkgContext *ctx, const char *name,
                          TranslationUnit **tus, size_t ntus);
Package *pkg_find(const PkgContext *ctx, const char *name);
const PkgFuncExport *pkg_find_func(const Package *pkg, const char *name);
const PkgGlobalExport *pkg_find_global(const Package *pkg, const char *name);
const Type *pkg_find_typedef(const Package *pkg, const char *name);
const StructDef *pkg_find_struct(const Package *pkg, const char *name);
const EnumDef *pkg_find_enum(const Package *pkg, const char *name);
const EnumConstant *pkg_find_enum_const(const Package *pkg, const char *name);
void pkg_clone_struct_into(StructRegistry *dst, const StructDef *src);
void pkg_import_typedef(TranslationUnit *tu, const char *name, const Type *src,
                        const Package *pkg);
const char *pkg_suggest_export(const PkgContext *ctx, const char *name);
struct PkgContext;
int sema_check(const TranslationUnit *tu, int require_main);
int sema_check_in_pkg(const TranslationUnit *tu, int require_main,
                      struct PkgContext *ctx);
int sema_has_errors(void);
int sema_error_count(void);
int sema_warning_count(void);
typedef struct FILE FILE;
typedef long fpos_t;
static int file_readable(const char *path) {
    FILE *f = runtime.fopen(path, "rb");
    if (!f) return 0;
    runtime.fclose(f);
    return 1;
}
static char *path_join(const char *a, const char *b) {
    size_t na = runtime.strlen(a), nb = runtime.strlen(b);
    int slash = (na > 0 && a[na - 1] != '/');
    char *p = runtime.malloc(na + (size_t)slash + nb + 1);
    if (!p) return ((void*)0);
    runtime.memcpy(p, a, na);
    if (slash) p[na++] = '/';
    runtime.memcpy(p + na, b, nb + 1);
    return p;
}
static char *dir_of(const char *path) {
    const char *slash = ((void*)0);
    for (const char *p = path; *p; p++)
        if (*p == '/') slash = p;
    if (!slash) return xstrdup(".");
    if (slash == path) return xstrdup("/");
    size_t n = (size_t)(slash - path);
    char *d = runtime.malloc(n + 1);
    if (!d) return ((void*)0);
    runtime.memcpy(d, path, n);
    d[n] = '\0';
    return d;
}
static char *read_file_text(const char *path) {
    FILE *f = runtime.fopen(path, "rb");
    if (!f) return ((void*)0);
    runtime.fseek(f, 0, 2);
    long size = runtime.ftell(f);
    runtime.fseek(f, 0, 0);
    char *buf = runtime.malloc((size_t)size + 1);
    if (!buf) { runtime.fclose(f); return ((void*)0); }
    size_t nread = runtime.fread(buf, 1, (size_t)size, f);
    buf[nread] = '\0';
    runtime.fclose(f);
    return buf;
}
static char *find_runtime_dir(const char *hint) {
    if (hint && hint[0]) {
        char *probe = path_join(hint, "string.c");
        int ok = file_readable(probe);
        runtime.free(probe);
        if (ok) return xstrdup(hint);
    }
    const char *env = runtime.getenv("FAKECC_RT");
    if (env && env[0]) {
        char *probe = path_join(env, "string.c");
        int ok = file_readable(probe);
        runtime.free(probe);
        if (ok) return xstrdup(env);
    }
    if (file_readable("runtime/string.c")) return xstrdup("runtime");
    const char *sys_paths[] = {
        "/usr/local/share/fakecc/runtime",
        "/usr/share/fakecc/runtime",
        ((void*)0)
    };
    for (int i = 0; sys_paths[i]; i++) {
        char *probe = path_join(sys_paths[i], "string.c");
        int ok = file_readable(probe);
        runtime.free(probe);
        if (ok) return xstrdup(sys_paths[i]);
    }
    return ((void*)0);
}
static int ends_with(const char *s, const char *suffix) {
    size_t slen = runtime.strlen(s), suflen = runtime.strlen(suffix);
    if (slen < suflen) return 0;
    return runtime.strcmp(s + slen - suflen, suffix) == 0;
}
static int lower_one_tu(TranslationUnit *tu, const char *filename,
                        EmitModule *out, int opt_level, int want_debug,
                        PkgContext *pkg) {
    int rc;
    if (pkg)
        rc = sema_check_in_pkg(tu, 0, pkg);
    else
        rc = sema_check(tu, 0);
    if (rc != FAKECC_OK || sema_has_errors())
        return FAKECC_ERR;
    IRModule ir;
    ir_module_init(&ir);
    if (ir_generate(tu, &ir, opt_level == 0) != FAKECC_OK) {
        ir_module_free(&ir);
        return FAKECC_ERR;
    }
    opt(&ir, opt_level, want_debug);
    emit_module_init(out);
    if (want_debug) out->dbg_tu_name = xstrdup(filename);
    codegen(&ir, out, want_debug);
    ir_module_free(&ir);
    return FAKECC_OK;
}
static int compile_parse_string(const char *source, const char *filename,
                                TranslationUnit *tu, PkgContext *pkg) {
    TokenArray tokens;
    token_array_init(&tokens);
    if (lex(source, filename, &tokens) != FAKECC_OK) {
        token_array_free(&tokens);
        return FAKECC_ERR;
    }
    tu_init(tu);
    int rc = pkg ? parse_in_pkg(&tokens, tu, pkg) : parse(&tokens, tu);
    token_array_free(&tokens);
    return rc;
}
void fakecc_options_init(FakeccOptions *opts) {
    if (!opts) return;
    runtime.memset(opts, 0, sizeof(*opts));
    opts->opt_level = 1;
}
int fakecc_compile_string_to_obj(const char *source,
                                 const char *output_obj_path,
                                 const FakeccOptions *opts) {
    if (!source || !output_obj_path) return -1;
    int opt_level = opts ? opts->opt_level : 1;
    int want_debug = opts ? opts->want_debug : 0;
    TranslationUnit tu;
    if (compile_parse_string(source, "input.c", &tu, ((void*)0)) != FAKECC_OK)
        return FAKECC_ERR;
    EmitModule em;
    if (lower_one_tu(&tu, "input.c", &em, opt_level, want_debug, ((void*)0)) != FAKECC_OK) {
        tu_free(&tu);
        return FAKECC_ERR;
    }
    tu_free(&tu);
    emit_obj(&em, output_obj_path);
    emit_module_free(&em);
    return FAKECC_OK;
}
int fakecc_compile_string_to_so(const char *source,
                                const char *output_so_path,
                                const FakeccOptions *opts) {
    if (!source || !output_so_path) return -1;
    int opt_level = opts ? opts->opt_level : 1;
    int want_debug = opts ? opts->want_debug : 0;
    TranslationUnit tu;
    if (compile_parse_string(source, "input.c", &tu, ((void*)0)) != FAKECC_OK)
        return FAKECC_ERR;
    EmitModule em;
    if (lower_one_tu(&tu, "input.c", &em, opt_level, want_debug, ((void*)0)) != FAKECC_OK) {
        tu_free(&tu);
        return FAKECC_ERR;
    }
    tu_free(&tu);
    EmitModule *mods[1];
    mods[0] = &em;
    const char **needed = opts ? opts->needed : ((void*)0);
    size_t num_needed = opts ? opts->num_needed : 0;
    const char **lib_paths = opts ? opts->lib_paths : ((void*)0);
    size_t num_lib_paths = opts ? opts->num_lib_paths : 0;
    emit_link(mods, 1, output_so_path,
              needed, num_needed, 0,
              lib_paths, num_lib_paths,
              want_debug, 1);
    emit_module_free(&em);
    return FAKECC_OK;
}
int fakecc_compile_string_to_executable(const char *source,
                                        const char *output_path,
                                        const FakeccOptions *opts) {
    if (!source || !output_path) return -1;
    int opt_level = opts ? opts->opt_level : 1;
    int want_debug = opts ? opts->want_debug : 0;
    int nostdlib = opts ? opts->nostdlib : 0;
    const char **needed = opts ? opts->needed : ((void*)0);
    size_t num_needed = opts ? opts->num_needed : 0;
    const char **lib_paths = opts ? opts->lib_paths : ((void*)0);
    size_t num_lib_paths = opts ? opts->num_lib_paths : 0;
    if (nostdlib) {
        TranslationUnit tu;
        if (compile_parse_string(source, "input.c", &tu, ((void*)0)) != FAKECC_OK)
            return FAKECC_ERR;
        EmitModule em;
        if (lower_one_tu(&tu, "input.c", &em, opt_level, want_debug, ((void*)0)) != FAKECC_OK) {
            tu_free(&tu);
            return FAKECC_ERR;
        }
        tu_free(&tu);
        EmitModule *mods[1];
        mods[0] = &em;
        emit_link(mods, 1, output_path,
                  needed, num_needed, 0,
                  lib_paths, num_lib_paths,
                  want_debug, 0);
        emit_module_free(&em);
        return FAKECC_OK;
    }
    char *rt_dir = find_runtime_dir(opts ? opts->rt_dir : ((void*)0));
    if (!rt_dir) return -1;
    PkgContext pkg;
    pkg_ctx_init(&pkg);
    char *rt_parent = dir_of(rt_dir);
    if (rt_parent) {
        pkg_ctx_add_path(&pkg, rt_parent);
        runtime.free(rt_parent);
    }
    runtime.free(rt_dir);
    SourceLoc zloc = {0};
    pkg_load(&pkg, "runtime", zloc);
    TranslationUnit tu;
    if (compile_parse_string(source, "input.c", &tu, &pkg) != FAKECC_OK) {
        pkg_ctx_free(&pkg);
        return FAKECC_ERR;
    }
    int nlinked = 0;
    for (size_t p = 0; p < pkg.npkgs; p++) {
        if (!pkg.pkgs[p]->owns_files) continue;
        nlinked += (int)pkg.pkgs[p]->nfiles;
    }
    int total_mods = 1 + nlinked;
    EmitModule *all_mods = runtime.malloc((size_t)total_mods * sizeof(EmitModule));
    EmitModule **mod_ptrs = runtime.malloc((size_t)total_mods * sizeof(EmitModule *));
    if (!all_mods || !mod_ptrs) {
        tu_free(&tu);
        pkg_ctx_free(&pkg);
        runtime.free(all_mods);
        runtime.free(mod_ptrs);
        return -1;
    }
    if (lower_one_tu(&tu, "input.c", &all_mods[0], opt_level, want_debug, &pkg) != FAKECC_OK) return FAKECC_ERR;
    tu_free(&tu);
    mod_ptrs[0] = &all_mods[0];
    int mi = 1;
    for (size_t p = 0; p < pkg.npkgs; p++) {
        Package *pp = pkg.pkgs[p];
        if (!pp->owns_files) continue;
        for (size_t f = 0; f < pp->nfiles; f++) {
            char *fake = path_join(pp->dir, "_.c");
            if (lower_one_tu(&pp->files[f], fake, &all_mods[mi], opt_level, want_debug, &pkg) != FAKECC_OK) return FAKECC_ERR;
            runtime.free(fake);
            mod_ptrs[mi] = &all_mods[mi];
            mi++;
        }
    }
    emit_link(mod_ptrs, (size_t)total_mods, output_path,
              needed, num_needed, 0,
              lib_paths, num_lib_paths,
              want_debug, 0);
    for (int i = 0; i < total_mods; i++) emit_module_free(&all_mods[i]);
    runtime.free(all_mods);
    runtime.free(mod_ptrs);
    pkg_ctx_free(&pkg);
    return 0;
}
int fakecc_compile_file_to_obj(const char *source_path,
                               const char *output_obj_path,
                               const FakeccOptions *opts) {
    char *text = read_file_text(source_path);
    if (!text) return -1;
    int rc = fakecc_compile_string_to_obj(text, output_obj_path, opts);
    runtime.free(text);
    return rc;
}
int fakecc_compile_file_to_so(const char *source_path,
                              const char *output_so_path,
                              const FakeccOptions *opts) {
    return fakecc_compile_files(&source_path, 1, output_so_path, 1, opts);
}
int fakecc_compile_file_to_executable(const char *source_path,
                                      const char *output_path,
                                      const FakeccOptions *opts) {
    return fakecc_compile_files(&source_path, 1, output_path, 0, opts);
}
int fakecc_compile_files(const char **input_paths,
                         size_t num_inputs,
                         const char *output_path,
                         int is_shared,
                         const FakeccOptions *opts) {
    if (!input_paths || num_inputs == 0 || !output_path) return -1;
    int opt_level = opts ? opts->opt_level : 1;
    int want_debug = opts ? opts->want_debug : 0;
    int nostdlib = opts ? opts->nostdlib : (is_shared ? 1 : 0);
    const char **needed = opts ? opts->needed : ((void*)0);
    size_t num_needed = opts ? opts->num_needed : 0;
    const char **lib_paths = opts ? opts->lib_paths : ((void*)0);
    size_t num_lib_paths = opts ? opts->num_lib_paths : 0;
    PkgContext pkg;
    pkg_ctx_init(&pkg);
    for (size_t i = 0; i < num_inputs; i++) {
        if (!ends_with(input_paths[i], ".o")) {
            char *d = dir_of(input_paths[i]);
            if (d) {
                pkg_ctx_add_path(&pkg, d);
                runtime.free(d);
            }
        }
    }
    if (!nostdlib) {
        char *rt_dir = find_runtime_dir(opts ? opts->rt_dir : ((void*)0));
        if (!rt_dir) {
            pkg_ctx_free(&pkg);
            return -1;
        }
        char *rt_parent = dir_of(rt_dir);
        if (rt_parent) {
            pkg_ctx_add_path(&pkg, rt_parent);
            runtime.free(rt_parent);
        }
        runtime.free(rt_dir);
        SourceLoc zloc = {0};
        pkg_load(&pkg, "runtime", zloc);
    }
    TranslationUnit *user_tus = runtime.malloc(num_inputs * sizeof(TranslationUnit));
    if (!user_tus) { pkg_ctx_free(&pkg); return -1; }
    for (size_t i = 0; i < num_inputs; i++) {
        tu_init(&user_tus[i]);
        if (!ends_with(input_paths[i], ".o")) {
            char *src = read_file_text(input_paths[i]);
            if (!src) {
                for (size_t j = 0; j <= i; j++) tu_free(&user_tus[j]);
                runtime.free(user_tus);
                pkg_ctx_free(&pkg);
                return -1;
            }
            TokenArray arr;
            token_array_init(&arr);
            if (lex(src, input_paths[i], &arr) != FAKECC_OK) {
                runtime.free(src);
                token_array_free(&arr);
                for (size_t j = 0; j <= i; j++) tu_free(&user_tus[j]);
                runtime.free(user_tus);
                pkg_ctx_free(&pkg);
                return FAKECC_ERR;
            }
            runtime.free(src);
            if (parse_in_pkg(&arr, &user_tus[i], &pkg) != FAKECC_OK) {
                token_array_free(&arr);
                for (size_t j = 0; j <= i; j++) tu_free(&user_tus[j]);
                runtime.free(user_tus);
                pkg_ctx_free(&pkg);
                return FAKECC_ERR;
            }
            token_array_free(&arr);
            if (user_tus[i].package.name) {
                TranslationUnit *one = &user_tus[i];
                pkg_register_tus(&pkg, user_tus[i].package.name, &one, 1);
            }
        }
    }
    int nlinked = 0;
    for (size_t p = 0; p < pkg.npkgs; p++) {
        if (!pkg.pkgs[p]->owns_files) continue;
        nlinked += (int)pkg.pkgs[p]->nfiles;
    }
    size_t total_mods = num_inputs + (size_t)nlinked;
    EmitModule *mods = runtime.malloc(total_mods * sizeof(EmitModule));
    EmitModule **mod_ptrs = runtime.malloc(total_mods * sizeof(EmitModule *));
    if (!mods || !mod_ptrs) {
        for (size_t i = 0; i < num_inputs; i++) tu_free(&user_tus[i]);
        runtime.free(user_tus);
        runtime.free(mods);
        runtime.free(mod_ptrs);
        pkg_ctx_free(&pkg);
        return -1;
    }
    for (size_t i = 0; i < num_inputs; i++) {
        if (ends_with(input_paths[i], ".o")) {
            if (emit_obj_read(input_paths[i], &mods[i]) != 0) {
                for (size_t j = 0; j < i; j++) emit_module_free(&mods[j]);
                for (size_t j = 0; j < num_inputs; j++) tu_free(&user_tus[j]);
                runtime.free(user_tus);
                runtime.free(mods);
                runtime.free(mod_ptrs);
                pkg_ctx_free(&pkg);
                return -1;
            }
        } else {
            if (lower_one_tu(&user_tus[i], input_paths[i], &mods[i], opt_level, want_debug, &pkg) != FAKECC_OK) return FAKECC_ERR;
            tu_free(&user_tus[i]);
        }
        mod_ptrs[i] = &mods[i];
    }
    runtime.free(user_tus);
    size_t mi = num_inputs;
    for (size_t p = 0; p < pkg.npkgs; p++) {
        Package *pp = pkg.pkgs[p];
        if (!pp->owns_files) continue;
        for (size_t f = 0; f < pp->nfiles; f++) {
            char *fake = path_join(pp->dir, "_.c");
            if (lower_one_tu(&pp->files[f], fake, &mods[mi], opt_level, want_debug, &pkg) != FAKECC_OK) return FAKECC_ERR;
            runtime.free(fake);
            mod_ptrs[mi] = &mods[mi];
            mi++;
        }
    }
    emit_link(mod_ptrs, total_mods, output_path,
              needed, num_needed, 0,
              lib_paths, num_lib_paths,
              want_debug, is_shared);
    for (size_t i = 0; i < total_mods; i++) emit_module_free(&mods[i]);
    runtime.free(mods);
    runtime.free(mod_ptrs);
    pkg_ctx_free(&pkg);
    return 0;
}
