package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
void die_at(const char *file, int line, int col, const char *fmt, ...);
enum TokenKind {
    TK_KW_PACKAGE,
    TK_KW_IMPORT,
    TK_KW_VOID,
    TK_KW_INT,
    TK_KW_FLOAT,
    TK_KW_DOUBLE,
    TK_KW_CHAR,
    TK_KW_SHORT,
    TK_KW_LONG,
    TK_KW_SIGNED,
    TK_KW_UNSIGNED,
    TK_KW_SIZEOF,
    TK_KW_RETURN,
    TK_KW_IF,
    TK_KW_ELSE,
    TK_KW_WHILE,
    TK_KW_FOR,
    TK_KW_GOTO,
    TK_KW_SWITCH,
    TK_KW_CASE,
    TK_KW_DEFAULT,
    TK_KW_BREAK,
    TK_KW_CONTINUE,
    TK_KW_CONST,
    TK_KW_UNION,
    TK_KW_DO,
    TK_KW_ENUM,
    TK_KW_STRUCT,
    TK_KW_TYPEDEF,
    TK_KW_STATIC,
    TK_KW_EXTERN,
    TK_KW_BOOL,
    TK_KW_VOLATILE,
    TK_KW_RESTRICT,
    TK_KW_INLINE,
    TK_KW_ALIGNOF,
    TK_KW_LONG_DOUBLE,
    TK_KW_COMPLEX,
    TK_KW_REAL,
    TK_KW_IMAG,
    TK_IDENT,
    TK_INT_LITERAL,
    TK_FLOAT_LITERAL,
    TK_CHAR_LITERAL,
    TK_STRING_LITERAL,
    TK_LPAREN,
    TK_RPAREN,
    TK_LBRACE,
    TK_RBRACE,
    TK_LBRACKET,
    TK_RBRACKET,
    TK_SEMICOLON,
    TK_COMMA,
    TK_PLUS,
    TK_MINUS,
    TK_STAR,
    TK_SLASH,
    TK_PERCENT,
    TK_AMP,
    TK_ANDAND,
    TK_OROR,
    TK_BITOR,
    TK_XOR,
    TK_TILDE,
    TK_NOT,
    TK_SHL,
    TK_SHR,
    TK_SHL_EQ,
    TK_SHR_EQ,
    TK_PLUS_EQ,
    TK_MINUS_EQ,
    TK_STAR_EQ,
    TK_SLASH_EQ,
    TK_PERCENT_EQ,
    TK_AMP_EQ,
    TK_BITOR_EQ,
    TK_XOR_EQ,
    TK_INC,
    TK_DEC,
    TK_QUESTION,
    TK_COLON,
    TK_DOT,
    TK_ELLIPSIS,
    TK_ARROW,
    TK_ASSIGN,
    TK_EQ,
    TK_NE,
    TK_LT,
    TK_LE,
    TK_GT,
    TK_GE,
    TK_EOF,
};typedef enum TokenKind TokenKind;
struct Token {
    TokenKind kind;
    char *text;
    SourceLoc loc;
};typedef struct Token Token;
struct TokenArray {
    Token *data;
    size_t len;
    size_t cap;
};typedef struct TokenArray TokenArray;
void token_array_init(TokenArray *a);
void token_array_free(TokenArray *a);
void token_array_push(TokenArray *a, Token t);
void lex(const char *source, const char *filename, TokenArray *out);
typedef struct FILE FILE;
typedef long fpos_t;
static const char *predefined_macro_literal(const char *text, int *out_is_float) {
    *out_is_float = 0;
    if (runtime.strcmp(text, "__INT_MAX__") == 0) return "2147483647";
    if (runtime.strcmp(text, "__INT_MIN__") == 0) return "-2147483648";
    if (runtime.strcmp(text, "__UINT_MAX__") == 0) return "4294967295u";
    if (runtime.strcmp(text, "__LONG_MAX__") == 0) return "9223372036854775807l";
    if (runtime.strcmp(text, "__LONG_MIN__") == 0) return "-9223372036854775807l";
    if (runtime.strcmp(text, "__ULONG_MAX__") == 0) return "18446744073709551615ul";
    if (runtime.strcmp(text, "__CHAR_BIT__") == 0) return "8";
    if (runtime.strcmp(text, "__SIZEOF_INT__") == 0) return "4";
    if (runtime.strcmp(text, "__SIZEOF_LONG__") == 0) return "8";
    if (runtime.strcmp(text, "__SIZEOF_LONG_LONG__") == 0) return "8";
    if (runtime.strcmp(text, "__SIZEOF_POINTER__") == 0) return "8";
    if (runtime.strcmp(text, "__SIZEOF_FLOAT__") == 0) return "4";
    if (runtime.strcmp(text, "__SIZEOF_DOUBLE__") == 0) return "8";
    if (runtime.strcmp(text, "__SIZEOF_LONG_DOUBLE__") == 0) return "16";
    if (runtime.strcmp(text, "__FLT_MAX__") == 0) { *out_is_float = 1; return "3.40282347e+38f"; }
    if (runtime.strcmp(text, "__DBL_MAX__") == 0) { *out_is_float = 1; return "1.7976931348623157e+308"; }
    if (runtime.strcmp(text, "__FLT_MIN__") == 0) { *out_is_float = 1; return "1.17549435e-38f"; }
    if (runtime.strcmp(text, "__DBL_MIN__") == 0) { *out_is_float = 1; return "2.2250738585072014e-308"; }
    if (runtime.strcmp(text, "__FLT_EPSILON__") == 0) { *out_is_float = 1; return "1.19209290e-7f"; }
    if (runtime.strcmp(text, "__DBL_EPSILON__") == 0) { *out_is_float = 1; return "2.2204460492503131e-16"; }
    return ((void*)0);
}
void token_array_init(TokenArray *a) {
    a->data = ((void*)0);
    a->len = 0;
    a->cap = 0;
}
void token_array_free(TokenArray *a) {
    for (size_t i = 0; i < a->len; i++) {
        runtime.free(a->data[i].text);
    }
    runtime.free(a->data);
    a->data = ((void*)0);
    a->len = 0;
    a->cap = 0;
}
void token_array_push(TokenArray *a, Token t) {
    if (a->len >= a->cap) {
        size_t new_cap = a->cap ? a->cap * 2 : 16;
        a->data = runtime.realloc(a->data, new_cap * sizeof(Token));
        if (!a->data) {
            runtime.fprintf(runtime.stderr, "fakecc: out of memory\n");
            runtime.exit(1);
        }
        a->cap = new_cap;
    }
    a->data[a->len++] = t;
}
static TokenKind keyword_kind(const char *s, size_t len) {
    switch (len) {
    case 2:
        if (runtime.memcmp(s, "if", 2) == 0) return TK_KW_IF;
        if (runtime.memcmp(s, "do", 2) == 0) return TK_KW_DO;
        break;
    case 3:
        if (runtime.memcmp(s, "int", 3) == 0) return TK_KW_INT;
        if (runtime.memcmp(s, "for", 3) == 0) return TK_KW_FOR;
        break;
    case 4:
        if (runtime.memcmp(s, "else", 4) == 0) return TK_KW_ELSE;
        if (runtime.memcmp(s, "char", 4) == 0) return TK_KW_CHAR;
        if (runtime.memcmp(s, "long", 4) == 0) return TK_KW_LONG;
        if (runtime.memcmp(s, "enum", 4) == 0) return TK_KW_ENUM;
        if (runtime.memcmp(s, "goto", 4) == 0) return TK_KW_GOTO;
        if (runtime.memcmp(s, "case", 4) == 0) return TK_KW_CASE;
        if (runtime.memcmp(s, "void", 4) == 0) return TK_KW_VOID;
        break;
    case 5:
        if (runtime.memcmp(s, "while", 5) == 0) return TK_KW_WHILE;
        if (runtime.memcmp(s, "short", 5) == 0) return TK_KW_SHORT;
        if (runtime.memcmp(s, "break", 5) == 0) return TK_KW_BREAK;
        if (runtime.memcmp(s, "union", 5) == 0) return TK_KW_UNION;
        if (runtime.memcmp(s, "const", 5) == 0) return TK_KW_CONST;
        if (runtime.memcmp(s, "float", 5) == 0) return TK_KW_FLOAT;
        if (runtime.memcmp(s, "_Bool", 5) == 0) return TK_KW_BOOL;
        break;
    case 6:
        if (runtime.memcmp(s, "double", 6) == 0) return TK_KW_DOUBLE;
        if (runtime.memcmp(s, "import", 6) == 0) return TK_KW_IMPORT;
        if (runtime.memcmp(s, "return", 6) == 0) return TK_KW_RETURN;
        if (runtime.memcmp(s, "signed", 6) == 0) return TK_KW_SIGNED;
        if (runtime.memcmp(s, "sizeof", 6) == 0) return TK_KW_SIZEOF;
        if (runtime.memcmp(s, "static", 6) == 0) return TK_KW_STATIC;
        if (runtime.memcmp(s, "struct", 6) == 0) return TK_KW_STRUCT;
        if (runtime.memcmp(s, "switch", 6) == 0) return TK_KW_SWITCH;
        if (runtime.memcmp(s, "extern", 6) == 0) return TK_KW_EXTERN;
        if (runtime.memcmp(s, "inline", 6) == 0) return TK_KW_INLINE;
        if (runtime.memcmp(s, "__real", 6) == 0) return TK_KW_REAL;
        if (runtime.memcmp(s, "__imag", 6) == 0) return TK_KW_IMAG;
        break;
    case 7:
        if (runtime.memcmp(s, "package", 7) == 0) return TK_KW_PACKAGE;
        if (runtime.memcmp(s, "default", 7) == 0) return TK_KW_DEFAULT;
        if (runtime.memcmp(s, "typedef", 7) == 0) return TK_KW_TYPEDEF;
        if (runtime.memcmp(s, "alignof", 7) == 0) return TK_KW_ALIGNOF;
        if (runtime.memcmp(s, "__const", 7) == 0) return TK_KW_CONST;
        break;
    case 8:
        if (runtime.memcmp(s, "unsigned", 8) == 0) return TK_KW_UNSIGNED;
        if (runtime.memcmp(s, "continue", 8) == 0) return TK_KW_CONTINUE;
        if (runtime.memcmp(s, "volatile", 8) == 0) return TK_KW_VOLATILE;
        if (runtime.memcmp(s, "restrict", 8) == 0) return TK_KW_RESTRICT;
        if (runtime.memcmp(s, "_Alignof", 8) == 0) return TK_KW_ALIGNOF;
        if (runtime.memcmp(s, "_Complex", 8) == 0) return TK_KW_COMPLEX;
        if (runtime.memcmp(s, "__real__", 8) == 0) return TK_KW_REAL;
        if (runtime.memcmp(s, "__imag__", 8) == 0) return TK_KW_IMAG;
        if (runtime.memcmp(s, "__signed", 8) == 0) return TK_KW_SIGNED;
        if (runtime.memcmp(s, "__inline", 8) == 0) return TK_KW_INLINE;
        break;
    case 9:
        if (runtime.memcmp(s, "__alignof", 9) == 0) return TK_KW_ALIGNOF;
        if (runtime.memcmp(s, "__const__", 9) == 0) return TK_KW_CONST;
        if (runtime.memcmp(s, "__complex", 9) == 0) return TK_KW_COMPLEX;
        break;
    case 10:
        if (runtime.memcmp(s, "__signed__", 10) == 0) return TK_KW_SIGNED;
        if (runtime.memcmp(s, "__inline__", 10) == 0) return TK_KW_INLINE;
        if (runtime.memcmp(s, "__volatile", 10) == 0) return TK_KW_VOLATILE;
        if (runtime.memcmp(s, "__restrict", 10) == 0) return TK_KW_RESTRICT;
        break;
    case 11:
        if (runtime.memcmp(s, "__alignof__", 11) == 0) return TK_KW_ALIGNOF;
        if (runtime.memcmp(s, "__complex__", 11) == 0) return TK_KW_COMPLEX;
        if (runtime.memcmp(s, "__extension", 11) == 0) return TK_KW_INLINE;
        break;
    case 12:
        if (runtime.memcmp(s, "__volatile__", 12) == 0) return TK_KW_VOLATILE;
        if (runtime.memcmp(s, "__restrict__", 12) == 0) return TK_KW_RESTRICT;
        break;
    case 13:
        if (runtime.memcmp(s, "__extension__", 13) == 0) return TK_KW_INLINE;
        break;
    default:
        break;
    }
    return TK_IDENT;
}
void lex(const char *source, const char *filename, TokenArray *out) {
    size_t pos = 0;
    int line = 1;
    int col = 1;
    int line_start = 1;
    char c;
lex_loop_head:
    while (source[pos] != '\0') {
        c = source[pos];
        if (c == '\n') {
            pos++;
            line++;
            col = 1;
            line_start = 1;
            goto lex_loop_head;
        }
        if (c == ' ' || c == '\t' || c == '\r') {
            pos++;
            col++;
            goto lex_loop_head;
        }
        if (c == '/' && source[pos + 1] == '/') {
            pos += 2;
            col += 2;
            while (source[pos] != '\0' && source[pos] != '\n') {
                pos++;
                col++;
            }
            goto lex_loop_head;
        }
        if (c == '/' && source[pos + 1] == '*') {
            pos += 2;
            col += 2;
            while (source[pos] != '\0') {
                if (source[pos] == '*' && source[pos + 1] == '/') {
                    pos += 2;
                    col += 2;
                    break;
                }
                if (source[pos] == '\n') {
                    pos++;
                    line++;
                    col = 1;
                } else {
                    pos++;
                    col++;
                }
            }
            goto lex_loop_head;
        }
        if (c == '#' && line_start) {
            int start_line = line;
            int start_col = col;
            die_at(filename, start_line, start_col,
                   "preprocessor directives are not supported in FakeCC");
        }
        line_start = 0;
        if (c == '\'') {
            int start_line = line;
            int start_col = col;
            size_t start = pos;
            pos++;
            col++;
            if (source[pos] == '\0' || source[pos] == '\n') {
                die_at(filename, start_line, start_col,
                       "unterminated character literal");
            }
            while (source[pos] != '\'' && source[pos] != '\0' && source[pos] != '\n') {
                if (source[pos] == '\\') {
                    pos++; col++;
                    if (source[pos] == '\0' || source[pos] == '\n') break;
                    if (source[pos] == 'x' || source[pos] == 'X') {
                        pos++; col++;
                        if (!runtime.isxdigit((unsigned char)source[pos]))
                            die_at(filename, start_line, start_col,
                                   "hex escape \\x with no digits");
                        while (runtime.isxdigit((unsigned char)source[pos])) { pos++; col++; }
                    } else if (source[pos] >= '0' && source[pos] <= '7') {
                        int n = 0;
                        while (n < 3 && source[pos] >= '0' && source[pos] <= '7') {
                            pos++; col++; n++;
                        }
                    } else {
                        pos++; col++;
                    }
                } else {
                    pos++; col++;
                }
            }
            if (source[pos] != '\'') {
                die_at(filename, start_line, start_col,
                       "missing closing quote in character literal");
            }
            pos++; col++;
            size_t len = pos - start;
            Token t;
            t.kind = TK_CHAR_LITERAL;
            t.text = runtime.malloc(len + 1);
            runtime.memcpy(t.text, source + start, len);
            t.text[len] = '\0';
            t.loc.file = filename;
            t.loc.line = start_line;
            t.loc.col = start_col;
            token_array_push(out, t);
            goto lex_loop_head;
        }
        if (c == '"') {
            int start_line = line;
            int start_col = col;
            size_t start = pos;
            pos++;
            col++;
            while (source[pos] != '\0' && source[pos] != '"') {
                if (source[pos] == '\\' && source[pos + 1] != '\0') {
                    pos += 2;
                    col += 2;
                } else if (source[pos] == '\n') {
                    pos++;
                    line++;
                    col = 1;
                } else {
                    pos++;
                    col++;
                }
            }
            if (source[pos] == '"') {
                pos++;
                col++;
            }
            size_t len = pos - start;
            Token t;
            t.kind = TK_STRING_LITERAL;
            t.text = runtime.malloc(len + 1);
            runtime.memcpy(t.text, source + start, len);
            t.text[len] = '\0';
            t.loc.file = filename;
            t.loc.line = start_line;
            t.loc.col = start_col;
            token_array_push(out, t);
            goto lex_loop_head;
        }
        if (runtime.isdigit((unsigned char)c)) {
            int start_line = line;
            int start_col = col;
            size_t start = pos;
            int is_float = 0;
            int is_hex = 0;
            if (c == '0' && (source[pos + 1] == 'x' || source[pos + 1] == 'X')) {
                is_hex = 1;
                pos += 2;
                col += 2;
                if (!runtime.isxdigit((unsigned char)source[pos]))
                    die_at(filename, start_line, start_col,
                           "hex literal has no digits");
                while (runtime.isxdigit((unsigned char)source[pos])) { pos++; col++; }
                if (source[pos] == '.') {
                    is_float = 1;
                    pos++; col++;
                    while (runtime.isxdigit((unsigned char)source[pos])) { pos++; col++; }
                }
                if (source[pos] == 'p' || source[pos] == 'P') {
                    is_float = 1;
                    pos++; col++;
                    if (source[pos] == '+' || source[pos] == '-') { pos++; col++; }
                    if (!runtime.isdigit((unsigned char)source[pos])) {
                        die_at(filename, line, col, "hex float exponent has no digits");
                    }
                    while (runtime.isdigit((unsigned char)source[pos])) { pos++; col++; }
                }
            } else {
                while (runtime.isdigit((unsigned char)source[pos])) { pos++; col++; }
            }
            if (!is_hex && source[pos] == '.') {
                is_float = 1;
                pos++; col++;
                while (runtime.isdigit((unsigned char)source[pos])) { pos++; col++; }
            }
            if (!is_hex && (source[pos] == 'e' || source[pos] == 'E')) {
                is_float = 1;
                pos++; col++;
                if (source[pos] == '+' || source[pos] == '-') { pos++; col++; }
                if (!runtime.isdigit((unsigned char)source[pos])) {
                    die_at(filename, line, col,
                           "exponent has no digits");
                }
                while (runtime.isdigit((unsigned char)source[pos])) { pos++; col++; }
            }
            for (;;) {
                char sc = source[pos];
                if (sc == 'u' || sc == 'U' || sc == 'l' || sc == 'L' ||
                    sc == 'f' || sc == 'F' || sc == 'i' || sc == 'I' ||
                    sc == 'j' || sc == 'J') {
                    if (sc == 'f' || sc == 'F' || sc == 'i' || sc == 'I' || sc == 'j' || sc == 'J')
                        is_float = 1;
                    pos++; col++;
                } else break;
            }
            size_t len = pos - start;
            Token t;
            t.kind = is_float ? TK_FLOAT_LITERAL : TK_INT_LITERAL;
            t.text = runtime.malloc(len + 1);
            runtime.memcpy(t.text, source + start, len);
            t.text[len] = '\0';
            t.loc.file = filename;
            t.loc.line = start_line;
            t.loc.col = start_col;
            token_array_push(out, t);
            goto lex_loop_head;
        }
        if (c == '.' && runtime.isdigit((unsigned char)source[pos + 1])) {
            int start_line = line;
            int start_col = col;
            size_t start = pos;
            pos++; col++;
            while (runtime.isdigit((unsigned char)source[pos])) { pos++; col++; }
            if (source[pos] == 'e' || source[pos] == 'E') {
                pos++; col++;
                if (source[pos] == '+' || source[pos] == '-') { pos++; col++; }
                if (!runtime.isdigit((unsigned char)source[pos])) {
                    die_at(filename, line, col, "exponent has no digits");
                }
                while (runtime.isdigit((unsigned char)source[pos])) { pos++; col++; }
            }
            for (;;) {
                char sc = source[pos];
                if (sc == 'f' || sc == 'F' || sc == 'l' || sc == 'L' ||
                    sc == 'i' || sc == 'I' || sc == 'j' || sc == 'J') {
                    pos++; col++;
                } else break;
            }
            size_t len = pos - start;
            Token t;
            t.kind = TK_FLOAT_LITERAL;
            t.text = runtime.malloc(len + 1);
            runtime.memcpy(t.text, source + start, len);
            t.text[len] = '\0';
            t.loc.file = filename;
            t.loc.line = start_line;
            t.loc.col = start_col;
            token_array_push(out, t);
            goto lex_loop_head;
        }
        if (runtime.isalpha((unsigned char)c) || c == '_') {
            int start_line = line;
            int start_col = col;
            size_t start = pos;
            while (runtime.isalnum((unsigned char)source[pos]) || source[pos] == '_') {
                pos++;
                col++;
            }
            size_t len = pos - start;
            char ident_buf[64];
            runtime.memcpy(ident_buf, source + start, len);
            ident_buf[len] = '\0';
            int is_float = 0;
            const char *lit = predefined_macro_literal(ident_buf, &is_float);
            if (lit) {
                Token t;
                t.kind = is_float ? TK_FLOAT_LITERAL : TK_INT_LITERAL;
                t.text = xstrdup(lit);
                t.loc.file = filename;
                t.loc.line = start_line;
                t.loc.col = start_col;
                token_array_push(out, t);
                goto lex_loop_head;
            }
            Token t;
            t.kind = keyword_kind(ident_buf, len);
            t.text = runtime.malloc(len + 1);
            runtime.memcpy(t.text, ident_buf, len);
            t.text[len] = '\0';
            t.loc.file = filename;
            t.loc.line = start_line;
            t.loc.col = start_col;
            token_array_push(out, t);
            goto lex_loop_head;
        }
        if (c == '=' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_EQ;
            t.text = xstrdup("==");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '+' && source[pos + 1] == '+') {
            Token t;
            t.kind = TK_INC;
            t.text = xstrdup("++");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '-' && source[pos + 1] == '-') {
            Token t;
            t.kind = TK_DEC;
            t.text = xstrdup("--");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '-' && source[pos + 1] == '>') {
            Token t;
            t.kind = TK_ARROW;
            t.text = xstrdup("->");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '!' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_NE;
            t.text = xstrdup("!=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '&' && source[pos + 1] == '&') {
            Token t;
            t.kind = TK_ANDAND;
            t.text = xstrdup("&&");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '|' && source[pos + 1] == '|') {
            Token t;
            t.kind = TK_OROR;
            t.text = xstrdup("||");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '+' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_PLUS_EQ;
            t.text = xstrdup("+=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '-' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_MINUS_EQ;
            t.text = xstrdup("-=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '*' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_STAR_EQ;
            t.text = xstrdup("*=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '/' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_SLASH_EQ;
            t.text = xstrdup("/=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '%' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_PERCENT_EQ;
            t.text = xstrdup("%=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '&' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_AMP_EQ;
            t.text = xstrdup("&=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '|' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_BITOR_EQ;
            t.text = xstrdup("|=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '^' && source[pos + 1] == '=') {
            Token t;
            t.kind = TK_XOR_EQ;
            t.text = xstrdup("^=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '<' && source[pos + 1] == '<' && source[pos + 2] == '=') {
            Token t;
            t.kind = TK_SHL_EQ;
            t.text = xstrdup("<<=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 3; col += 3;
            goto lex_loop_head;
        }
        if (c == '>' && source[pos + 1] == '>' && source[pos + 2] == '=') {
            Token t;
            t.kind = TK_SHR_EQ;
            t.text = xstrdup(">>=");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 3; col += 3;
            goto lex_loop_head;
        }
        if (c == '<' && source[pos + 1] == '<') {
            Token t;
            t.kind = TK_SHL;
            t.text = xstrdup("<<");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '>' && source[pos + 1] == '>') {
            Token t;
            t.kind = TK_SHR;
            t.text = xstrdup(">>");
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            token_array_push(out, t);
            pos += 2; col += 2;
            goto lex_loop_head;
        }
        if (c == '<') {
            Token t;
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            if (source[pos + 1] == '=') {
                t.kind = TK_LE;
                t.text = xstrdup("<=");
                pos += 2; col += 2;
            } else {
                t.kind = TK_LT;
                t.text = xstrdup("<");
                pos++; col++;
            }
            token_array_push(out, t);
            goto lex_loop_head;
        }
        if (c == '>') {
            Token t;
            t.loc.file = filename; t.loc.line = line; t.loc.col = col;
            if (source[pos + 1] == '=') {
                t.kind = TK_GE;
                t.text = xstrdup(">=");
                pos += 2; col += 2;
            } else {
                t.kind = TK_GT;
                t.text = xstrdup(">");
                pos++; col++;
            }
            token_array_push(out, t);
            goto lex_loop_head;
        }
        switch (c) {
        case '(':
        case ')':
        case '{':
        case '}':
        case '[':
        case ']':
        case ';':
        case ',':
        case '.':
        case '+':
        case '-':
        case '*':
        case '/':
        case '%':
        case '&':
        case '|':
        case '^':
        case '~':
        case '=':
        case '!':
        case '?':
        case ':': {
            Token t;
            switch (c) {
            case '(': t.kind = TK_LPAREN; break;
            case ')': t.kind = TK_RPAREN; break;
            case '{': t.kind = TK_LBRACE; break;
            case '}': t.kind = TK_RBRACE; break;
            case '[': t.kind = TK_LBRACKET; break;
            case ']': t.kind = TK_RBRACKET; break;
            case ';': t.kind = TK_SEMICOLON; break;
            case ',': t.kind = TK_COMMA; break;
            case '.':
                if (source[pos + 1] == '.' && source[pos + 2] == '.') {
                    t.kind = TK_ELLIPSIS;
                    t.text = xstrdup("...");
                    t.loc.file = filename;
                    t.loc.line = line;
                    t.loc.col = col;
                    token_array_push(out, t);
                    pos += 3; col += 3;
                    goto lex_loop_head;
                }
                t.kind = TK_DOT;
                break;
            case '+': t.kind = TK_PLUS; break;
            case '-': t.kind = TK_MINUS; break;
            case '*': t.kind = TK_STAR; break;
            case '/': t.kind = TK_SLASH; break;
            case '%': t.kind = TK_PERCENT; break;
            case '&': t.kind = TK_AMP; break;
            case '|': t.kind = TK_BITOR; break;
            case '^': t.kind = TK_XOR; break;
            case '~': t.kind = TK_TILDE; break;
            case '!': t.kind = TK_NOT; break;
            case '=': t.kind = TK_ASSIGN; break;
            case '?': t.kind = TK_QUESTION; break;
            case ':': t.kind = TK_COLON; break;
            default: t.kind = TK_EOF; break;
            }
            t.text = runtime.malloc(2);
            t.text[0] = c;
            t.text[1] = '\0';
            t.loc.file = filename;
            t.loc.line = line;
            t.loc.col = col;
            token_array_push(out, t);
            pos++;
            col++;
            goto lex_loop_head;
        }
        default:
            break;
        }
        die_at(filename, line, col, "unexpected character '%c'", c);
    }
    Token eof;
    eof.kind = TK_EOF;
    eof.text = runtime.malloc(1);
    eof.text[0] = '\0';
    eof.loc.file = filename;
    eof.loc.line = line;
    eof.loc.col = col;
    token_array_push(out, eof);
}
