package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
void die_at(const char *file, int line, int col, const char *fmt, ...);
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long uint64_t;
typedef char int8_t;
typedef short int16_t;
typedef int int32_t;
typedef long int64_t;
typedef int bool;
struct EmitSymbol {
    char *name;
    uint8_t binding;
    uint8_t type;
    uint16_t shndx;
    size_t value;
    size_t size;
};typedef struct EmitSymbol EmitSymbol;
struct EmitReloc {
    size_t offset;
    uint32_t type;
    uint32_t sym;
    int32_t addend;
};typedef struct EmitReloc EmitReloc;
enum DebugVarKind {
    DBG_VAR_PARAM = 0,
    DBG_VAR_LOCAL = 1,
    DBG_VAR_GLOBAL = 2
};typedef enum DebugVarKind DebugVarKind;
enum DebugTypeTag {
    DBG_TY_VOID = 0,
    DBG_TY_INT = 1,
    DBG_TY_FLOAT = 2,
    DBG_TY_PTR = 3,
    DBG_TY_ARRAY = 4,
    DBG_TY_STRUCT = 5,
    DBG_TY_BOOL = 6
};typedef enum DebugTypeTag DebugTypeTag;
enum DebugLocKind {
    DBG_LOC_NONE = 0,
    DBG_LOC_FBREG = 1,
    DBG_LOC_REG = 2,
    DBG_LOC_ADDR = 3,
    DBG_LOC_ENTRY_VALUE = 4
};typedef enum DebugLocKind DebugLocKind;
struct DebugLocRange {
    size_t pc_start;
    size_t pc_end;
    DebugLocKind loc_kind;
    int rbp_offset;
    int dwarf_reg;
};typedef struct DebugLocRange DebugLocRange;
struct DebugMember {
    char *name;
    int offset;
    int bit_width;
    int bit_offset;
    DebugTypeTag type_tag;
    int width;
    int is_unsigned;
};typedef struct DebugMember DebugMember;
struct DebugVar {
    char *name;
    char *file;
    int line;
    DebugVarKind kind;
    DebugTypeTag type_tag;
    int width;
    int is_unsigned;
    int array_len;
    char *type_name;
    int struct_size;
    DebugMember *members;
    size_t num_members;
    DebugLocKind loc_kind;
    int rbp_offset;
    int dwarf_reg;
    char *sym_name;
    DebugLocRange *ranges;
    size_t num_ranges;
    size_t cap_ranges;
    int alloca_ssa;
    int param_idx;
    int entry_dwarf_reg;
};typedef struct DebugVar DebugVar;
struct DebugCallSiteParam {
    int dwarf_reg;
    unsigned char *value_expr;
    size_t value_expr_len;
};typedef struct DebugCallSiteParam DebugCallSiteParam;
struct DebugCallSite {
    size_t call_pc;
    size_t return_pc;
    char *callee_name;
    DebugCallSiteParam *params;
    size_t num_params;
};typedef struct DebugCallSite DebugCallSite;
struct DebugLineEntry {
    char *file;
    int line;
    int col;
    size_t pc_off;
};typedef struct DebugLineEntry DebugLineEntry;
struct DebugFunc {
    char *name;
    char *file;
    int line;
    size_t start_pc;
    size_t end_pc;
    size_t prologue_end_pc;
    size_t after_push_rbp_pc;
    size_t after_mov_rbp_pc;
    DebugVar *vars;
    size_t num_vars;
    size_t cap_vars;
    DebugCallSite *call_sites;
    size_t num_call_sites;
    size_t cap_call_sites;
};typedef struct DebugFunc DebugFunc;
struct EmitModule {
    Buffer text;
    Buffer rodata;
    Buffer data;
    size_t bss_size;
    EmitSymbol *syms;
    size_t num_syms;
    size_t cap_syms;
    EmitReloc *relocs;
    size_t num_relocs;
    size_t cap_relocs;
    EmitReloc *data_relocs;
    size_t num_data_relocs;
    size_t cap_data_relocs;
    char *dbg_tu_name;
    DebugLineEntry *dbg_lines;
    size_t num_dbg_lines;
    size_t cap_dbg_lines;
    DebugFunc *dbg_funcs;
    size_t num_dbg_funcs;
    size_t cap_dbg_funcs;
    DebugVar *dbg_globals;
    size_t num_dbg_globals;
    size_t cap_dbg_globals;
};typedef struct EmitModule EmitModule;
void emit_module_init(EmitModule *m);
void emit_module_free(EmitModule *m);
int emit_module_add_symbol(EmitModule *m, const char *name,
                            uint8_t binding, uint8_t type,
                            uint16_t shndx, size_t value, size_t size);
int emit_module_find_symbol(EmitModule *m, const char *name);
int emit_module_add_undefined(EmitModule *m, const char *name);
void emit_module_add_reloc(EmitModule *m, size_t offset, uint32_t type,
                           int sym, int32_t addend);
void emit_module_add_data_reloc(EmitModule *m, size_t offset, uint32_t type,
                                int sym, int32_t addend);
void emit_obj(const EmitModule *m, const char *path);
int emit_obj_read(const char *path, EmitModule *m);
void emit_link(EmitModule **mods, size_t n, const char *path,
               const char **needed, size_t num_needed, int nodefaultlibs,
               const char **lib_paths, size_t num_lib_paths,
               int want_debug);
void emit_elf(const EmitModule *m, const char *path);
void debug_emit_dwarf(const EmitModule *m, uint64_t text_base_vaddr,
                      Buffer *debug_abbrev, Buffer *debug_info,
                      Buffer *debug_str, Buffer *debug_line,
                      Buffer *debug_frame, Buffer *debug_loc);
void debug_serialize(const EmitModule *m, Buffer *out);
int debug_deserialize(EmitModule *m, const unsigned char *data, size_t len);
void emit_module_add_dbg_line(EmitModule *m, const char *file, int line,
                              int col, size_t pc_off);
int emit_module_add_dbg_func(EmitModule *m, const char *name,
                              const char *file, int line, size_t start_pc);
void emit_module_dbg_func_end(EmitModule *m, int func_idx, size_t end_pc,
                              size_t prologue_end_pc);
void emit_module_dbg_func_frame(EmitModule *m, int func_idx,
                                size_t after_push_rbp_pc,
                                size_t after_mov_rbp_pc);
void emit_module_add_dbg_var(EmitModule *m, int func_idx, const DebugVar *v);
void emit_module_add_dbg_global(EmitModule *m, const DebugVar *v);
void emit_module_add_dbg_call_site(EmitModule *m, int func_idx,
                                   const DebugCallSite *cs);
void debug_var_release(DebugVar *v);
void debug_call_site_release(DebugCallSite *cs);
typedef struct FILE FILE;
extern FILE *stderr;
extern FILE *stdin;
extern FILE *stdout;
extern FILE *fopen(const char *p, const char *m);
typedef long fpos_t;
extern void *malloc(size_t n);
extern void *realloc(void *p, size_t n);
extern void *calloc(size_t n, size_t m);
extern void *memcpy(void *dst, const void *src, size_t n);
extern void *memset(void *dst, int c, size_t n);
static const char INTERP_PATH[] = "/lib64/ld-linux-x86-64.so.2";
struct SymInfo { int defined; int shndx; size_t value; uint8_t binding; };
typedef struct SymInfo SymInfo;
static void emit_byte(Buffer *b, uint8_t v) { buffer_append(b, (const char *)&v, 1); }
static void emit_int32(Buffer *b, int32_t v) { buffer_append(b, (const char *)&v, 4); }
static void *xcalloc(size_t nmemb, size_t size) {
    void *p = calloc(nmemb, size);
    if (!p) { runtime.fprintf(stderr, "fakecc: OOM\n"); runtime.exit(1); }
    return p;
}
static void buf_u8(Buffer *b, uint8_t v) { buffer_append(b, (const char *)&v, 1); }
static void buf_pad(Buffer *b, size_t n) { while (n--) buf_u8(b, 0); }
static void buf_bytes(Buffer *b, const char *d, size_t n) { buffer_append(b, d, n); }
static void buf_u16(Buffer *b, uint16_t v) { buffer_append(b, (const char *)&v, 2); }
static void buf_u32(Buffer *b, uint32_t v) { buffer_append(b, (const char *)&v, 4); }
static void buf_u64(Buffer *b, uint64_t v) { buffer_append(b, (const char *)&v, 8); }
static void write_ehdr(Buffer *b, uint64_t entry, uint64_t phoff,
                       uint16_t phnum) {
    buffer_append(b, "\x7f" "ELF", 4);
    char ident[12];
    memset(ident, 0, 12);
    ident[0] = 2;
    ident[1] = 1;
    ident[2] = 1;
    ident[3] = 0;
    buffer_append(b, ident, 12);
    buf_u16(b, 2);
    buf_u16(b, 62);
    buf_u32(b, 1);
    buf_u64(b, entry);
    buf_u64(b, phoff);
    buf_u64(b, 0);
    buf_u32(b, 0);
    buf_u16(b, 64);
    buf_u16(b, 56);
    buf_u16(b, phnum);
    buf_u16(b, 64);
    buf_u16(b, 0);
    buf_u16(b, 0);
}
static void write_phdr(Buffer *b, uint32_t type, uint32_t flags,
                       uint64_t offset, uint64_t vaddr,
                       uint64_t filesz, uint64_t memsz,
                       uint64_t align) {
    buf_u32(b, type);
    buf_u32(b, flags);
    buf_u64(b, offset);
    buf_u64(b, vaddr);
    buf_u64(b, vaddr);
    buf_u64(b, filesz);
    buf_u64(b, memsz);
    buf_u64(b, align);
}
static void write_shdr_exec(Buffer *b, uint32_t name, uint32_t type,
                            uint64_t flags, uint64_t addr, uint64_t offset,
                            uint64_t size, uint32_t link, uint32_t info,
                            uint64_t addralign, uint64_t entsize) {
    buf_u32(b, name);
    buf_u32(b, type);
    buf_u64(b, flags);
    buf_u64(b, addr);
    buf_u64(b, offset);
    buf_u64(b, size);
    buf_u32(b, link);
    buf_u32(b, info);
    buf_u64(b, addralign);
    buf_u64(b, entsize);
}
static uint32_t append_string(Buffer *b, const char *s) {
    uint32_t off = (uint32_t)b->len;
    buf_bytes(b, s, runtime.strlen(s) + 1);
    return off;
}
static void write_sym(Buffer *b, uint32_t name, uint8_t binding, uint8_t type,
                      uint16_t shndx, uint64_t value, uint64_t size) {
    buf_u32(b, name);
    buf_u8(b, (uint8_t)((binding << 4) | (type & 0xf)));
    buf_u8(b, 0);
    buf_u16(b, shndx);
    buf_u64(b, value);
    buf_u64(b, size);
}
struct SectionLayout {
    uint64_t code_vaddr;
    uint64_t data_vaddr;
    uint64_t bss_vaddr;
    size_t text_offset;
    size_t data_file_offset;
    size_t text_len;
    size_t rodata_len;
    size_t data_len;
    size_t bss_file_offset;
    size_t bss_size;
    int have_dynamic;
    size_t dynstr_off;
    size_t dynsym_off;
    size_t hash_off;
    size_t rela_plt_off;
    size_t rela_dyn_off;
    size_t dynamic_off;
    size_t dynstr_size;
    size_t dynsym_size;
    size_t hash_size;
    size_t rela_plt_size;
    size_t rela_dyn_size;
    size_t dynamic_size;
    uint64_t dynstr_vaddr;
    uint64_t dynsym_vaddr;
    uint64_t hash_vaddr;
    uint64_t rela_plt_vaddr;
    uint64_t rela_dyn_vaddr;
    uint64_t dynamic_vaddr;
};typedef struct SectionLayout SectionLayout;
static void finalize_sections(
    Buffer *elf, EmitModule **mods, size_t n,
    const size_t *mod_text_off, const size_t *mod_sym_base,
    const size_t *sym_addr, const SectionLayout *lay,
    uint64_t entry, int want_debug) {
    uint64_t code_vaddr = lay->code_vaddr;
    uint64_t data_vaddr = lay->data_vaddr;
    uint64_t bss_vaddr = lay->bss_vaddr;
    size_t text_offset = lay->text_offset;
    size_t data_file_offset = lay->data_file_offset;
    size_t text_len = lay->text_len;
    size_t rodata_len = lay->rodata_len;
    size_t data_len = lay->data_len;
    size_t bss_file_offset = lay->bss_file_offset;
    size_t bss_size = lay->bss_size;
Buffer symtab;
Buffer strtab;
Buffer shstrtab;
Buffer debug_abbrev;
Buffer debug_info;
Buffer debug_str;
Buffer debug_line;
Buffer debug_frame;
    Buffer debug_loc;
    buffer_init(&symtab); buffer_init(&strtab); buffer_init(&shstrtab);
    buffer_init(&debug_abbrev); buffer_init(&debug_info);
    buffer_init(&debug_str); buffer_init(&debug_line);
    buffer_init(&debug_frame); buffer_init(&debug_loc);
    buf_u8(&strtab, 0);
    buf_pad(&symtab, 24);
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t j = 0; j < m->num_syms; j++) {
            const EmitSymbol *s = &m->syms[j];
            if (!s->name || s->type == 3 ||
                s->shndx == 0 || s->binding != 0)
                continue;
            uint32_t name = append_string(&strtab, s->name);
            write_sym(&symtab, name, s->binding, s->type, s->shndx,
                      sym_addr[mod_sym_base[i] + j], s->size);
        }
    }
    uint32_t first_global = (uint32_t)(symtab.len / 24);
    uint32_t start_name = append_string(&strtab, "_start");
    write_sym(&symtab, start_name, 1, 2, 1,
              entry, 22);
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t j = 0; j < m->num_syms; j++) {
            const EmitSymbol *s = &m->syms[j];
            if (!s->name || s->type == 3 ||
                s->shndx == 0 || s->binding == 0)
                continue;
            uint32_t name = append_string(&strtab, s->name);
            write_sym(&symtab, name, s->binding, s->type, s->shndx,
                      sym_addr[mod_sym_base[i] + j], s->size);
        }
    }
    EmitModule dbg;
    int have_dbg = want_debug;
    if (have_dbg) {
        emit_module_init(&dbg);
        dbg.text.len = text_len;
        for (size_t i = 0; i < n; i++) {
            EmitModule *m = mods[i];
            if (!dbg.dbg_tu_name && m->dbg_tu_name)
                dbg.dbg_tu_name = xstrdup(m->dbg_tu_name);
            for (size_t j = 0; j < m->num_dbg_lines; j++) {
                const DebugLineEntry *line = &m->dbg_lines[j];
                emit_module_add_dbg_line(&dbg, line->file, line->line,
                                         line->col,
                                         mod_text_off[i] + line->pc_off);
            }
            for (size_t j = 0; j < m->num_dbg_funcs; j++) {
                const DebugFunc *f = &m->dbg_funcs[j];
                int fi = emit_module_add_dbg_func(
                    &dbg, f->name, f->file, f->line,
                    mod_text_off[i] + f->start_pc);
                emit_module_dbg_func_end(
                    &dbg, fi, mod_text_off[i] + f->end_pc,
                    mod_text_off[i] + f->prologue_end_pc);
                for (size_t k = 0; k < f->num_vars; k++) {
                    emit_module_add_dbg_var(&dbg, fi, &f->vars[k]);
                    DebugVar *dv = &dbg.dbg_funcs[fi].vars[
                        dbg.dbg_funcs[fi].num_vars - 1];
                    for (size_t r = 0; r < dv->num_ranges; r++) {
                        dv->ranges[r].pc_start += mod_text_off[i];
                        dv->ranges[r].pc_end += mod_text_off[i];
                    }
                }
                for (size_t k = 0; k < f->num_call_sites; k++) {
                    DebugCallSite cs = f->call_sites[k];
                    cs.call_pc += mod_text_off[i];
                    cs.return_pc += mod_text_off[i];
                    emit_module_add_dbg_call_site(&dbg, fi, &cs);
                }
            }
            for (size_t j = 0; j < m->num_dbg_globals; j++)
                emit_module_add_dbg_global(&dbg, &m->dbg_globals[j]);
            for (size_t j = 0; j < m->num_syms; j++) {
                const EmitSymbol *s = &m->syms[j];
                if (!s->name || s->shndx == 0) continue;
                emit_module_add_symbol(
                    &dbg, s->name, s->binding, s->type, s->shndx,
                    sym_addr[mod_sym_base[i] + j], s->size);
            }
        }
        debug_emit_dwarf(&dbg, code_vaddr, &debug_abbrev, &debug_info,
                         &debug_str, &debug_line, &debug_frame, &debug_loc);
    }
    buf_u8(&shstrtab, 0);
    uint32_t shname_text = append_string(&shstrtab, ".text");
    uint32_t shname_rodata = append_string(&shstrtab, ".rodata");
    uint32_t shname_data = append_string(&shstrtab, ".data");
    uint32_t shname_bss = append_string(&shstrtab, ".bss");
    uint32_t shname_symtab = append_string(&shstrtab, ".symtab");
    uint32_t shname_strtab = append_string(&shstrtab, ".strtab");
    uint32_t shname_shstrtab = append_string(&shstrtab, ".shstrtab");
    uint32_t shname_debug_abbrev = 0, shname_debug_info = 0;
    uint32_t shname_debug_str = 0, shname_debug_line = 0;
    uint32_t shname_debug_frame = 0, shname_debug_loc = 0;
    if (have_dbg) {
        shname_debug_abbrev = append_string(&shstrtab, ".debug_abbrev");
        shname_debug_info = append_string(&shstrtab, ".debug_info");
        shname_debug_str = append_string(&shstrtab, ".debug_str");
        shname_debug_line = append_string(&shstrtab, ".debug_line");
        shname_debug_frame = append_string(&shstrtab, ".debug_frame");
        shname_debug_loc = append_string(&shstrtab, ".debug_loc");
    }
    uint32_t shname_dynstr = 0, shname_dynsym = 0, shname_hash = 0;
    uint32_t shname_rela_plt = 0, shname_rela_dyn = 0, shname_dynamic = 0;
    if (lay->have_dynamic) {
        shname_dynstr = append_string(&shstrtab, ".dynstr");
        shname_dynsym = append_string(&shstrtab, ".dynsym");
        shname_hash = append_string(&shstrtab, ".hash");
        shname_rela_plt = append_string(&shstrtab, ".rela.plt");
        shname_rela_dyn = append_string(&shstrtab, ".rela.dyn");
        shname_dynamic = append_string(&shstrtab, ".dynamic");
    }
    while (elf->len & 7) buf_u8(elf, 0);
    size_t off_symtab = elf->len;
    buf_bytes(elf, symtab.data, symtab.len);
    size_t off_strtab = elf->len;
    buf_bytes(elf, strtab.data, strtab.len);
    size_t off_shstrtab = elf->len;
    buf_bytes(elf, shstrtab.data, shstrtab.len);
    size_t off_debug_abbrev = elf->len;
    if (have_dbg) buf_bytes(elf, debug_abbrev.data, debug_abbrev.len);
    size_t off_debug_info = elf->len;
    if (have_dbg) buf_bytes(elf, debug_info.data, debug_info.len);
    size_t off_debug_str = elf->len;
    if (have_dbg) buf_bytes(elf, debug_str.data, debug_str.len);
    size_t off_debug_line = elf->len;
    if (have_dbg) buf_bytes(elf, debug_line.data, debug_line.len);
    if (have_dbg) while (elf->len & 7) buf_u8(elf, 0);
    size_t off_debug_frame = elf->len;
    if (have_dbg) buf_bytes(elf, debug_frame.data, debug_frame.len);
    if (have_dbg) while (elf->len & 7) buf_u8(elf, 0);
    size_t off_debug_loc = elf->len;
    if (have_dbg) buf_bytes(elf, debug_loc.data, debug_loc.len);
    while (elf->len & 7) buf_u8(elf, 0);
    uint64_t shoff = elf->len;
    buf_pad(elf, 64);
    write_shdr_exec(elf, shname_text, 1,
                    0x2 | 0x4, code_vaddr, text_offset,
                    text_len, 0, 0, 16, 0);
    write_shdr_exec(elf, shname_rodata, 1, 0x2,
                    code_vaddr + text_len, text_offset + text_len,
                    rodata_len, 0, 0, 8, 0);
    write_shdr_exec(elf, shname_data, 1, 0x2 | 0x1,
                    data_vaddr, data_file_offset, data_len, 0, 0, 8, 0);
    write_shdr_exec(elf, shname_bss, 8, 0x2 | 0x1,
                    bss_vaddr, bss_file_offset,
                    bss_size, 0, 0, 8, 0);
    write_shdr_exec(elf, shname_symtab, 2, 0, 0, off_symtab,
                    symtab.len, 6, first_global, 8, 24);
    write_shdr_exec(elf, shname_strtab, 3, 0, 0, off_strtab,
                    strtab.len, 0, 0, 1, 0);
    write_shdr_exec(elf, shname_shstrtab, 3, 0, 0, off_shstrtab,
                    shstrtab.len, 0, 0, 1, 0);
    if (have_dbg) {
        write_shdr_exec(elf, shname_debug_abbrev, 1, 0, 0,
                        off_debug_abbrev, debug_abbrev.len, 0, 0, 1, 0);
        write_shdr_exec(elf, shname_debug_info, 1, 0, 0,
                        off_debug_info, debug_info.len, 0, 0, 1, 0);
        write_shdr_exec(elf, shname_debug_str, 1, 0, 0,
                        off_debug_str, debug_str.len, 0, 0, 1, 0);
        write_shdr_exec(elf, shname_debug_line, 1, 0, 0,
                        off_debug_line, debug_line.len, 0, 0, 1, 0);
        write_shdr_exec(elf, shname_debug_frame, 1, 0, 0,
                        off_debug_frame, debug_frame.len, 0, 0, 8, 0);
        write_shdr_exec(elf, shname_debug_loc, 1, 0, 0,
                        off_debug_loc, debug_loc.len, 0, 0, 1, 0);
    }
    int dyn_base = have_dbg ? 14 : 8;
    if (lay->have_dynamic) {
        write_shdr_exec(elf, shname_dynstr, 3, 0x2,
                        lay->dynstr_vaddr, lay->dynstr_off, lay->dynstr_size,
                        0, 0, 1, 0);
        write_shdr_exec(elf, shname_dynsym, 11, 0x2,
                        lay->dynsym_vaddr, lay->dynsym_off, lay->dynsym_size,
                        dyn_base + 0, 1, 8, 24);
        write_shdr_exec(elf, shname_hash, 5, 0x2,
                        lay->hash_vaddr, lay->hash_off, lay->hash_size,
                        dyn_base + 1, 0, 4, 4);
        write_shdr_exec(elf, shname_rela_plt, 4, 0x2,
                        lay->rela_plt_vaddr, lay->rela_plt_off,
                        lay->rela_plt_size, dyn_base + 1, 1, 8, 24);
        write_shdr_exec(elf, shname_rela_dyn, 4, 0x2,
                        lay->rela_dyn_vaddr, lay->rela_dyn_off,
                        lay->rela_dyn_size, dyn_base + 1, 3, 8, 24);
        write_shdr_exec(elf, shname_dynamic, 6,
                        0x2 | 0x1, lay->dynamic_vaddr,
                        lay->dynamic_off, lay->dynamic_size,
                        dyn_base + 0, 0, 8, 16);
    }
    uint16_t shnum = (uint16_t)(8 + (have_dbg ? 6 : 0) + (lay->have_dynamic ? 6 : 0));
    uint16_t shstrndx = 7;
    memcpy(elf->data + 40, &shoff, sizeof(shoff));
    memcpy(elf->data + 60, &shnum, sizeof(shnum));
    memcpy(elf->data + 62, &shstrndx, sizeof(shstrndx));
    if (have_dbg) {
        dbg.text.len = 0;
        emit_module_free(&dbg);
    }
    buffer_free(&symtab); buffer_free(&strtab); buffer_free(&shstrtab);
    buffer_free(&debug_abbrev); buffer_free(&debug_info);
    buffer_free(&debug_str); buffer_free(&debug_line);
    buffer_free(&debug_frame); buffer_free(&debug_loc);
}
static void gen_start(Buffer *code, uint64_t call_vaddr, uint64_t main_vaddr,
                      uint64_t exit_plt_vaddr) {
    uint8_t mov_edi[] = {0x8b, 0x3c, 0x24};
    buffer_append(code, (const char *)mov_edi, 3);
    uint8_t lea_rsi[] = {0x48, 0x8d, 0x74, 0x24, 0x08};
    buffer_append(code, (const char *)lea_rsi, 5);
    uint8_t call_opcode = 0xe8;
    buffer_append(code, (const char *)&call_opcode, 1);
    int32_t rel = (int32_t)(main_vaddr - (call_vaddr + 3 + 5 + 5));
    buffer_append(code, (const char *)&rel, 4);
    uint8_t mov_reg[] = {0x89, 0xc7};
    buffer_append(code, (const char *)mov_reg, 2);
    if (exit_plt_vaddr != 0) {
        buffer_append(code, (const char *)&call_opcode, 1);
        int32_t erel = (int32_t)(exit_plt_vaddr -
                                 (call_vaddr + 3 + 5 + 5 + 2 + 5));
        buffer_append(code, (const char *)&erel, 4);
        uint8_t ud2[] = {0x0f, 0x0b};
        buffer_append(code, (const char *)ud2, 2);
    } else {
        uint8_t mov_imm[] = {0xb8, 0x3c, 0x00, 0x00, 0x00};
        buffer_append(code, (const char *)mov_imm, 5);
        uint8_t syscall[] = {0x0f, 0x05};
        buffer_append(code, (const char *)syscall, 2);
    }
}
static unsigned long elf_hash(const char *name) {
    unsigned long h = 0, g;
    while (*name) {
        h = (h << 4) + (unsigned char)*name++;
        g = h & 0xf0000000;
        if (g) h ^= g >> 24;
        h &= ~g;
    }
    return h;
}
static size_t emit_plt0(Buffer *code, size_t got_fixup[2]) {
    size_t start = code->len;
    emit_byte(code, 0xFF); emit_byte(code, 0x35);
    got_fixup[0] = code->len;
    emit_int32(code, 0);
    emit_byte(code, 0xFF); emit_byte(code, 0x25);
    got_fixup[1] = code->len;
    emit_int32(code, 0);
    while ((code->len - start) < 16) emit_byte(code, 0x90);
    return start;
}
static size_t emit_plt_entry(Buffer *code, size_t idx, size_t plt0_off,
                             size_t *got_fixup) {
    size_t start = code->len;
    emit_byte(code, 0xFF); emit_byte(code, 0x25);
    *got_fixup = code->len;
    emit_int32(code, 0);
    emit_byte(code, 0x68);
    emit_int32(code, (int32_t)idx);
    emit_byte(code, 0xE9);
    size_t pjmp = code->len;
    emit_int32(code, 0);
    int32_t rel = (int32_t)plt0_off - (int32_t)(pjmp + 4);
    memcpy(code->data + pjmp, &rel, 4);
    return start;
}
static int ext_find_or_add(char ***ext, int *num_ext, const char *name) {
    for (int e = 0; e < *num_ext; e++)
        if (runtime.strcmp((*ext)[e], name) == 0) return e;
    *ext = realloc(*ext, ((size_t)*num_ext + 1) * sizeof(char *));
    (*ext)[(*num_ext)++] = xstrdup(name);
    return *num_ext - 1;
}
static void needed_add(char ***needed, int *num, const char *soname) {
    for (int i = 0; i < *num; i++)
        if (runtime.strcmp((*needed)[i], soname) == 0) return;
    *needed = realloc(*needed, ((size_t)*num + 1) * sizeof(char *));
    if (!*needed) { runtime.fprintf(stderr, "fakecc: OOM\n"); runtime.exit(1); }
    (*needed)[(*num)++] = xstrdup(soname);
}
void emit_link(EmitModule **mods, size_t n, const char *path,
               const char **needed_in, size_t num_needed_in, int nodefaultlibs,
               const char **lib_paths, size_t num_lib_paths,
               int want_debug) {
Buffer text;
Buffer rodata;
Buffer data;
    buffer_init(&text); buffer_init(&rodata); buffer_init(&data);
    size_t bss_size = 0;
    size_t *mod_text_off = xcalloc(n, sizeof(size_t));
    size_t *mod_rodata_off = xcalloc(n, sizeof(size_t));
    size_t *mod_data_off = xcalloc(n, sizeof(size_t));
    size_t *mod_bss_off = xcalloc(n, sizeof(size_t));
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        while (text.len & 15) { char z = 0; buffer_append(&text, &z, 1); }
        mod_text_off[i] = text.len;
        buffer_append(&text, m->text.data, m->text.len);
        while (rodata.len & 7) { char z = 0; buffer_append(&rodata, &z, 1); }
        mod_rodata_off[i] = rodata.len;
        buffer_append(&rodata, m->rodata.data, m->rodata.len);
        while (data.len & 7) { char z = 0; buffer_append(&data, &z, 1); }
        mod_data_off[i] = data.len;
        buffer_append(&data, m->data.data, m->data.len);
        while (bss_size & 7) bss_size++;
        mod_bss_off[i] = bss_size;
        bss_size += m->bss_size;
    }
    size_t *mod_sym_base = xcalloc(n + 1, sizeof(size_t));
    for (size_t i = 0; i < n; i++)
        mod_sym_base[i + 1] = mod_sym_base[i] + mods[i]->num_syms;
    size_t total_syms = mod_sym_base[n];
    SymInfo *sinfo = xcalloc(total_syms, sizeof(SymInfo));
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t j = 0; j < m->num_syms; j++) {
            size_t gsi = mod_sym_base[i] + j;
            sinfo[gsi].shndx = m->syms[j].shndx;
            sinfo[gsi].value = m->syms[j].value;
            sinfo[gsi].binding = m->syms[j].binding;
            sinfo[gsi].defined = (m->syms[j].shndx != 0);
        }
    }
    char **ext_list = ((void*)0);
    int num_ext = 0;
    int *reloc_ext_idx = xcalloc(total_syms, sizeof(int));
    for (size_t i = 0; i < total_syms; i++) reloc_ext_idx[i] = -1;
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t r = 0; r < m->num_relocs; r++) {
            if (m->relocs[r].type == 9) continue;
            size_t gsi = mod_sym_base[i] + m->relocs[r].sym;
            if (sinfo[gsi].defined) continue;
            const char *nm = m->syms[m->relocs[r].sym].name
                             ? m->syms[m->relocs[r].sym].name : "";
            int resolved = 0;
            for (size_t mi = 0; mi < n && !resolved; mi++) {
                EmitModule *om = mods[mi];
                for (size_t mj = 0; mj < om->num_syms; mj++) {
                    size_t ogsi = mod_sym_base[mi] + mj;
                    if (sinfo[ogsi].defined && sinfo[ogsi].binding == 1
                        && om->syms[mj].name
                        && runtime.strcmp(om->syms[mj].name, nm) == 0) {
                        resolved = 1;
                        break;
                    }
                }
            }
            if (!resolved)
                reloc_ext_idx[gsi] = ext_find_or_add(&ext_list, &num_ext, nm);
        }
    }
    char **data_ext_list = ((void*)0);
    int num_data_ext = 0;
    int *reloc_data_got_idx = xcalloc(total_syms, sizeof(int));
    for (size_t i = 0; i < total_syms; i++) reloc_data_got_idx[i] = -1;
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t r = 0; r < m->num_relocs; r++) {
            if (m->relocs[r].type != 9) continue;
            size_t gsi = mod_sym_base[i] + m->relocs[r].sym;
            if (reloc_data_got_idx[gsi] >= 0) continue;
            const char *nm = m->syms[m->relocs[r].sym].name
                             ? m->syms[m->relocs[r].sym].name : "";
            reloc_data_got_idx[gsi] = ext_find_or_add(&data_ext_list, &num_data_ext, nm);
        }
    }
    int *data_got_external = num_data_ext ? xcalloc(num_data_ext, sizeof(int)) : ((void*)0);
    int num_true_data_ext = 0;
    for (int j = 0; j < num_data_ext; j++) {
        const char *nm = data_ext_list[j];
        int found = 0;
        for (size_t mi = 0; mi < n && !found; mi++) {
            EmitModule *om = mods[mi];
            for (size_t mj = 0; mj < om->num_syms; mj++) {
                size_t ogsi = mod_sym_base[mi] + mj;
                if (sinfo[ogsi].defined && sinfo[ogsi].binding == 1
                    && om->syms[mj].name
                    && runtime.strcmp(om->syms[mj].name, nm) == 0) {
                    found = 1;
                    break;
                }
            }
        }
        data_got_external[j] = !found;
        if (!found) num_true_data_ext++;
    }
    int need_dynamic = (num_ext > 0 || num_true_data_ext > 0);
    char **needed = ((void*)0);
    int num_needed = 0;
    for (size_t i = 0; i < num_needed_in; i++)
        needed_add(&needed, &num_needed, needed_in[i]);
    (void)nodefaultlibs;
    char *runpath = ((void*)0);
    if (need_dynamic && num_lib_paths > 0) {
        size_t len = 1;
        for (size_t i = 0; i < num_lib_paths; i++)
            len += runtime.strlen(lib_paths[i]) + (i > 0 ? 1 : 0);
        runpath = malloc(len);
        if (!runpath) { runtime.fprintf(stderr, "fakecc: OOM\n"); runtime.exit(1); }
        size_t pos = 0;
        for (size_t i = 0; i < num_lib_paths; i++) {
            if (i > 0) runpath[pos++] = ':';
            size_t n = runtime.strlen(lib_paths[i]);
            memcpy(runpath + pos, lib_paths[i], n);
            pos += n;
        }
        runpath[pos] = '\0';
    }
    int exit_ext_idx = -1;
    int have_libc = 0;
    for (int i = 0; i < num_needed; i++) {
        if (runtime.strcmp(needed[i], "libc.so.6") == 0) { have_libc = 1; break; }
    }
    if (need_dynamic && have_libc)
        exit_ext_idx = ext_find_or_add(&ext_list, &num_ext, "exit");
    size_t *plt_entry_off = num_ext ? xcalloc(num_ext, sizeof(size_t)) : ((void*)0);
    size_t *plt_got_fixup = num_ext ? xcalloc(num_ext, sizeof(size_t)) : ((void*)0);
    size_t plt0_got_fixup[2] = {0, 0};
    size_t plt0_off = 0;
    if (num_ext > 0) {
        plt0_off = emit_plt0(&text, plt0_got_fixup);
        for (int e = 0; e < num_ext; e++)
            plt_entry_off[e] = emit_plt_entry(&text, e, plt0_off, &plt_got_fixup[e]);
    }
Buffer dynstr;
Buffer dynsym;
Buffer hash;
Buffer rela_plt;
Buffer rela_dyn;
Buffer dynamic;
    buffer_init(&dynstr); buffer_init(&dynsym); buffer_init(&hash);
    buffer_init(&rela_plt); buffer_init(&rela_dyn); buffer_init(&dynamic);
    size_t interp_len = need_dynamic ? sizeof(INTERP_PATH) : 0;
    int num_dynsym_ext = num_ext + num_true_data_ext;
    size_t needed_str_bytes = 0;
    size_t runpath_str_bytes = 0;
    size_t runpath_dynstr_off = 0;
    if (need_dynamic) {
        buf_u8(&dynstr, 0);
        for (int i = 0; i < num_needed; i++) {
            buf_bytes(&dynstr, needed[i], runtime.strlen(needed[i]) + 1);
            needed_str_bytes += runtime.strlen(needed[i]) + 1;
        }
        if (runpath) {
            runpath_dynstr_off = dynstr.len;
            buf_bytes(&dynstr, runpath, runtime.strlen(runpath) + 1);
            runpath_str_bytes = runtime.strlen(runpath) + 1;
        }
        for (int i = 0; i < num_ext; i++)
            buf_bytes(&dynstr, ext_list[i], runtime.strlen(ext_list[i]) + 1);
        for (int j = 0; j < num_data_ext; j++) {
            if (!data_got_external[j]) continue;
            buf_bytes(&dynstr, data_ext_list[j], runtime.strlen(data_ext_list[j]) + 1);
        }
        buf_pad(&dynsym, 24);
        for (int k = 0; k < num_dynsym_ext; k++) {
            buf_u32(&dynsym, 0);
            buf_u8(&dynsym, 1 << 4);
            buf_u8(&dynsym, 0);
            buf_u16(&dynsym, 0);
            buf_u64(&dynsym, 0);
            buf_u64(&dynsym, 0);
        }
        size_t nsyms = 1 + (size_t)num_dynsym_ext;
        size_t nbucket = (nsyms < 2) ? 1 : 3;
        uint32_t *bucket = calloc(nbucket, sizeof(uint32_t));
        uint32_t *chain = calloc(nsyms, sizeof(uint32_t));
        for (size_t i = 0; i < nsyms; i++) {
            const char *nm = "";
            if (i > 0) {
                int idx = (int)(i - 1);
                if (idx < num_ext) nm = ext_list[idx];
                else {
                    int want = idx - num_ext;
                    int seen = 0;
                    for (int j = 0; j < num_data_ext; j++) {
                        if (!data_got_external[j]) continue;
                        if (seen == want) { nm = data_ext_list[j]; break; }
                        seen++;
                    }
                }
            }
            uint32_t b = (uint32_t)(elf_hash(nm) % nbucket);
            chain[i] = bucket[b];
            bucket[b] = (uint32_t)i;
        }
        buf_u32(&hash, (uint32_t)nbucket);
        buf_u32(&hash, (uint32_t)nsyms);
        for (size_t i = 0; i < nbucket; i++) buf_u32(&hash, bucket[i]);
        for (size_t i = 0; i < nsyms; i++) buf_u32(&hash, chain[i]);
        runtime.free(bucket); runtime.free(chain);
        for (int i = 0; i < num_ext; i++) {
            buf_u64(&rela_plt, 0);
            buf_u64(&rela_plt, ((uint64_t)(i + 1) << 32) | 7);
            buf_u64(&rela_plt, 0);
        }
        {
            int dyn_sym_i = 1 + num_ext;
            for (int j = 0; j < num_data_ext; j++) {
                if (!data_got_external[j]) continue;
                buf_u64(&rela_dyn, 0);
                buf_u64(&rela_dyn, ((uint64_t)dyn_sym_i << 32) | 6);
                buf_u64(&rela_dyn, 0);
                dyn_sym_i++;
            }
        }
    }
    uint16_t phnum_max = 4;
    size_t hdr_size = 64 + 56 * phnum_max;
    size_t start_offset = hdr_size;
    size_t text_offset = start_offset + 22;
    size_t dynamic_size = 0;
    if (need_dynamic) {
        dynamic_size = (size_t)(num_needed + 10 + (runpath ? 1 : 0)
                                + (num_true_data_ext > 0 ? 3 : 0)) * 16;
    }
    size_t dyn_sections_len = interp_len + dynstr.len + dynsym.len + hash.len
        + rela_plt.len + rela_dyn.len + dynamic_size;
    size_t rx_content_len = 22 + text.len + rodata.len + dyn_sections_len;
    size_t rx_filesz = hdr_size + rx_content_len;
    size_t data_file_offset = rx_filesz;
    if (data_file_offset & (0x1000 - 1))
        data_file_offset = (data_file_offset + 0x1000 - 1) & ~(size_t)(0x1000 - 1);
    uint64_t base = 0x400000;
    uint64_t data_vaddr = base + data_file_offset;
    size_t got_data_off = data.len;
    while (got_data_off & 7) got_data_off++;
    uint64_t got_vaddr = data_vaddr + got_data_off;
    size_t layout_got_bytes = need_dynamic
        ? (size_t)(3 + num_ext + num_data_ext) * 8
        : (num_data_ext > 0 ? (size_t)(3 + num_data_ext) * 8 : 0);
    size_t bss_data_off = layout_got_bytes
        ? got_data_off + layout_got_bytes : data.len;
    uint64_t bss_vaddr = data_vaddr + bss_data_off;
    size_t bss_file_offset = data_file_offset + bss_data_off;
    uint64_t code_vaddr = base + text_offset;
    size_t *sym_addr = xcalloc(total_syms, sizeof(size_t));
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t j = 0; j < m->num_syms; j++) {
            size_t gsi = mod_sym_base[i] + j;
            const EmitSymbol *sym = &m->syms[j];
            if (sym->shndx == 0) continue;
            switch (sym->shndx) {
            case 1:
                sym_addr[gsi] = code_vaddr + mod_text_off[i] + sym->value; break;
            case 2:
                sym_addr[gsi] = code_vaddr + text.len + mod_rodata_off[i] + sym->value; break;
            case 3:
                sym_addr[gsi] = data_vaddr + mod_data_off[i] + sym->value; break;
            case 4:
                sym_addr[gsi] = bss_vaddr + mod_bss_off[i] + sym->value; break;
            default:
                sym_addr[gsi] = sym->value; break;
            }
        }
    }
    size_t *data_got_addr = num_data_ext ? xcalloc(num_data_ext, sizeof(size_t)) : ((void*)0);
    for (int j = 0; j < num_data_ext; j++) {
        if (data_got_external[j]) continue;
        const char *nm = data_ext_list[j];
        for (size_t mi = 0; mi < n; mi++) {
            EmitModule *om = mods[mi];
            for (size_t mj = 0; mj < om->num_syms; mj++) {
                size_t ogsi = mod_sym_base[mi] + mj;
                if (sinfo[ogsi].defined && sinfo[ogsi].binding == 1
                    && om->syms[mj].name
                    && runtime.strcmp(om->syms[mj].name, nm) == 0) {
                    data_got_addr[j] = sym_addr[ogsi];
                    break;
                }
            }
        }
    }
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t r = 0; r < m->num_relocs; r++) {
            const EmitReloc *rel = &m->relocs[r];
            size_t patch_in_text = mod_text_off[i] + rel->offset;
            uint64_t P = code_vaddr + patch_in_text;
            if (rel->type == 9) {
                size_t gsi = mod_sym_base[i] + rel->sym;
                int dgidx = reloc_data_got_idx[gsi];
                uint64_t got_slot_vaddr = got_vaddr + (3 + num_ext + dgidx) * 8;
                int32_t disp = (int32_t)(got_slot_vaddr - (P + 4));
                memcpy(text.data + patch_in_text, &disp, 4);
                continue;
            }
            size_t gsi = mod_sym_base[i] + rel->sym;
            uint64_t S;
            if (sinfo[gsi].defined) {
                S = sym_addr[gsi];
            } else {
                const char *nm = m->syms[rel->sym].name
                                 ? m->syms[rel->sym].name : "";
                size_t global_addr = (size_t)-1;
                for (size_t mi = 0; mi < n && global_addr == (size_t)-1; mi++) {
                    EmitModule *om = mods[mi];
                    for (size_t mj = 0; mj < om->num_syms; mj++) {
                        size_t ogsi = mod_sym_base[mi] + mj;
                        if (sinfo[ogsi].defined && sinfo[ogsi].binding == 1
                            && om->syms[mj].name
                            && runtime.strcmp(om->syms[mj].name, nm) == 0) {
                            global_addr = sym_addr[ogsi];
                            break;
                        }
                    }
                }
                if (global_addr != (size_t)-1) {
                    S = global_addr;
                } else {
                    int eidx = reloc_ext_idx[gsi];
                    S = code_vaddr + (eidx >= 0 ? plt_entry_off[eidx] : plt0_off);
                }
            }
            int32_t disp = (int32_t)(S + rel->addend - P);
            memcpy(text.data + patch_in_text, &disp, 4);
        }
    }
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t r = 0; r < m->num_data_relocs; r++) {
            const EmitReloc *rel = &m->data_relocs[r];
            size_t patch_in_data = mod_data_off[i] + rel->offset;
            size_t gsi = mod_sym_base[i] + rel->sym;
            uint64_t S;
            if (sinfo[gsi].defined) {
                S = sym_addr[gsi];
            } else {
                const char *nm = m->syms[rel->sym].name
                                 ? m->syms[rel->sym].name : "";
                size_t global_addr = (size_t)-1;
                for (size_t mi = 0; mi < n && global_addr == (size_t)-1; mi++) {
                    EmitModule *om = mods[mi];
                    for (size_t mj = 0; mj < om->num_syms; mj++) {
                        size_t ogsi = mod_sym_base[mi] + mj;
                        if (sinfo[ogsi].defined && sinfo[ogsi].binding == 1
                            && om->syms[mj].name
                            && runtime.strcmp(om->syms[mj].name, nm) == 0) {
                            global_addr = sym_addr[ogsi];
                            break;
                        }
                    }
                }
                if (global_addr != (size_t)-1) {
                    S = global_addr;
                } else {
                    int eidx = reloc_ext_idx[gsi];
                    S = code_vaddr + (eidx >= 0 ? plt_entry_off[eidx] : plt0_off);
                }
            }
            uint64_t value = S + rel->addend;
            memcpy(data.data + patch_in_data, &value, 8);
        }
    }
    if (num_ext > 0) {
        for (int f = 0; f < 2; f++) {
            uint64_t target = got_vaddr + (1 + f) * 8;
            uint64_t rip_next = code_vaddr + plt0_got_fixup[f] + 4;
            int32_t disp = (int32_t)((int64_t)target - (int64_t)rip_next);
            memcpy(text.data + plt0_got_fixup[f], &disp, 4);
        }
        for (int e = 0; e < num_ext; e++) {
            uint64_t target = got_vaddr + (3 + e) * 8;
            uint64_t rip_next = code_vaddr + plt_got_fixup[e] + 4;
            int32_t disp = (int32_t)((int64_t)target - (int64_t)rip_next);
            memcpy(text.data + plt_got_fixup[e], &disp, 4);
        }
    }
    uint64_t main_addr = 0;
    uint64_t exit_static_addr = 0;
    int found_main = 0;
    for (size_t i = 0; i < n; i++) {
        EmitModule *m = mods[i];
        for (size_t j = 0; j < m->num_syms; j++) {
            const EmitSymbol *sym = &m->syms[j];
            if (!sym->name || sym->shndx != 1 || sym->binding != 1)
                continue;
            if (runtime.strcmp(sym->name, "main") == 0) {
                main_addr = code_vaddr + mod_text_off[i] + sym->value;
                found_main = 1;
            }
            if (runtime.strcmp(sym->name, "exit") == 0)
                exit_static_addr = code_vaddr + mod_text_off[i] + sym->value;
        }
    }
    if (!found_main) {
        runtime.fprintf(stderr, "fakecc: no 'main' function found\n");
        runtime.exit(1);
    }
    if (need_dynamic) {
        {
            size_t acc = 1 + needed_str_bytes + runpath_str_bytes;
            int k = 0;
            for (int i = 0; i < num_ext; i++, k++) {
                uint32_t noff = (uint32_t)acc;
                memcpy(dynsym.data + 24 + (size_t)k * 24, &noff, 4);
                acc += runtime.strlen(ext_list[i]) + 1;
            }
            for (int j = 0; j < num_data_ext; j++) {
                if (!data_got_external[j]) continue;
                uint32_t noff = (uint32_t)acc;
                memcpy(dynsym.data + 24 + (size_t)k * 24, &noff, 4);
                acc += runtime.strlen(data_ext_list[j]) + 1;
                k++;
            }
        }
        for (int i = 0; i < num_ext; i++) {
            uint64_t roff = got_vaddr + (3 + i) * 8;
            memcpy(rela_plt.data + (size_t)i * 24, &roff, 8);
        }
        {
            int rdj = 0;
            for (int j = 0; j < num_data_ext; j++) {
                if (!data_got_external[j]) continue;
                uint64_t roff = got_vaddr + (3 + num_ext + j) * 8;
                memcpy(rela_dyn.data + (size_t)rdj * 24, &roff, 8);
                rdj++;
            }
        }
        size_t rx_base_vaddr = base + hdr_size;
        size_t dynstr_off = 22 + text.len + rodata.len + interp_len;
        size_t dynsym_off = dynstr_off + dynstr.len;
        size_t hash_off = dynsym_off + dynsym.len;
        size_t rela_plt_off = hash_off + hash.len;
        size_t rela_dyn_off = rela_plt_off + rela_plt.len;
        size_t dynamic_off = rela_dyn_off + rela_dyn.len;
        uint64_t dynstr_vaddr = rx_base_vaddr + dynstr_off;
        {
            size_t off = 1;
            for (int i = 0; i < num_needed; i++) {
                buf_u64(&dynamic, 1);
                buf_u64(&dynamic, off);
                off += runtime.strlen(needed[i]) + 1;
            }
        }
        if (runpath) {
            buf_u64(&dynamic, 29);
            buf_u64(&dynamic, runpath_dynstr_off);
        }
        buf_u64(&dynamic, 5); buf_u64(&dynamic, dynstr_vaddr);
        buf_u64(&dynamic, 6); buf_u64(&dynamic, rx_base_vaddr + dynsym_off);
        buf_u64(&dynamic, 11); buf_u64(&dynamic, 24);
        buf_u64(&dynamic, 10); buf_u64(&dynamic, dynstr.len);
        buf_u64(&dynamic, 4); buf_u64(&dynamic, rx_base_vaddr + hash_off);
        buf_u64(&dynamic, 3); buf_u64(&dynamic, got_vaddr);
        buf_u64(&dynamic, 2); buf_u64(&dynamic, rela_plt.len);
        buf_u64(&dynamic, 20); buf_u64(&dynamic, 7);
        buf_u64(&dynamic, 23); buf_u64(&dynamic, rx_base_vaddr + rela_plt_off);
        if (num_true_data_ext > 0) {
            buf_u64(&dynamic, 7); buf_u64(&dynamic, rx_base_vaddr + rela_dyn_off);
            buf_u64(&dynamic, 8); buf_u64(&dynamic, rela_dyn.len);
            buf_u64(&dynamic, 9); buf_u64(&dynamic, 24);
        }
        buf_u64(&dynamic, 0); buf_u64(&dynamic, 0);
        Buffer rx;
        buffer_init(&rx);
        uint64_t exit_call = 0;
        if (exit_ext_idx >= 0)
            exit_call = code_vaddr + plt_entry_off[exit_ext_idx];
        else if (exit_static_addr)
            exit_call = exit_static_addr;
        gen_start(&rx, base + start_offset, main_addr, exit_call);
        buf_bytes(&rx, text.data, text.len);
        buf_bytes(&rx, rodata.data, rodata.len);
        size_t interp_off = rx.len;
        buf_bytes(&rx, INTERP_PATH, interp_len);
        buf_bytes(&rx, dynstr.data, dynstr.len);
        buf_bytes(&rx, dynsym.data, dynsym.len);
        buf_bytes(&rx, hash.data, hash.len);
        buf_bytes(&rx, rela_plt.data, rela_plt.len);
        buf_bytes(&rx, rela_dyn.data, rela_dyn.len);
        buf_bytes(&rx, dynamic.data, dynamic.len);
        uint64_t entry = base + start_offset;
        size_t got_count = 3 + num_ext + num_data_ext;
        size_t got_bytes = got_count * 8;
        Buffer got;
        buffer_init(&got);
        buf_u64(&got, rx_base_vaddr + dynamic_off);
        buf_u64(&got, 0);
        buf_u64(&got, 0);
        for (int i = 0; i < num_ext; i++)
            buf_u64(&got, code_vaddr + plt_entry_off[i] + 6);
        for (int j = 0; j < num_data_ext; j++)
            buf_u64(&got, data_got_external[j] ? 0 : data_got_addr[j]);
        Buffer elf;
        buffer_init(&elf);
        uint16_t phnum = 4;
        write_ehdr(&elf, entry, 64, phnum);
        write_phdr(&elf, 1, 4 | 1, 0, base, rx_filesz, rx_filesz, 0x1000);
        write_phdr(&elf, 1, 4 | 2, data_file_offset, data_vaddr,
                   got_data_off + got_bytes,
                   got_data_off + got_bytes + bss_size, 0x1000);
        write_phdr(&elf, 3, 4, hdr_size + interp_off, rx_base_vaddr + interp_off,
                   interp_len, interp_len, 1);
        write_phdr(&elf, 2, 4, hdr_size + dynamic_off, rx_base_vaddr + dynamic_off,
                   dynamic.len, dynamic.len, 8);
        buf_bytes(&elf, rx.data, rx.len);
        while (elf.len < data_file_offset) buf_u8(&elf, 0);
        buf_bytes(&elf, data.data, data.len);
        while (elf.len < data_file_offset + got_data_off) buf_u8(&elf, 0);
        buf_bytes(&elf, got.data, got.len);
        SectionLayout lay;
        lay.code_vaddr = code_vaddr;
        lay.data_vaddr = data_vaddr;
        lay.bss_vaddr = bss_vaddr;
        lay.text_offset = text_offset;
        lay.data_file_offset = data_file_offset;
        lay.text_len = text.len;
        lay.rodata_len = rodata.len;
        lay.data_len = data.len;
        lay.bss_file_offset = bss_file_offset;
        lay.bss_size = bss_size;
        lay.have_dynamic = 1;
        lay.dynstr_off = hdr_size + dynstr_off;
        lay.dynsym_off = hdr_size + dynsym_off;
        lay.hash_off = hdr_size + hash_off;
        lay.rela_plt_off = hdr_size + rela_plt_off;
        lay.rela_dyn_off = hdr_size + rela_dyn_off;
        lay.dynamic_off = hdr_size + dynamic_off;
        lay.dynstr_size = dynstr.len;
        lay.dynsym_size = dynsym.len;
        lay.hash_size = hash.len;
        lay.rela_plt_size = rela_plt.len;
        lay.rela_dyn_size = rela_dyn.len;
        lay.dynamic_size = dynamic.len;
        lay.dynstr_vaddr = rx_base_vaddr + dynstr_off;
        lay.dynsym_vaddr = rx_base_vaddr + dynsym_off;
        lay.hash_vaddr = rx_base_vaddr + hash_off;
        lay.rela_plt_vaddr = rx_base_vaddr + rela_plt_off;
        lay.rela_dyn_vaddr = rx_base_vaddr + rela_dyn_off;
        lay.dynamic_vaddr = rx_base_vaddr + dynamic_off;
        finalize_sections(&elf, mods, n, mod_text_off, mod_sym_base, sym_addr,
                          &lay, entry, want_debug);
        FILE *f = fopen(path, "wb");
        if (!f) { runtime.fprintf(stderr, "fakecc: cannot write '%s'\n", path); runtime.exit(1); }
        runtime.fwrite(elf.data, 1, elf.len, f);
        runtime.fclose(f);
        runtime.chmod(path, 0755);
        buffer_free(&rx); buffer_free(&got); buffer_free(&elf);
    } else {
        uint64_t entry = base + start_offset;
        Buffer rx;
        buffer_init(&rx);
        gen_start(&rx, base + start_offset, main_addr, exit_static_addr);
        buf_bytes(&rx, text.data, text.len);
        buf_bytes(&rx, rodata.data, rodata.len);
        size_t got_bytes = 0;
        Buffer got;
        buffer_init(&got);
        if (num_data_ext > 0) {
            got_bytes = (size_t)(3 + num_data_ext) * 8;
            buf_u64(&got, 0);
            buf_u64(&got, 0);
            buf_u64(&got, 0);
            for (int j = 0; j < num_data_ext; j++)
                buf_u64(&got, data_got_addr[j]);
        }
        Buffer elf;
        buffer_init(&elf);
        int has_rw = (data.len > 0 || bss_size > 0 || got_bytes > 0);
        uint16_t phnum = has_rw ? 2 : 1;
        write_ehdr(&elf, entry, 64, phnum);
        write_phdr(&elf, 1, 4 | 1, 0, base,
                   rx_filesz, rx_filesz, 0x1000);
        if (has_rw) {
            write_phdr(&elf, 1, 4 | 2, data_file_offset, data_vaddr,
                       bss_data_off, bss_data_off + bss_size, 0x1000);
        }
        while (elf.len < hdr_size)
            buf_u8(&elf, 0);
        buf_bytes(&elf, rx.data, rx.len);
        if (has_rw) {
            while (elf.len < data_file_offset) buf_u8(&elf, 0);
            buf_bytes(&elf, data.data, data.len);
            if (got_bytes > 0)
                while (elf.len < data_file_offset + got_data_off) buf_u8(&elf, 0);
            buf_bytes(&elf, got.data, got.len);
        }
        SectionLayout lay;
        lay.code_vaddr = code_vaddr;
        lay.data_vaddr = data_vaddr;
        lay.bss_vaddr = bss_vaddr;
        lay.text_offset = text_offset;
        lay.data_file_offset = data_file_offset;
        lay.text_len = text.len;
        lay.rodata_len = rodata.len;
        lay.data_len = data.len;
        lay.bss_file_offset = bss_file_offset;
        lay.bss_size = bss_size;
        lay.have_dynamic = 0;
        finalize_sections(&elf, mods, n, mod_text_off, mod_sym_base, sym_addr,
                          &lay, entry, want_debug);
        FILE *f = fopen(path, "wb");
        if (!f) { runtime.fprintf(stderr, "fakecc: cannot write '%s'\n", path); runtime.exit(1); }
        runtime.fwrite(elf.data, 1, elf.len, f);
        runtime.fclose(f);
        runtime.chmod(path, 0755);
        buffer_free(&rx); buffer_free(&got); buffer_free(&elf);
    }
    buffer_free(&dynstr); buffer_free(&dynsym); buffer_free(&hash);
    buffer_free(&rela_plt); buffer_free(&rela_dyn); buffer_free(&dynamic);
    for (int i = 0; i < num_ext; i++) runtime.free(ext_list[i]);
    runtime.free(ext_list);
    for (int j = 0; j < num_data_ext; j++) runtime.free(data_ext_list[j]);
    runtime.free(data_ext_list);
    for (int i = 0; i < num_needed; i++) runtime.free(needed[i]);
    runtime.free(needed);
    runtime.free(runpath);
    buffer_free(&text); buffer_free(&rodata); buffer_free(&data);
    runtime.free(mod_text_off); runtime.free(mod_rodata_off); runtime.free(mod_data_off); runtime.free(mod_bss_off);
    runtime.free(mod_sym_base); runtime.free(sym_addr); runtime.free(sinfo); runtime.free(reloc_ext_idx);
    runtime.free(reloc_data_got_idx);
    runtime.free(plt_entry_off); runtime.free(plt_got_fixup);
    runtime.free(data_got_addr); runtime.free(data_got_external);
}
