package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
void die_at(const char *file, int line, int col, const char *fmt, ...);
typedef unsigned char uint8_t;
typedef unsigned short uint16_t;
typedef unsigned int uint32_t;
typedef unsigned long uint64_t;
typedef char int8_t;
typedef short int16_t;
typedef int int32_t;
typedef long int64_t;
typedef int bool;
typedef int IRValue;
enum IROpcode {
    IR_CONST,
    IR_ADD,
    IR_SUB,
    IR_MUL,
    IR_DIV,
    IR_MOD,
    IR_NEG,
    IR_BAND,
    IR_BOR,
    IR_BXOR,
    IR_BNOT,
    IR_SHL,
    IR_SHR,
    IR_EQ,
    IR_NE,
    IR_FADD,
    IR_FSUB,
    IR_FMUL,
    IR_FDIV,
    IR_FCMP,
    IR_VADD,
    IR_VSUB,
    IR_VMUL,
    IR_VDIV,
    IR_VBAND,
    IR_VBOR,
    IR_VBXOR,
    IR_SITOFP,
    IR_FPTOSI,
    IR_FPEXT,
    IR_FPTRUNC,
    IR_LT,
    IR_LE,
    IR_GT,
    IR_GE,
    IR_ALLOCA,
    IR_LOAD,
    IR_STORE,
    IR_ADDR,
    IR_LOAD_PTR,
    IR_STORE_PTR,
    IR_COPY,
    IR_LABEL,
    IR_BR,
    IR_CBR,
    IR_PARAM,
    IR_CALL,
    IR_RETURN,
    IR_SEXT,
    IR_ZEXT,
    IR_TRUNC,
    IR_GADDR,
    IR_FADDR,
    IR_LADDR,
    IR_JMP_PTR,
    IR_FRAME_ADDR,
    IR_RETURN_ADDR,
    IR_DYN_ALLOCA,
    IR_STACK_SAVE,
    IR_STACK_RESTORE,
    IR_LONGJMP,
    IR_DBG_VALUE,
};typedef enum IROpcode IROpcode;
struct IRInst {
    IROpcode op;
    IRValue dst;
    IRValue a;
    IRValue b;
    int64_t imm;
    SourceLoc loc;
    char *call_name;
    IRValue call_args[64];
    int call_nargs;
    IRValue call_callee;
    int width;
    int is_unsigned;
    int64_t float_imm;
    int is_float;
    int force_stack;
    unsigned char call_arg_on_stack[64];
    int alloca_bytes;
};typedef struct IRInst IRInst;
struct IRInstArray {
    IRInst *data;
    size_t len;
    size_t cap;
};typedef struct IRInstArray IRInstArray;
enum IRDebugVarKind {
    IR_DBG_PARAM = 0,
    IR_DBG_LOCAL = 1
};typedef enum IRDebugVarKind IRDebugVarKind;
struct IRDebugMember {
    char *name;
    int offset;
    int bit_width;
    int bit_offset;
    int type_kind;
    int width;
    int is_unsigned;
    int is_bool;
};typedef struct IRDebugMember IRDebugMember;
struct IRDebugVar {
    char *name;
    SourceLoc loc;
    IRDebugVarKind kind;
    int type_kind;
    int width;
    int is_unsigned;
    int is_bool;
    int array_len;
    char *struct_tag;
    int struct_size;
    IRDebugMember *members;
    int num_members;
    int alloca_ssa;
    int param_idx;
};typedef struct IRDebugVar IRDebugVar;
struct ExtractedMarker {
    int var;
    int value;
    int pos;
};typedef struct ExtractedMarker ExtractedMarker;
struct IRFunction {
    char *name;
    IRInstArray insts;
    int next_value_id;
    int next_label_id;
    SourceLoc loc;
    void *ra;
    void *ra_xmm;
    int *value_width;
    int *value_is_unsigned;
    int value_meta_cap;
    int *value_is_float;
    int ret_width;
    int ret_is_unsigned;
    int ret_is_float;
    int ret_is_struct;
    int ret_reg_n;
    int ret_reg_cls[2];
    int ret_is_bool;
    int is_variadic;
    int is_static;
    int has_dyn_alloca;
    IRValue sret_value;
    IRDebugVar *dbg_vars;
    size_t num_dbg_vars;
    size_t cap_dbg_vars;
};typedef struct IRFunction IRFunction;
struct IRFunctionArray {
    IRFunction *data;
    size_t len;
    size_t cap;
};typedef struct IRFunctionArray IRFunctionArray;
struct GlobalFixup {
    int offset;
    char *sym;
    int addend;
};typedef struct GlobalFixup GlobalFixup;
struct IRGlobal {
    char *name;
    int size;
    char *init_bytes;
    int is_readonly;
    int is_static;
    SourceLoc loc;
    GlobalFixup *fixups;
    int num_fixups;
    int cap_fixups;
};typedef struct IRGlobal IRGlobal;
struct IRGlobalArray {
    IRGlobal *data;
    size_t len;
    size_t cap;
};typedef struct IRGlobalArray IRGlobalArray;
struct IRAlias {
    char *name;
    char *target;
    int is_static;
    SourceLoc loc;
};typedef struct IRAlias IRAlias;
struct IRAliasArray {
    IRAlias *data;
    size_t len;
    size_t cap;
};typedef struct IRAliasArray IRAliasArray;
struct IRModule {
    IRFunctionArray functions;
    IRGlobalArray globals;
    IRAliasArray aliases;
};typedef struct IRModule IRModule;
void ir_module_init(IRModule *m);
void ir_module_free(IRModule *m);
void ir_module_push_alias(IRModule *m, const char *name, const char *target,
                          int is_static, SourceLoc loc);
enum TokenKind {
    TK_KW_PACKAGE,
    TK_KW_IMPORT,
    TK_KW_VOID,
    TK_KW_INT,
    TK_KW_FLOAT,
    TK_KW_DOUBLE,
    TK_KW_CHAR,
    TK_KW_SHORT,
    TK_KW_LONG,
    TK_KW_SIGNED,
    TK_KW_UNSIGNED,
    TK_KW_SIZEOF,
    TK_KW_RETURN,
    TK_KW_IF,
    TK_KW_ELSE,
    TK_KW_WHILE,
    TK_KW_FOR,
    TK_KW_GOTO,
    TK_KW_SWITCH,
    TK_KW_CASE,
    TK_KW_DEFAULT,
    TK_KW_BREAK,
    TK_KW_CONTINUE,
    TK_KW_CONST,
    TK_KW_UNION,
    TK_KW_DO,
    TK_KW_ENUM,
    TK_KW_STRUCT,
    TK_KW_TYPEDEF,
    TK_KW_STATIC,
    TK_KW_EXTERN,
    TK_KW_BOOL,
    TK_KW_VOLATILE,
    TK_KW_RESTRICT,
    TK_KW_INLINE,
    TK_KW_ALIGNOF,
    TK_KW_LONG_DOUBLE,
    TK_KW_COMPLEX,
    TK_KW_REAL,
    TK_KW_IMAG,
    TK_IDENT,
    TK_INT_LITERAL,
    TK_FLOAT_LITERAL,
    TK_CHAR_LITERAL,
    TK_STRING_LITERAL,
    TK_LPAREN,
    TK_RPAREN,
    TK_LBRACE,
    TK_RBRACE,
    TK_LBRACKET,
    TK_RBRACKET,
    TK_SEMICOLON,
    TK_COMMA,
    TK_PLUS,
    TK_MINUS,
    TK_STAR,
    TK_SLASH,
    TK_PERCENT,
    TK_AMP,
    TK_ANDAND,
    TK_OROR,
    TK_BITOR,
    TK_XOR,
    TK_TILDE,
    TK_NOT,
    TK_SHL,
    TK_SHR,
    TK_SHL_EQ,
    TK_SHR_EQ,
    TK_PLUS_EQ,
    TK_MINUS_EQ,
    TK_STAR_EQ,
    TK_SLASH_EQ,
    TK_PERCENT_EQ,
    TK_AMP_EQ,
    TK_BITOR_EQ,
    TK_XOR_EQ,
    TK_INC,
    TK_DEC,
    TK_QUESTION,
    TK_COLON,
    TK_DOT,
    TK_ELLIPSIS,
    TK_ARROW,
    TK_ASSIGN,
    TK_EQ,
    TK_NE,
    TK_LT,
    TK_LE,
    TK_GT,
    TK_GE,
    TK_EOF,
};typedef enum TokenKind TokenKind;
struct Token {
    TokenKind kind;
    char *text;
    SourceLoc loc;
};typedef struct Token Token;
struct TokenArray {
    Token *data;
    size_t len;
    size_t cap;
};typedef struct TokenArray TokenArray;
void token_array_init(TokenArray *a);
void token_array_free(TokenArray *a);
void token_array_push(TokenArray *a, Token t);
enum TypeKind {
    TY_VOID,
    TY_INT,
    TY_FLOAT,
    TY_PTR,
    TY_ARRAY,
    TY_STRUCT,
    TY_FUNC,
};typedef enum TypeKind TypeKind;
typedef struct Type Type;
struct Type {
    TypeKind kind;
    long long width;
    int is_unsigned;
    unsigned is_const : 1;
    unsigned is_volatile : 1;
    unsigned is_restrict : 1;
    unsigned is_bool : 1;
    Type *pointee;
    Type *elem_type;
    long long length;
    struct Expr *vla_dim;
    char *tag;
    Type *func_ret;
    Type *func_params;
    int func_nparams;
    int func_is_variadic;
    int enum_id;
    int bitfield_width;
    int is_vector;
};
static inline Type type_make_int(long long width, int is_unsigned) {
    Type t; t.kind = TY_INT; t.width = width; t.is_unsigned = is_unsigned;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; return t;
}
static inline Type type_make_bool(void) {
    Type t = type_make_int(1, 1);
    t.is_bool = 1;
    return t;
}
static inline Type type_default_int(void) { return type_make_int(4, 0); }
static inline Type type_make_float(long long width) {
    Type t; t.kind = TY_FLOAT; t.width = width; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; return t;
}
static inline Type type_make_void(void) {
    Type t; t.kind = TY_VOID; t.width = 0; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.vla_dim = ((void*)0); t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; t.func_is_variadic = 0; t.enum_id = 0;
    t.bitfield_width = 0; t.is_vector = 0; return t;
}
Type type_clone(Type t);
void type_free(Type *t);
long long type_size(Type t);
long long type_align(Type t);
enum SysVRegClass {
    SYSV_CLS_INTEGER = 1,
    SYSV_CLS_SSE = 2
};typedef enum SysVRegClass SysVRegClass;
int sysv_classify_agg(Type t, SysVRegClass cls[2]);
Type type_make_ptr(Type pointee);
Type type_make_array(Type elem, long long length);
Type type_make_vector(Type elem, long long vec_size);
Type type_make_vla(Type elem, struct Expr *dim);
Type type_make_struct(const char *tag, long long size);
Type type_make_func(Type ret, Type * *params, int nparams);
Type type_make_func_var(Type ret, Type * *params, int nparams, int is_variadic);
Type type_decay(Type t);
int type_is_ptr_or_array(Type t);
Type type_pointee_or_elem(Type t);
int type_funcs_equal(Type a, Type b);
int type_is_vla(Type t);
int type_same_typedef(Type a, Type b);
struct Expr *expr_clone(const struct Expr *e);
enum ExprKind {
    EX_INT_LIT,
    EX_BINOP,
    EX_UNARY,
    EX_VAR,
    EX_ASSIGN,
    EX_CALL,
    EX_STR,
    EX_ADDR,
    EX_DEREF,
    EX_INDEX,
    EX_MEMBER,
    EX_CAST,
    EX_SIZEOF_TYPE,
    EX_SIZEOF_EXPR,
    EX_ALIGNOF_TYPE,
    EX_ALIGNOF_EXPR,
    EX_TERNARY,
    EX_INC_DEC,
    EX_COMPOUND_ASSIGN,
    EX_COMMA,
    EX_INIT_LIST,
    EX_FLOAT_LIT,
    EX_COMPOUND_LITERAL,
    EX_STMT_EXPR,
    EX_LABEL_ADDR,
};typedef enum ExprKind ExprKind;
enum BinOp {
    BOP_ADD,
    BOP_SUB,
    BOP_MUL,
    BOP_DIV,
    BOP_MOD,
    BOP_EQ,
    BOP_NE,
    BOP_LT,
    BOP_LE,
    BOP_GT,
    BOP_GE,
    BOP_AND,
    BOP_OR,
    BOP_BITAND,
    BOP_BITOR,
    BOP_BITXOR,
    BOP_SHL,
    BOP_SHR,
};typedef enum BinOp BinOp;
enum UnaryOp {
    UOP_NEG,
    UOP_POS,
    UOP_BITNOT,
    UOP_NOT,
};typedef enum UnaryOp UnaryOp;
typedef struct StmtArray StmtArray;
typedef struct Expr Expr;
int fold_const_int(const Expr *e, long long *out);
struct ExprArray {
    Expr **data;
    size_t len;
    size_t cap;
};typedef struct ExprArray ExprArray;
union __anon_u_1 {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *operand; } alignof_e;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
        struct { StmtArray *stmts; } stmt_expr;
        struct { char *label; } label_addr;
    };struct Expr {
    ExprKind kind;
    SourceLoc loc;
    Type type;
    Type va_arg_type;
    union {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *operand; } alignof_e;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
        struct { StmtArray *stmts; } stmt_expr;
        struct { char *label; } label_addr;
    } u;
    unsigned long long int_hi;
};
Expr *expr_new_int(long long v, SourceLoc loc);
Expr *expr_new_int_typed(long long v, int width, int is_unsigned, SourceLoc loc);
Expr *expr_new_int_bits(unsigned long long lo, unsigned long long hi,
                       int width, int is_unsigned, SourceLoc loc);
Expr *expr_new_binop(BinOp op, Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_unary(UnaryOp op, Expr *operand, SourceLoc loc);
Expr *expr_new_var(const char *name, SourceLoc loc);
Expr *expr_new_var_qual(const char *pkg, const char *name, SourceLoc loc);
Expr *expr_new_assign(Expr *lvalue, Expr *rvalue, SourceLoc loc);
Expr *expr_new_call(Expr *callee, SourceLoc loc);
Expr *expr_new_str(const char *bytes, int len, SourceLoc loc);
Expr *expr_new_addr(Expr *operand, SourceLoc loc);
Expr *expr_new_deref(Expr *operand, SourceLoc loc);
Expr *expr_new_index(Expr *array, Expr *index, SourceLoc loc);
Expr *expr_new_member(Expr *obj, const char *name, SourceLoc loc);
Expr *expr_new_cast(Type target, Expr *operand, SourceLoc loc);
Expr *expr_new_sizeof_type(Type t, SourceLoc loc);
Expr *expr_new_sizeof_expr(Expr *operand, SourceLoc loc);
Expr *expr_new_alignof_type(Type t, SourceLoc loc);
Expr *expr_new_alignof_expr(Expr *operand, SourceLoc loc);
Expr *expr_new_ternary(Expr *cond, Expr *then, Expr *else_, SourceLoc loc);
Expr *expr_new_inc_dec(Expr *operand, int is_inc, int is_prefix, SourceLoc loc);
Expr *expr_new_compound_assign(Expr *lvalue, Expr *rvalue, BinOp op, SourceLoc loc);
Expr *expr_new_comma(Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_init_list(Expr **elements, int num_elements, SourceLoc loc);
Expr *expr_new_float_lit(const char *text, int width, SourceLoc loc);
Expr *expr_new_compound_literal(Type target_type, Expr *init, SourceLoc loc);
Expr *expr_new_stmt_expr(StmtArray *stmts, SourceLoc loc);
Expr *expr_new_label_addr(const char *label, SourceLoc loc);
void expr_call_push_arg(Expr *e, Expr *arg);
void expr_call_set_callee(Expr *e, Expr *callee);
void expr_free(Expr *e);
void expr_set_type(Expr *e, Type t);
enum StmtKind {
    ST_DECL,
    ST_EXPR,
    ST_RETURN,
    ST_IF,
    ST_WHILE,
    ST_FOR,
    ST_BREAK,
    ST_CONTINUE,
    ST_BLOCK,
    ST_DO_WHILE,
    ST_GOTO,
    ST_LABEL,
    ST_SWITCH,
};typedef enum StmtKind StmtKind;
typedef struct Stmt Stmt;
struct StmtArray {
    Stmt *data;
    size_t len;
    size_t cap;
};
struct SwitchCase {
    int is_default;
    int value;
    char *label_name;
    StmtArray stmts;
};typedef struct SwitchCase SwitchCase;
union __anon_u_2 {
        struct { char *name; Type type; Expr *init; int storage_class; char *alias_target; int align; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; Expr *target_expr; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; Stmt *body; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    };struct Stmt {
    StmtKind kind;
    SourceLoc loc;
    union {
        struct { char *name; Type type; Expr *init; int storage_class; char *alias_target; int align; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; Expr *target_expr; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; Stmt *body; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    } u;
};
void stmt_array_init(StmtArray *a);
void stmt_array_push(StmtArray *a, Stmt s);
void stmt_array_free(StmtArray *a);
void stmt_free(Stmt *s);
Stmt stmt_clone(const Stmt *s);
Stmt *stmt_alloc(void);
void stmt_free_ptr(Stmt *s);
void switch_push_case(Stmt *s, int is_default, int value, const char *label_name);
struct Param {
    char *name;
    Type type;
    SourceLoc loc;
};typedef struct Param Param;
struct ParamArray {
    Param *data;
    size_t len;
    size_t cap;
};typedef struct ParamArray ParamArray;
void param_array_init(ParamArray *a);
void param_array_push(ParamArray *a, const char *name, Type type, SourceLoc loc);
void param_array_free(ParamArray *a);
struct FunctionDecl {
    char *name;
    Type ret_type;
    ParamArray params;
    StmtArray body;
    SourceLoc loc;
    int is_variadic;
    int is_unprototyped;
    int is_extern;
    int is_static;
    char *alias_target;
    int align;
    int no_instrument;
};typedef struct FunctionDecl FunctionDecl;
struct PackageDecl {
    char *name;
    SourceLoc loc;
};typedef struct PackageDecl PackageDecl;
struct ImportDecl {
    char *name;
    SourceLoc loc;
};typedef struct ImportDecl ImportDecl;
struct ImportArray {
    ImportDecl *data;
    size_t len;
    size_t cap;
};typedef struct ImportArray ImportArray;
void import_array_init(ImportArray *a);
void import_array_push(ImportArray *a, const char *name, SourceLoc loc);
void import_array_free(ImportArray *a);
struct StructMember {
    char *name;
    Type type;
    long long offset;
    int bit_width;
    int bit_offset;
};typedef struct StructMember StructMember;
struct StructDef {
    char *tag;
    int is_union;
    int is_big_endian;
    StructMember *members;
    int num_members;
    int cap_members;
    long long size;
    long long align;
    int is_packed;
    SourceLoc loc;
    Type *canonical_type;
    long long bf_unit_type;
    int bf_unit_used;
    long long bf_unit_offset;
};typedef struct StructDef StructDef;
struct StructRegistry {
    StructDef *data;
    size_t len;
    size_t cap;
};typedef struct StructRegistry StructRegistry;
void struct_registry_init(StructRegistry *r);
void struct_registry_free(StructRegistry *r);
StructDef *struct_registry_add(StructRegistry *r, const char *tag, SourceLoc loc);
StructDef *struct_registry_find(StructRegistry *r, const char *tag);
const StructDef *struct_registry_find_c(const StructRegistry *r, const char *tag);
void struct_def_push_member(StructDef *sd, const char *name, Type ty, int bit_width);
void struct_def_finish(StructDef *sd);
void struct_def_apply_sso(StructDef *sd, int is_big_endian);
void struct_def_fixup_self_types(StructDef *sd);
const StructMember *struct_lookup_member(const StructRegistry *reg,
                                         const StructDef *sd,
                                         const char *name,
                                         long long *offset_out);
struct FunctionArray {
    FunctionDecl *data;
    size_t len;
    size_t cap;
};typedef struct FunctionArray FunctionArray;
struct EnumConstant {
    char *name;
    int value;
};typedef struct EnumConstant EnumConstant;
struct EnumDef {
    char *tag;
    EnumConstant *constants;
    int num_constants;
    int cap_constants;
    SourceLoc loc;
};typedef struct EnumDef EnumDef;
struct EnumRegistry {
    EnumDef *data;
    size_t len;
    size_t cap;
};typedef struct EnumRegistry EnumRegistry;
void enum_registry_init(EnumRegistry *r);
void enum_registry_free(EnumRegistry *r);
EnumDef *enum_registry_add(EnumRegistry *r, const char *tag, SourceLoc loc);
EnumDef *enum_registry_find(EnumRegistry *r, const char *tag);
int enum_def_push_constant(EnumDef *ed, const char *name, int has_value,
                            int value, SourceLoc loc);
const EnumConstant *enum_registry_find_constant(const EnumRegistry *r,
                                                const char *name);
struct TypedefEntry {
    char *name;
    Type type;
};typedef struct TypedefEntry TypedefEntry;
struct TypedefRegistry {
    TypedefEntry *data;
    size_t len;
    size_t cap;
};typedef struct TypedefRegistry TypedefRegistry;
void typedef_registry_init(TypedefRegistry *r);
void typedef_registry_free(TypedefRegistry *r);
TypedefEntry *typedef_registry_add(TypedefRegistry *r, const char *name, Type type);
const Type *typedef_registry_find(const TypedefRegistry *r, const char *name);
TypedefEntry *typedef_registry_get(TypedefRegistry *r, const char *name);
void typedef_registry_truncate(TypedefRegistry *r, size_t len);
struct TranslationUnit {
    PackageDecl package;
    ImportArray imports;
    StmtArray globals;
    FunctionArray functions;
    StructRegistry structs;
    EnumRegistry enums;
    TypedefRegistry typedefs;
};typedef struct TranslationUnit TranslationUnit;
void tu_init(TranslationUnit *tu);
void tu_free(TranslationUnit *tu);
void ir_generate(const TranslationUnit *tu, IRModule *ir, int pin_locals);
const StructRegistry *get_ir_structs(void);
void opt(IRModule *ir, int opt_level, int want_debug);
struct CFGBlock {
    int id;
    int label;
    size_t start;
    size_t end;
    int *preds;
    size_t num_preds;
    int *succs;
    size_t num_succs;
};typedef struct CFGBlock CFGBlock;
struct CFG {
    CFGBlock *blocks;
    size_t num;
    int entry;
};typedef struct CFG CFG;
void cfg_build(CFG *g, const IRInstArray *insts);
void cfg_free(CFG *g);
int cfg_find_label(const CFG *g, int label);
void cfg_link(CFG *g, int from, int to);
int *cfg_rpo(const CFG *g);
struct DomTree {
    int *idom;
    int **df;
    size_t *df_len;
    size_t n;
};typedef struct DomTree DomTree;
void domtree_build(DomTree *dt, const CFG *cfg);
int domtree_dominates(const DomTree *dt, int a, int b);
void domtree_free(DomTree *dt);
struct PhiArg { IRValue val; int pred; };typedef struct PhiArg PhiArg;
struct IRPhi {
    IRValue dst;
    int alloca_slot;
    PhiArg *args;
    size_t num_args;
    size_t cap_args;
    SourceLoc loc;
};typedef struct IRPhi IRPhi;
struct BlockPhiInfo {
    IRPhi *phis;
    size_t num_phis;
    size_t cap_phis;
};typedef struct BlockPhiInfo BlockPhiInfo;
BlockPhiInfo *mem2reg_place_phis(
    const CFG *cfg,
    const DomTree *dt,
    const int *alloca_slots,
    size_t num_alloca,
    const char **block_stores,
    int *next_value_id);
void block_phi_info_free(BlockPhiInfo *bp, size_t num_blocks);
void mem2reg_rename(
    IRFunction *fn,
    const CFG *cfg,
    const DomTree *dt,
    const int *alloca_slots,
    size_t num_alloca,
    BlockPhiInfo *block_phi_info,
    char **dead,
    int want_debug);
void mem2reg_writeback(
    IRFunction *fn,
    const CFG *cfg,
    BlockPhiInfo *block_phi_info,
    char *dead,
    int want_debug);
int opt_mem2reg(IRFunction *fn, int want_debug);
int scalar_constfold(IRFunction *fn);
int scalar_dce(IRFunction *fn);
int scalar_peephole(IRFunction *fn);
void scalar_renumber(IRFunction *fn);
void scalar_cleanup(IRFunction *fn);
enum Reg {
    REG_RAX = 0,
    REG_RCX = 1,
    REG_RDX = 2,
    REG_RBX = 3,
    REG_RSP = 4,
    REG_RBP = 5,
    REG_RSI = 6,
    REG_RDI = 7,
    REG_R8 = 8,
    REG_R9 = 9,
    REG_R10 = 10,
    REG_R11 = 11,
    REG_R12 = 12,
    REG_R13 = 13,
    REG_R14 = 14,
    REG_R15 = 15,
    REG_NONE = -1,
};typedef enum Reg Reg;
static const int ALLOCATABLE_REGS[9] = {
    REG_RSI, REG_RDI,
    REG_R8, REG_R9, REG_R10, REG_R11,
    REG_RBX, REG_R12, REG_R13
};
static const int XMM_ALLOCATABLE_REGS[14] = {
     0, 1, 2, 3, 4, 5, 6, 7,
     8, 9, 10, 11, 12, 13
};
struct RAResult {
    int *reg;
    int *spill_slot;
    int num_spill_slots;
    int num_values;
    int stack_size;
};typedef struct RAResult RAResult;
RAResult *reg_alloc(const IRFunction *fn);
RAResult *reg_alloc_xmm(const IRFunction *fn);
void ra_result_free(RAResult *ra);
typedef struct FILE FILE;
typedef long fpos_t;
static void pin_scalar_allocas(IRFunction *fn) {
    for (size_t i = 0; i < fn->insts.len; i++) {
        IRInst *inst = &fn->insts.data[i];
        if (inst->op != IR_ALLOCA) continue;
        if (inst->alloca_bytes > 0) continue;
        int w = inst->width > 0 ? inst->width : 4;
        if (w < 8 && !inst->is_float) {
            inst->alloca_bytes = w;
        } else {
            inst->alloca_bytes = w;
        }
        if (inst->alloca_bytes < 1) inst->alloca_bytes = 8;
    }
}
static void extract_markers(IRFunction *fn, ExtractedMarker **out, int *nout) {
    *out = ((void*)0);
    *nout = 0;
    int pos = 0;
    size_t w = 0;
    for (size_t i = 0; i < fn->insts.len; i++) {
        IRInst *in = &fn->insts.data[i];
        if (in->op != IR_DBG_VALUE) {
            fn->insts.data[w++] = *in;
            pos++;
            continue;
        }
        *out = xrealloc(*out, ((size_t)*nout + 1) * sizeof(ExtractedMarker));
        (*out)[*nout].var = (int)in->imm;
        (*out)[*nout].value = in->a;
        (*out)[*nout].pos = pos;
        (*nout)++;
    }
    fn->insts.len = w;
}
static void reinsert_markers(IRFunction *fn, ExtractedMarker *markers, int nmarkers) {
    IRInstArray out;
    out.len = 0;
    out.cap = fn->insts.len + (size_t)nmarkers;
    out.data = xmalloc(out.cap * sizeof(IRInst));
    int mi = 0;
    int real = 0;
    for (size_t i = 0; i < fn->insts.len; i++) {
        while (mi < nmarkers && markers[mi].pos == real) {
            IRInst marker;
            runtime.memset(&marker, 0, sizeof(marker));
            marker.op = IR_DBG_VALUE;
            marker.dst = -1;
            marker.imm = markers[mi].var;
            marker.a = markers[mi].value;
            if (out.len >= out.cap) { out.cap *= 2; out.data = xrealloc(out.data, out.cap * sizeof(IRInst)); }
            out.data[out.len++] = marker;
            mi++;
        }
        if (out.len >= out.cap) { out.cap *= 2; out.data = xrealloc(out.data, out.cap * sizeof(IRInst)); }
        out.data[out.len++] = fn->insts.data[i];
        real++;
    }
    while (mi < nmarkers && markers[mi].pos == real) {
        IRInst marker;
        runtime.memset(&marker, 0, sizeof(marker));
        marker.op = IR_DBG_VALUE;
        marker.dst = -1;
        marker.imm = markers[mi].var;
        marker.a = markers[mi].value;
        if (out.len >= out.cap) { out.cap *= 2; out.data = xrealloc(out.data, out.cap * sizeof(IRInst)); }
        out.data[out.len++] = marker;
        mi++;
    }
    runtime.free(fn->insts.data);
    fn->insts = out;
}
void opt(IRModule *ir, int opt_level, int want_debug) {
    for (size_t i = 0; i < ir->functions.len; i++) {
        IRFunction *fn = &ir->functions.data[i];
        if (opt_level == 0)
            pin_scalar_allocas(fn);
        else
            opt_mem2reg(fn, want_debug);
        if (want_debug) {
            scalar_cleanup(fn);
            ExtractedMarker *markers = ((void*)0);
            int nmarkers = 0;
            extract_markers(fn, &markers, &nmarkers);
            fn->ra = reg_alloc(fn);
            fn->ra_xmm = reg_alloc_xmm(fn);
            if (nmarkers > 0)
                reinsert_markers(fn, markers, nmarkers);
            runtime.free(markers);
        } else {
            scalar_cleanup(fn);
            fn->ra = reg_alloc(fn);
            fn->ra_xmm = reg_alloc_xmm(fn);
        }
    }
}
