package main;
import runtime;
/* Generated by v0/translate.py from src/ — do not edit. */

static int __fakecc_ctzll(unsigned long _v){int c;for(c=0;!(_v&1);c++)_v>>=1;return c;}
static void __fakecc_va_copy(void *dst, void *src){
    char *d = (char*)dst; char *s = (char*)src;
    for(int i = 0; i < 24; i++) d[i] = s[i];
}

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef long ssize_t;
typedef long intptr_t;
typedef unsigned long uintptr_t;
struct SourceLoc {
    const char *file;
    int line;
    int col;
};typedef struct SourceLoc SourceLoc;
struct Buffer {
    char *data;
    size_t len;
    size_t cap;
};typedef struct Buffer Buffer;
void buffer_init(Buffer *b);
void buffer_free(Buffer *b);
void buffer_append(Buffer *b, const char *s, size_t n);
void buffer_appendf(Buffer *b, const char *fmt, ...);
char *xstrdup(const char *s);
void *xmalloc(size_t n);
void *xrealloc(void *p, size_t n);
void die_at(const char *file, int line, int col, const char *fmt, ...);
enum TokenKind {
    TK_KW_PACKAGE,
    TK_KW_IMPORT,
    TK_KW_VOID,
    TK_KW_INT,
    TK_KW_FLOAT,
    TK_KW_DOUBLE,
    TK_KW_CHAR,
    TK_KW_SHORT,
    TK_KW_LONG,
    TK_KW_SIGNED,
    TK_KW_UNSIGNED,
    TK_KW_SIZEOF,
    TK_KW_RETURN,
    TK_KW_IF,
    TK_KW_ELSE,
    TK_KW_WHILE,
    TK_KW_FOR,
    TK_KW_GOTO,
    TK_KW_SWITCH,
    TK_KW_CASE,
    TK_KW_DEFAULT,
    TK_KW_BREAK,
    TK_KW_CONTINUE,
    TK_KW_CONST,
    TK_KW_UNION,
    TK_KW_DO,
    TK_KW_ENUM,
    TK_KW_STRUCT,
    TK_KW_TYPEDEF,
    TK_KW_STATIC,
    TK_KW_EXTERN,
    TK_KW_BOOL,
    TK_KW_VOLATILE,
    TK_KW_RESTRICT,
    TK_KW_INLINE,
    TK_KW_ALIGNOF,
    TK_KW_LONG_DOUBLE,
    TK_IDENT,
    TK_INT_LITERAL,
    TK_FLOAT_LITERAL,
    TK_CHAR_LITERAL,
    TK_STRING_LITERAL,
    TK_LPAREN,
    TK_RPAREN,
    TK_LBRACE,
    TK_RBRACE,
    TK_LBRACKET,
    TK_RBRACKET,
    TK_SEMICOLON,
    TK_COMMA,
    TK_PLUS,
    TK_MINUS,
    TK_STAR,
    TK_SLASH,
    TK_PERCENT,
    TK_AMP,
    TK_ANDAND,
    TK_OROR,
    TK_BITOR,
    TK_XOR,
    TK_TILDE,
    TK_NOT,
    TK_SHL,
    TK_SHR,
    TK_SHL_EQ,
    TK_SHR_EQ,
    TK_PLUS_EQ,
    TK_MINUS_EQ,
    TK_STAR_EQ,
    TK_SLASH_EQ,
    TK_PERCENT_EQ,
    TK_AMP_EQ,
    TK_BITOR_EQ,
    TK_XOR_EQ,
    TK_INC,
    TK_DEC,
    TK_QUESTION,
    TK_COLON,
    TK_DOT,
    TK_ELLIPSIS,
    TK_ARROW,
    TK_ASSIGN,
    TK_EQ,
    TK_NE,
    TK_LT,
    TK_LE,
    TK_GT,
    TK_GE,
    TK_EOF,
};typedef enum TokenKind TokenKind;
struct Token {
    TokenKind kind;
    char *text;
    SourceLoc loc;
};typedef struct Token Token;
struct TokenArray {
    Token *data;
    size_t len;
    size_t cap;
};typedef struct TokenArray TokenArray;
void token_array_init(TokenArray *a);
void token_array_free(TokenArray *a);
void token_array_push(TokenArray *a, Token t);
enum TypeKind {
    TY_VOID,
    TY_INT,
    TY_FLOAT,
    TY_PTR,
    TY_ARRAY,
    TY_STRUCT,
    TY_FUNC,
};typedef enum TypeKind TypeKind;
typedef struct Type Type;
struct Type {
    TypeKind kind;
    int width;
    int is_unsigned;
    unsigned is_const : 1;
    unsigned is_volatile : 1;
    unsigned is_restrict : 1;
    unsigned is_bool : 1;
    Type *pointee;
    Type *elem_type;
    int length;
    char *tag;
    Type *func_ret;
    Type *func_params;
    int func_nparams;
};
static inline Type type_make_int(int width, int is_unsigned) {
    Type t; t.kind = TY_INT; t.width = width; t.is_unsigned = is_unsigned;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; return t;
}
static inline Type type_make_bool(void) {
    Type t = type_make_int(1, 1);
    t.is_bool = 1;
    return t;
}
static inline Type type_default_int(void) { return type_make_int(4, 0); }
static inline Type type_make_float(int width) {
    Type t; t.kind = TY_FLOAT; t.width = width; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; return t;
}
static inline Type type_make_void(void) {
    Type t; t.kind = TY_VOID; t.width = 0; t.is_unsigned = 0;
    t.is_const = 0; t.is_volatile = 0; t.is_restrict = 0; t.is_bool = 0;
    t.pointee = ((void*)0); t.elem_type = ((void*)0); t.length = 0; t.tag = ((void*)0);
    t.func_ret = ((void*)0); t.func_params = ((void*)0); t.func_nparams = 0; return t;
}
Type type_clone(Type t);
void type_free(Type *t);
int type_size(Type t);
int type_align(Type t);
enum SysVRegClass {
    SYSV_CLS_INTEGER = 1,
    SYSV_CLS_SSE = 2
};typedef enum SysVRegClass SysVRegClass;
int sysv_classify_agg(Type t, SysVRegClass cls[2]);
Type type_make_ptr(Type pointee);
Type type_make_array(Type elem, int length);
Type type_make_struct(const char *tag, int size);
Type type_make_func(Type ret, Type * *params, int nparams);
Type type_decay(Type t);
int type_is_ptr_or_array(Type t);
Type type_pointee_or_elem(Type t);
int type_funcs_equal(Type a, Type b);
enum ExprKind {
    EX_INT_LIT,
    EX_BINOP,
    EX_UNARY,
    EX_VAR,
    EX_ASSIGN,
    EX_CALL,
    EX_STR,
    EX_ADDR,
    EX_DEREF,
    EX_INDEX,
    EX_MEMBER,
    EX_CAST,
    EX_SIZEOF_TYPE,
    EX_SIZEOF_EXPR,
    EX_ALIGNOF_TYPE,
    EX_TERNARY,
    EX_INC_DEC,
    EX_COMPOUND_ASSIGN,
    EX_COMMA,
    EX_INIT_LIST,
    EX_FLOAT_LIT,
    EX_COMPOUND_LITERAL,
};typedef enum ExprKind ExprKind;
enum BinOp {
    BOP_ADD,
    BOP_SUB,
    BOP_MUL,
    BOP_DIV,
    BOP_MOD,
    BOP_EQ,
    BOP_NE,
    BOP_LT,
    BOP_LE,
    BOP_GT,
    BOP_GE,
    BOP_AND,
    BOP_OR,
    BOP_BITAND,
    BOP_BITOR,
    BOP_BITXOR,
    BOP_SHL,
    BOP_SHR,
};typedef enum BinOp BinOp;
enum UnaryOp {
    UOP_NEG,
    UOP_POS,
    UOP_BITNOT,
    UOP_NOT,
};typedef enum UnaryOp UnaryOp;
typedef struct Expr Expr;
int fold_const_int(const Expr *e, long long *out);
struct ExprArray {
    Expr **data;
    size_t len;
    size_t cap;
};typedef struct ExprArray ExprArray;
union __anon_u_1 {
        long long int_val;
        struct { BinOp op; Expr *l, *r; } bin;
        struct { UnaryOp op; Expr *operand; } un;
        struct { char *name; char *pkg; } var;
        struct { Expr *lvalue; Expr *rvalue; } assign;
        struct { Expr *callee; ExprArray args; } call;
        struct { char *bytes; int len; } str;
        struct { Expr *operand; } addr;
        struct { Expr *operand; } deref;
        struct { Expr *array; Expr *index; } idx;
        struct { Expr *obj; char *name; } member;
        struct { Type target; Expr *operand; } cast;
        struct { Type target; } sizeof_t;
        struct { Expr *operand; } sizeof_e;
        struct { Type target; } alignof_t;
        struct { Expr *cond; Expr *then; Expr *else_; } tern;
        struct { Expr *operand; int is_inc; int is_prefix; } incdec;
        struct { Expr *lvalue; Expr *rvalue; BinOp op; } comp;
        struct { Expr *lhs; Expr *rhs; } comma;
        struct { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; } init_list;
        char *float_text;
        struct { Type target_type; Expr *init; } compound;
    };struct Expr {union __anon_u_3 {struct __anon_bin_4 { BinOp op; Expr *l, *r; };
struct __anon_un_5 { UnaryOp op; Expr *operand; };
struct __anon_var_6 { char *name; char *pkg; };
struct __anon_assign_7 { Expr *lvalue; Expr *rvalue; };
struct __anon_call_8 { Expr *callee; ExprArray args; };
struct __anon_str_9 { char *bytes; int len; };
struct __anon_addr_10 { Expr *operand; };
struct __anon_deref_11 { Expr *operand; };
struct __anon_idx_12 { Expr *array; Expr *index; };
struct __anon_member_13 { Expr *obj; char *name; };
struct __anon_cast_14 { Type target; Expr *operand; };
struct __anon_sizeof_t_15 { Type target; };
struct __anon_sizeof_e_16 { Expr *operand; };
struct __anon_alignof_t_17 { Type target; };
struct __anon_tern_18 { Expr *cond; Expr *then; Expr *else_; };
struct __anon_incdec_19 { Expr *operand; int is_inc; int is_prefix; };
struct __anon_comp_20 { Expr *lvalue; Expr *rvalue; BinOp op; };
struct __anon_comma_21 { Expr *lhs; Expr *rhs; };
struct __anon_init_list_22 { Expr **elements; int num_elements; int *desig_kind; int *desig_index; char **desig_member; };
struct __anon_compound_23 { Type target_type; Expr *init; };

        long long int_val;
        struct __anon_bin_4 bin;
        struct __anon_un_5 un;
        struct __anon_var_6 var;
        struct __anon_assign_7 assign;
        struct __anon_call_8 call;
        struct __anon_str_9 str;
        struct __anon_addr_10 addr;
        struct __anon_deref_11 deref;
        struct __anon_idx_12 idx;
        struct __anon_member_13 member;
        struct __anon_cast_14 cast;
        struct __anon_sizeof_t_15 sizeof_t;
        struct __anon_sizeof_e_16 sizeof_e;
        struct __anon_alignof_t_17 alignof_t;
        struct __anon_tern_18 tern;
        struct __anon_incdec_19 incdec;
        struct __anon_comp_20 comp;
        struct __anon_comma_21 comma;
        struct __anon_init_list_22 init_list;
        char *float_text;
        struct __anon_compound_23 compound;
    };

    ExprKind kind;
    SourceLoc loc;
    Type type;
    Type va_arg_type;
    union __anon_u_3 u;
};
Expr *expr_new_int(long long v, SourceLoc loc);
Expr *expr_new_int_typed(long long v, int width, int is_unsigned, SourceLoc loc);
Expr *expr_new_binop(BinOp op, Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_unary(UnaryOp op, Expr *operand, SourceLoc loc);
Expr *expr_new_var(const char *name, SourceLoc loc);
Expr *expr_new_var_qual(const char *pkg, const char *name, SourceLoc loc);
Expr *expr_new_assign(Expr *lvalue, Expr *rvalue, SourceLoc loc);
Expr *expr_new_call(Expr *callee, SourceLoc loc);
Expr *expr_new_str(const char *bytes, int len, SourceLoc loc);
Expr *expr_new_addr(Expr *operand, SourceLoc loc);
Expr *expr_new_deref(Expr *operand, SourceLoc loc);
Expr *expr_new_index(Expr *array, Expr *index, SourceLoc loc);
Expr *expr_new_member(Expr *obj, const char *name, SourceLoc loc);
Expr *expr_new_cast(Type target, Expr *operand, SourceLoc loc);
Expr *expr_new_sizeof_type(Type t, SourceLoc loc);
Expr *expr_new_sizeof_expr(Expr *operand, SourceLoc loc);
Expr *expr_new_alignof_type(Type t, SourceLoc loc);
Expr *expr_new_ternary(Expr *cond, Expr *then, Expr *else_, SourceLoc loc);
Expr *expr_new_inc_dec(Expr *operand, int is_inc, int is_prefix, SourceLoc loc);
Expr *expr_new_compound_assign(Expr *lvalue, Expr *rvalue, BinOp op, SourceLoc loc);
Expr *expr_new_comma(Expr *l, Expr *r, SourceLoc loc);
Expr *expr_new_init_list(Expr **elements, int num_elements, SourceLoc loc);
Expr *expr_new_float_lit(const char *text, int width, SourceLoc loc);
Expr *expr_new_compound_literal(Type target_type, Expr *init, SourceLoc loc);
void expr_call_push_arg(Expr *e, Expr *arg);
void expr_call_set_callee(Expr *e, Expr *callee);
void expr_free(Expr *e);
void expr_set_type(Expr *e, Type t);
enum StmtKind {
    ST_DECL,
    ST_EXPR,
    ST_RETURN,
    ST_IF,
    ST_WHILE,
    ST_FOR,
    ST_BREAK,
    ST_CONTINUE,
    ST_BLOCK,
    ST_DO_WHILE,
    ST_GOTO,
    ST_LABEL,
    ST_SWITCH,
};typedef enum StmtKind StmtKind;
typedef struct Stmt Stmt;
struct StmtArray {
    Stmt *data;
    size_t len;
    size_t cap;
};typedef struct StmtArray StmtArray;
struct SwitchCase {
    int is_default;
    int value;
    StmtArray stmts;
};typedef struct SwitchCase SwitchCase;
union __anon_u_2 {
        struct { char *name; Type type; Expr *init; int storage_class; } decl;
        Expr *expr;
        Expr *value;
        struct { Expr *cond; Stmt *then_s; Stmt *else_s; } if_s;
        struct { Expr *cond; Stmt *body; } while_s;
        struct { Expr *cond; Stmt *body; } do_s;
        struct { Stmt *init; Expr *cond; Expr *step; Stmt *body; } for_s;
        StmtArray block;
        struct { char *target; } goto_s;
        struct { char *name; Stmt *stmt; } label_s;
        struct { Expr *cond; SwitchCase *cases; int num_cases; int cap_cases; } switch_s;
    };struct Stmt {union __anon_u_24 {struct __anon_decl_25 { char *name; Type type; Expr *init; int storage_class; };
struct __anon_if_s_26 { Expr *cond; Stmt *then_s; Stmt *else_s; };
struct __anon_while_s_27 { Expr *cond; Stmt *body; };
struct __anon_do_s_28 { Expr *cond; Stmt *body; };
struct __anon_for_s_29 { Stmt *init; Expr *cond; Expr *step; Stmt *body; };
struct __anon_goto_s_30 { char *target; };
struct __anon_label_s_31 { char *name; Stmt *stmt; };
struct __anon_switch_s_32 { Expr *cond; SwitchCase *cases; int num_cases; int cap_cases; };

        struct __anon_decl_25 decl;
        Expr *expr;
        Expr *value;
        struct __anon_if_s_26 if_s;
        struct __anon_while_s_27 while_s;
        struct __anon_do_s_28 do_s;
        struct __anon_for_s_29 for_s;
        StmtArray block;
        struct __anon_goto_s_30 goto_s;
        struct __anon_label_s_31 label_s;
        struct __anon_switch_s_32 switch_s;
    };

    StmtKind kind;
    SourceLoc loc;
    union __anon_u_24 u;
};
void stmt_array_init(StmtArray *a);
void stmt_array_push(StmtArray *a, Stmt s);
void stmt_array_free(StmtArray *a);
void stmt_free(Stmt *s);
Stmt *stmt_alloc(void);
void stmt_free_ptr(Stmt *s);
void switch_push_case(Stmt *s, int is_default, int value);
struct Param {
    char *name;
    Type type;
    SourceLoc loc;
};typedef struct Param Param;
struct ParamArray {
    Param *data;
    size_t len;
    size_t cap;
};typedef struct ParamArray ParamArray;
void param_array_init(ParamArray *a);
void param_array_push(ParamArray *a, const char *name, Type type, SourceLoc loc);
void param_array_free(ParamArray *a);
struct FunctionDecl {
    char *name;
    Type ret_type;
    ParamArray params;
    StmtArray body;
    SourceLoc loc;
    int is_variadic;
    int is_extern;
    int is_static;
};typedef struct FunctionDecl FunctionDecl;
struct PackageDecl {
    char *name;
    SourceLoc loc;
};typedef struct PackageDecl PackageDecl;
struct ImportDecl {
    char *name;
    SourceLoc loc;
};typedef struct ImportDecl ImportDecl;
struct ImportArray {
    ImportDecl *data;
    size_t len;
    size_t cap;
};typedef struct ImportArray ImportArray;
void import_array_init(ImportArray *a);
void import_array_push(ImportArray *a, const char *name, SourceLoc loc);
void import_array_free(ImportArray *a);
struct StructMember {
    char *name;
    Type type;
    int offset;
    int bit_width;
    int bit_offset;
};typedef struct StructMember StructMember;
struct StructDef {
    char *tag;
    int is_union;
    StructMember *members;
    int num_members;
    int cap_members;
    int size;
    int align;
    SourceLoc loc;
    Type *canonical_type;
    int bf_unit_type;
    int bf_unit_used;
    int bf_unit_offset;
};typedef struct StructDef StructDef;
struct StructRegistry {
    StructDef *data;
    size_t len;
    size_t cap;
};typedef struct StructRegistry StructRegistry;
void struct_registry_init(StructRegistry *r);
void struct_registry_free(StructRegistry *r);
StructDef *struct_registry_add(StructRegistry *r, const char *tag, SourceLoc loc);
StructDef *struct_registry_find(StructRegistry *r, const char *tag);
const StructDef *struct_registry_find_c(const StructRegistry *r, const char *tag);
void struct_def_push_member(StructDef *sd, const char *name, Type ty, int bit_width);
void struct_def_finish(StructDef *sd);
void struct_def_fixup_self_types(StructDef *sd);
struct FunctionArray {
    FunctionDecl *data;
    size_t len;
    size_t cap;
};typedef struct FunctionArray FunctionArray;
struct EnumConstant {
    char *name;
    int value;
};typedef struct EnumConstant EnumConstant;
struct EnumDef {
    char *tag;
    EnumConstant *constants;
    int num_constants;
    int cap_constants;
    SourceLoc loc;
};typedef struct EnumDef EnumDef;
struct EnumRegistry {
    EnumDef *data;
    size_t len;
    size_t cap;
};typedef struct EnumRegistry EnumRegistry;
void enum_registry_init(EnumRegistry *r);
void enum_registry_free(EnumRegistry *r);
EnumDef *enum_registry_add(EnumRegistry *r, const char *tag, SourceLoc loc);
EnumDef *enum_registry_find(EnumRegistry *r, const char *tag);
int enum_def_push_constant(EnumDef *ed, const char *name, int has_value,
                            int value, SourceLoc loc);
const EnumConstant *enum_registry_find_constant(const EnumRegistry *r,
                                                const char *name);
struct TypedefEntry {
    char *name;
    Type type;
};typedef struct TypedefEntry TypedefEntry;
struct TypedefRegistry {
    TypedefEntry *data;
    size_t len;
    size_t cap;
};typedef struct TypedefRegistry TypedefRegistry;
void typedef_registry_init(TypedefRegistry *r);
void typedef_registry_free(TypedefRegistry *r);
TypedefEntry *typedef_registry_add(TypedefRegistry *r, const char *name, Type type);
const Type *typedef_registry_find(const TypedefRegistry *r, const char *name);
struct TranslationUnit {
    PackageDecl package;
    ImportArray imports;
    StmtArray globals;
    FunctionArray functions;
    StructRegistry structs;
    EnumRegistry enums;
    TypedefRegistry typedefs;
};typedef struct TranslationUnit TranslationUnit;
void tu_init(TranslationUnit *tu);
void tu_free(TranslationUnit *tu);
struct PkgContext;
void sema_check(const TranslationUnit *tu, int require_main);
void sema_check_in_pkg(const TranslationUnit *tu, int require_main,
                       struct PkgContext *ctx);
typedef struct Package Package;
typedef struct PkgContext PkgContext;
struct PkgFuncExport {
    char *name;
    Type ret_type;
    Type param_types[16];
    int arity;
    int is_variadic;
    int is_extern;
    SourceLoc loc;
    TranslationUnit *tu;
};typedef struct PkgFuncExport PkgFuncExport;
struct PkgGlobalExport {
    char *name;
    Type type;
    int is_extern;
    SourceLoc loc;
    TranslationUnit *tu;
};typedef struct PkgGlobalExport PkgGlobalExport;
struct Package {
    char *name;
    char *dir;
    TranslationUnit *files;
    size_t nfiles;
    int owns_files;
    PkgFuncExport *funcs;
    size_t nfuncs;
    PkgGlobalExport *globals;
    size_t nglobals;
    TypedefRegistry typedefs;
    StructRegistry structs;
    EnumRegistry enums;
};
struct PkgContext {
    char **search_paths;
    int npaths;
    Package **pkgs;
    size_t npkgs;
    size_t cap_pkgs;
    char **loading;
    size_t nloading;
    size_t cap_loading;
};
void pkg_ctx_init(PkgContext *ctx);
void pkg_ctx_free(PkgContext *ctx);
void pkg_ctx_add_path(PkgContext *ctx, const char *dir);
Package *pkg_load(PkgContext *ctx, const char *name, SourceLoc loc);
Package *pkg_register_tus(PkgContext *ctx, const char *name,
                          TranslationUnit **tus, size_t ntus);
Package *pkg_find(const PkgContext *ctx, const char *name);
const PkgFuncExport *pkg_find_func(const Package *pkg, const char *name);
const PkgGlobalExport *pkg_find_global(const Package *pkg, const char *name);
const Type *pkg_find_typedef(const Package *pkg, const char *name);
const StructDef *pkg_find_struct(const Package *pkg, const char *name);
const EnumDef *pkg_find_enum(const Package *pkg, const char *name);
const EnumConstant *pkg_find_enum_const(const Package *pkg, const char *name);
void pkg_clone_struct_into(StructRegistry *dst, const StructDef *src);
void pkg_import_typedef(TranslationUnit *tu, const char *name, const Type *src,
                        const Package *pkg);
const char *pkg_suggest_export(const PkgContext *ctx, const char *name);
typedef struct FILE FILE;
typedef long fpos_t;
static const StructRegistry *g_sema_structs = ((void*)0);
static PkgContext *g_sema_pkg = ((void*)0);
static const TranslationUnit *g_sema_tu = ((void*)0);
static Type g_sema_ret_type;
struct FunSig {
    const char *name;
    int arity;
    int is_variadic;
    int is_external;
    Type ret_type;
    Type param_types[16];
    SourceLoc loc;
};typedef struct FunSig FunSig;
struct FunTable {
    FunSig *data;
    size_t len;
    size_t cap;
};typedef struct FunTable FunTable;
static void ftab_init(FunTable *t) { t->data = ((void*)0); t->len = 0; t->cap = 0; }
static void ftab_free(FunTable *t) { runtime.free(t->data); t->data = ((void*)0); t->len = 0; t->cap = 0; }
static void ftab_push(FunTable *t, const FunctionDecl *fn) {
    if (t->len >= t->cap) {
        t->cap = t->cap ? t->cap * 2 : 8;
        t->data = runtime.realloc(t->data, t->cap * sizeof(FunSig));
        if (!t->data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    }
    FunSig *s = &t->data[t->len++];
    s->name = fn->name;
    s->arity = (int)fn->params.len;
    s->is_variadic = fn->is_variadic;
    s->is_external = fn->is_extern;
    s->ret_type = fn->ret_type;
    s->loc = fn->loc;
    for (int i = 0; i < s->arity && i < 16; i++)
        s->param_types[i] = fn->params.data[i].type;
}
static const FunSig *ftab_find(const FunTable *t, const char *name) {
    for (size_t i = 0; i < t->len; i++)
        if (runtime.strcmp(t->data[i].name, name) == 0) return &t->data[i];
    return ((void*)0);
}
static int tu_imports(const TranslationUnit *tu, const char *name) {
    for (size_t i = 0; i < tu->imports.len; i++)
        if (runtime.strcmp(tu->imports.data[i].name, name) == 0) return 1;
    return 0;
}
static void ftab_push_export(FunTable *t, const PkgFuncExport *ex) {
    if (ftab_find(t, ex->name)) return;
    if (t->len >= t->cap) {
        t->cap = t->cap ? t->cap * 2 : 8;
        t->data = runtime.realloc(t->data, t->cap * sizeof(FunSig));
        if (!t->data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    }
    FunSig *s = &t->data[t->len++];
    s->name = ex->name;
    s->arity = ex->arity;
    s->is_variadic = ex->is_variadic;
    s->is_external = 1;
    s->ret_type = ex->ret_type;
    s->loc = ex->loc;
    for (int i = 0; i < s->arity && i < 16; i++)
        s->param_types[i] = ex->param_types[i];
}
static void tu_ensure_extern_func(TranslationUnit *tu, const PkgFuncExport *ex) {
    for (size_t i = 0; i < tu->functions.len; i++)
        if (runtime.strcmp(tu->functions.data[i].name, ex->name) == 0)
            return;
    if (tu->functions.len >= tu->functions.cap) {
        size_t nc = tu->functions.cap ? tu->functions.cap * 2 : 4;
        tu->functions.data = runtime.realloc(tu->functions.data,
                                     nc * sizeof(FunctionDecl));
        if (!tu->functions.data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
        tu->functions.cap = nc;
    }
    FunctionDecl *fn = &tu->functions.data[tu->functions.len++];
    runtime.memset(fn, 0, sizeof(*fn));
    fn->name = xstrdup(ex->name);
    fn->ret_type = type_clone(ex->ret_type);
    param_array_init(&fn->params);
    for (int i = 0; i < ex->arity && i < 16; i++)
        param_array_push(&fn->params, "", type_clone(ex->param_types[i]),
                         ex->loc);
    fn->loc = ex->loc;
    fn->is_variadic = ex->is_variadic;
    fn->is_extern = 1;
    fn->is_static = 0;
}
static void import_pkg_funcs(TranslationUnit *tu, FunTable *ft, Package *pkg) {
    if (!pkg) return;
    for (size_t i = 0; i < pkg->nfuncs; i++) {
        ftab_push_export(ft, &pkg->funcs[i]);
        tu_ensure_extern_func(tu, &pkg->funcs[i]);
    }
}
static void tu_ensure_extern_global(TranslationUnit *tu, const PkgGlobalExport *ex) {
    for (size_t i = 0; i < tu->globals.len; i++) {
        Stmt *s = &tu->globals.data[i];
        if (s->kind == ST_DECL && s->u.decl.name
            && runtime.strcmp(s->u.decl.name, ex->name) == 0)
            return;
    }
    Stmt s;
    runtime.memset(&s, 0, sizeof(s));
    s.kind = ST_DECL;
    s.loc = ex->loc;
    s.u.decl.name = xstrdup(ex->name);
    s.u.decl.type = type_clone(ex->type);
    s.u.decl.init = ((void*)0);
    s.u.decl.storage_class = 2;
    stmt_array_push(&tu->globals, s);
}
static void import_pkg_globals(TranslationUnit *tu, Package *pkg) {
    if (!pkg) return;
    for (size_t i = 0; i < pkg->nglobals; i++)
        tu_ensure_extern_global(tu, &pkg->globals[i]);
}
static int pkg_resolve_sym(const char *pkg_name, const char *sym,
                           const PkgFuncExport **out_func,
                           const PkgGlobalExport **out_global) {
    *out_func = ((void*)0);
    *out_global = ((void*)0);
    if (!g_sema_pkg) return 0;
    Package *pkg = pkg_find(g_sema_pkg, pkg_name);
    if (!pkg) return 0;
    const PkgFuncExport *f = pkg_find_func(pkg, sym);
    if (f) { *out_func = f; return 1; }
    const PkgGlobalExport *g = pkg_find_global(pkg, sym);
    if (g) { *out_global = g; return 1; }
    return 0;
}
static int is_va_list_type(const Type *t) {
    return t->kind == TY_STRUCT && t->tag && runtime.strcmp(t->tag, "__va_list_tag") == 0;
}
struct LabelSet {
    char **names;
    size_t len;
    size_t cap;
};typedef struct LabelSet LabelSet;
static void labelset_init(LabelSet *ls) { ls->names = ((void*)0); ls->len = 0; ls->cap = 0; }
static void labelset_free(LabelSet *ls) {
    for (size_t i = 0; i < ls->len; i++) runtime.free(ls->names[i]);
    runtime.free(ls->names);
    ls->names = ((void*)0); ls->len = 0; ls->cap = 0;
}
static void labelset_add(LabelSet *ls, const char *name) {
    if (ls->len >= ls->cap) {
        ls->cap = ls->cap ? ls->cap * 2 : 8;
        ls->names = runtime.realloc(ls->names, ls->cap * sizeof(char *));
        if (!ls->names) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    }
    ls->names[ls->len++] = xstrdup(name);
}
static int labelset_has(const LabelSet *ls, const char *name) {
    for (size_t i = 0; i < ls->len; i++)
        if (runtime.strcmp(ls->names[i], name) == 0) return 1;
    return 0;
}
static void collect_labels(LabelSet *ls, const Stmt *s) {
    if (!s) return;
    switch (s->kind) {
    case ST_LABEL:
        labelset_add(ls, s->u.label_s.name);
        collect_labels(ls, s->u.label_s.stmt);
        break;
    case ST_IF:
        collect_labels(ls, s->u.if_s.then_s);
        if (s->u.if_s.else_s) collect_labels(ls, s->u.if_s.else_s);
        break;
    case ST_WHILE:
        collect_labels(ls, s->u.while_s.body);
        break;
    case ST_DO_WHILE:
        collect_labels(ls, s->u.do_s.body);
        break;
    case ST_FOR:
        if (s->u.for_s.init) collect_labels(ls, s->u.for_s.init);
        collect_labels(ls, s->u.for_s.body);
        break;
    case ST_BLOCK:
        for (size_t i = 0; i < s->u.block.len; i++)
            collect_labels(ls, &s->u.block.data[i]);
        break;
    default:
        break;
    }
}
struct Sym {
    char *name;
    Type type;
    SourceLoc loc;
};typedef struct Sym Sym;
struct SymTable {
    Sym *data;
    size_t len;
    size_t cap;
};typedef struct SymTable SymTable;
static void symtable_init(SymTable *st) { st->data = ((void*)0); st->len = 0; st->cap = 0; }
static void symtable_free(SymTable *st) {
    for (size_t i = 0; i < st->len; i++) {
        runtime.free(st->data[i].name);
        type_free(&st->data[i].type);
    }
    runtime.free(st->data);
    st->data = ((void*)0); st->len = 0; st->cap = 0;
}
static void symtable_push(SymTable *st, const char *name, Type type, SourceLoc loc) {
    if (st->len >= st->cap) {
        st->cap = st->cap ? st->cap * 2 : 8;
        st->data = runtime.realloc(st->data, st->cap * sizeof(Sym));
        if (!st->data) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
    }
    st->data[st->len].name = name ? xstrdup(name) : ((void*)0);
    st->data[st->len].type = type_clone(type);
    st->data[st->len].loc = loc;
    st->len++;
}
static size_t symtable_enter_scope(SymTable *st) { return st->len; }
static void symtable_leave_scope(SymTable *st, size_t mark) {
    while (st->len > mark) {
        st->len--;
        runtime.free(st->data[st->len].name);
        type_free(&st->data[st->len].type);
    }
}
static const Sym *symtable_find(const SymTable *st, const char *name) {
    for (size_t i = st->len; i > 0; i--) {
        const Sym *e = &st->data[i - 1];
        if (e->name && runtime.strcmp(e->name, name) == 0) return e;
    }
    return ((void*)0);
}
static int symtable_has_since(const SymTable *st, const char *name, size_t mark) {
    for (size_t i = mark; i < st->len; i++)
        if (st->data[i].name && runtime.strcmp(st->data[i].name, name) == 0) return 1;
    return 0;
}
static int type_rank(Type t) {
    if (t.kind == TY_FLOAT) return 100 + t.width;
    if (t.kind == TY_PTR) return 50;
    return t.width;
}
static Type integer_promote(Type t) {
    if (t.kind == TY_FLOAT) return t;
    if (t.width < 4) return type_make_int(4, 0);
    return t;
}
static Type usual_arith_conv(Type a, Type b) {
    a = integer_promote(a);
    b = integer_promote(b);
    if (a.kind == TY_FLOAT && b.kind == TY_FLOAT)
        return type_rank(a) >= type_rank(b) ? a : b;
    if (a.kind == TY_FLOAT) return a;
    if (b.kind == TY_FLOAT) return b;
    if (a.width == b.width && a.is_unsigned == b.is_unsigned) return a;
    if (a.is_unsigned == b.is_unsigned) return a.width > b.width ? a : b;
    Type u = a.is_unsigned ? a : b;
    Type s = a.is_unsigned ? b : a;
    if (u.width >= s.width) return u;
    return s;
}
static void set_type(Expr *e, Type t) { expr_set_type(e, t); }
static void coerce_arg_to_param(Expr **argp, const Type *ptype) {
    if (!argp || !*argp || !ptype) return;
    Expr *arg = *argp;
    const Type *at = &arg->type;
    int at_arith = (at->kind == TY_INT || at->kind == TY_FLOAT);
    int pt_arith = (ptype->kind == TY_INT || ptype->kind == TY_FLOAT);
    if (!at_arith || !pt_arith) return;
    if (at->kind == ptype->kind && at->width == ptype->width
        && at->is_unsigned == ptype->is_unsigned)
        return;
    Type target = type_clone(*ptype);
    Expr *cast = expr_new_cast(target, arg, arg->loc);
    set_type(cast, target);
    *argp = cast;
}
static void normalize_init_list(Type *target, Expr *list, SourceLoc loc);
static Type check_expr(Expr *e, const SymTable *st, FunTable *ft) {
    if (!e) return type_default_int();
    switch (e->kind) {
    case EX_INT_LIT:
        set_type(e, type_make_int(e->type.width ? e->type.width : 4,
                                  e->type.is_unsigned));
        return type_clone(e->type);
    case EX_FLOAT_LIT:
        set_type(e, type_make_float(e->type.width ? e->type.width : 8));
        return type_clone(e->type);
    case EX_BINOP: {
        Type lt = check_expr(e->u.bin.l, st, ft);
        Type rt = check_expr(e->u.bin.r, st, ft);
        if (lt.kind == TY_ARRAY) {
            Type d = type_decay(lt); type_free(&lt); lt = d;
            set_type(e->u.bin.l, type_clone(lt));
        }
        if (rt.kind == TY_ARRAY) {
            Type d = type_decay(rt); type_free(&rt); rt = d;
            set_type(e->u.bin.r, type_clone(rt));
        }
        BinOp op = e->u.bin.op;
        Type res;
        if (op == BOP_AND || op == BOP_OR) {
            if (lt.kind != TY_INT && lt.kind != TY_FLOAT && lt.kind != TY_PTR)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "left operand of '%s' must be scalar",
                       op == BOP_AND ? "&&" : "||");
            if (rt.kind != TY_INT && rt.kind != TY_FLOAT && rt.kind != TY_PTR)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "right operand of '%s' must be scalar",
                       op == BOP_AND ? "&&" : "||");
            res = type_make_int(4, 0);
        } else if (op >= BOP_EQ && op <= BOP_GE) {
            res = type_make_int(4, 0);
        } else if ((op == BOP_ADD || op == BOP_SUB) && (lt.kind == TY_PTR || rt.kind == TY_PTR)) {
            if (op == BOP_SUB && lt.kind == TY_PTR && rt.kind == TY_PTR) {
                res = type_make_int(8, 0);
            } else if (lt.kind == TY_PTR) {
                res = type_clone(lt);
            } else {
                res = type_clone(rt);
            }
        } else if (op == BOP_BITAND || op == BOP_BITOR || op == BOP_BITXOR) {
            if (lt.kind != TY_INT)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "left operand of '%s' must be integer",
                       op == BOP_BITAND ? "&" : op == BOP_BITOR ? "|" : "^");
            if (rt.kind != TY_INT)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "right operand of '%s' must be integer",
                       op == BOP_BITAND ? "&" : op == BOP_BITOR ? "|" : "^");
            res = usual_arith_conv(lt, rt);
        } else if (op == BOP_SHL || op == BOP_SHR) {
            if (lt.kind != TY_INT)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "left operand of '%s' must be integer",
                       op == BOP_SHL ? "<<" : ">>");
            if (rt.kind != TY_INT)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "right operand of '%s' must be integer",
                       op == BOP_SHL ? "<<" : ">>");
            res = integer_promote(lt);
        } else {
            if (op == BOP_MOD &&
                (lt.kind != TY_INT || rt.kind != TY_INT))
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "operands of '%%' must be integer");
            else if (op != BOP_MOD &&
                     (lt.kind != TY_INT && lt.kind != TY_FLOAT))
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "left operand of '%s' must be arithmetic",
                       op == BOP_ADD ? "+" : op == BOP_SUB ? "-"
                       : op == BOP_MUL ? "*" : "/");
            res = usual_arith_conv(lt, rt);
        }
        type_free(&lt); type_free(&rt);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_UNARY: {
        Type ot = check_expr(e->u.un.operand, st, ft);
        if (ot.kind == TY_ARRAY) {
            Type d = type_decay(ot); type_free(&ot); ot = d;
            set_type(e->u.un.operand, type_clone(ot));
        }
        if ((e->u.un.op == UOP_BITNOT) && ot.kind != TY_INT)
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "bitwise NOT requires an integer operand");
        Type res;
        if (e->u.un.op == UOP_NOT) {
            if (ot.kind != TY_INT && ot.kind != TY_FLOAT && ot.kind != TY_PTR)
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "logical NOT requires a scalar operand");
            res = type_make_int(4, 0);
        } else {
            res = integer_promote(ot);
        }
        type_free(&ot);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_VAR: {
        if (e->u.var.pkg) {
            if (!g_sema_tu || !tu_imports(g_sema_tu, e->u.var.pkg)) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "package '%s' was not imported", e->u.var.pkg);
            }
            const PkgFuncExport *pf = ((void*)0);
            const PkgGlobalExport *pg = ((void*)0);
            if (!pkg_resolve_sym(e->u.var.pkg, e->u.var.name, &pf, &pg)) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "package '%s' has no exported symbol '%s'",
                       e->u.var.pkg, e->u.var.name);
            }
            if (pf) {
                ftab_push_export(ft, pf);
                const Type **ptys = ((void*)0);
                if (pf->arity > 0) {
                    ptys = runtime.malloc(pf->arity * sizeof(Type *));
                    if (!ptys) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
                    for (int i = 0; i < pf->arity; i++)
                        ptys[i] = &pf->param_types[i];
                }
                Type fn = type_make_func(pf->ret_type, (Type **)ptys, pf->arity);
                runtime.free(ptys);
                Type fp = type_make_ptr(fn);
                type_free(&fn);
                set_type(e, fp);
                return type_clone(e->type);
            }
            set_type(e, type_clone(pg->type));
            return type_clone(e->type);
        }
        const Sym *sym = symtable_find(st, e->u.var.name);
        if (sym) {
            set_type(e, type_clone(sym->type));
            return type_clone(e->type);
        }
        const FunSig *sig = ftab_find(ft, e->u.var.name);
        if (sig) {
            const Type **ptys = ((void*)0);
            if (sig->arity > 0) {
                ptys = runtime.malloc(sig->arity * sizeof(Type *));
                if (!ptys) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
                for (int i = 0; i < sig->arity; i++)
                    ptys[i] = &sig->param_types[i];
            }
            Type fn = type_make_func(sig->ret_type, (Type **)ptys, sig->arity);
            runtime.free(ptys);
            Type fp = type_make_ptr(fn);
            type_free(&fn);
            set_type(e, fp);
            return type_clone(e->type);
        }
        if (g_sema_pkg && g_sema_tu && g_sema_tu->package.name) {
            const PkgFuncExport *pf = ((void*)0);
            const PkgGlobalExport *pg = ((void*)0);
            if (pkg_resolve_sym(g_sema_tu->package.name, e->u.var.name, &pf, &pg)) {
                if (pf) {
                    ftab_push_export(ft, pf);
                    const Type **ptys = ((void*)0);
                    if (pf->arity > 0) {
                        ptys = runtime.malloc(pf->arity * sizeof(Type *));
                        if (!ptys) { runtime.fprintf(runtime.stderr, "fakecc: OOM\n"); runtime.exit(1); }
                        for (int i = 0; i < pf->arity; i++)
                            ptys[i] = &pf->param_types[i];
                    }
                    Type fn = type_make_func(pf->ret_type, (Type **)ptys, pf->arity);
                    runtime.free(ptys);
                    Type fp = type_make_ptr(fn);
                    type_free(&fn);
                    set_type(e, fp);
                    return type_clone(e->type);
                }
                set_type(e, type_clone(pg->type));
                return type_clone(e->type);
            }
        }
        {
            const char *hint = g_sema_pkg
                ? pkg_suggest_export(g_sema_pkg, e->u.var.name) : ((void*)0);
            if (hint) {
                if (g_sema_tu && tu_imports(g_sema_tu, hint)) {
                    die_at(e->loc.file, e->loc.line, e->loc.col,
                           "use of undeclared '%s'; did you mean '%s.%s'?",
                           e->u.var.name, hint, e->u.var.name);
                }
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "use of undeclared '%s'; did you mean '%s.%s'? "
                       "(add 'import %s;')",
                       e->u.var.name, hint, e->u.var.name, hint);
            }
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "use of undeclared variable '%s'", e->u.var.name);
        }
    }
    case EX_ASSIGN: {
        if (e->u.assign.lvalue->kind != EX_VAR &&
            e->u.assign.lvalue->kind != EX_DEREF &&
            e->u.assign.lvalue->kind != EX_INDEX &&
            e->u.assign.lvalue->kind != EX_MEMBER) {
            die_at(e->u.assign.lvalue->loc.file,
                   e->u.assign.lvalue->loc.line,
                   e->u.assign.lvalue->loc.col,
                   "expression is not assignable");
        }
        Type lt = check_expr(e->u.assign.lvalue, st, ft);
        if (lt.is_const)
            die_at(e->u.assign.lvalue->loc.file,
                   e->u.assign.lvalue->loc.line,
                   e->u.assign.lvalue->loc.col,
                   "assignment of read-only variable");
        Type rt = check_expr(e->u.assign.rvalue, st, ft);
        (void)rt;
        type_free(&rt);
        set_type(e, lt);
        return type_clone(e->type);
    }
    case EX_COMPOUND_ASSIGN: {
        Expr *lv = e->u.comp.lvalue;
        if (lv->kind != EX_VAR && lv->kind != EX_DEREF &&
            lv->kind != EX_INDEX && lv->kind != EX_MEMBER)
            die_at(lv->loc.file, lv->loc.line, lv->loc.col,
                   "left operand of '%s' must be an lvalue",
                   "compound assign");
        Type lt = check_expr(lv, st, ft);
        if (lt.is_const)
            die_at(lv->loc.file, lv->loc.line, lv->loc.col,
                   "compound assignment of read-only variable");
        Type rt = check_expr(e->u.comp.rvalue, st, ft);
        BinOp op = e->u.comp.op;
        int arith_float = (op == BOP_ADD || op == BOP_SUB || op == BOP_MUL
                           || op == BOP_DIV);
        if (op == BOP_ADD || op == BOP_SUB) {
            if (lt.kind == TY_PTR && rt.kind != TY_INT)
                die_at(lv->loc.file, lv->loc.line, lv->loc.col,
                       "pointer %s requires an integer right operand",
                       op == BOP_ADD ? "+=" : "-=");
        }
        if (lt.kind != TY_PTR
            && !(arith_float && (lt.kind == TY_FLOAT || rt.kind == TY_FLOAT))) {
            if (lt.kind != TY_INT)
                die_at(lv->loc.file, lv->loc.line, lv->loc.col,
                       "left operand of '%s' must be integer",
                       "compound assign");
            if (rt.kind != TY_INT)
                die_at(lv->loc.file, lv->loc.line, lv->loc.col,
                       "right operand of '%s' must be integer",
                       "compound assign");
        }
        if (lt.kind == TY_FLOAT && !arith_float)
            die_at(lv->loc.file, lv->loc.line, lv->loc.col,
                   "left operand of '%s' must be integer", "compound assign");
        type_free(&rt);
        set_type(e, lt);
        return type_clone(e->type);
    }
    case EX_CALL: {
        if (e->u.call.callee->kind == EX_VAR
            && runtime.strcmp(e->u.call.callee->u.var.name, "__syscall") == 0) {
            if (e->u.call.args.len < 1 || e->u.call.args.len > 7) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "__syscall takes 1 to 7 arguments (syscall num + up to 6 args)");
            }
            for (size_t i = 0; i < e->u.call.args.len; i++) {
                Type at = check_expr(e->u.call.args.data[i], st, ft);
                type_free(&at);
            }
            set_type(e, type_make_int(8, 0));
            return type_clone(e->type);
        }
        if (e->u.call.callee->kind == EX_VAR
            && runtime.strcmp(e->u.call.callee->u.var.name, "__builtin_ctzll") == 0) {
            if (e->u.call.args.len != 1) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "__builtin_ctzll takes exactly 1 argument");
            }
            Type at = check_expr(e->u.call.args.data[0], st, ft);
            type_free(&at);
            set_type(e, type_make_int(4, 0));
            return type_clone(e->type);
        }
        if (e->u.call.callee->kind == EX_VAR
            && runtime.strcmp(e->u.call.callee->u.var.name, "va_start") == 0) {
            if (e->u.call.args.len != 2) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_start takes exactly 2 arguments (va_list, last_param)");
            }
            Type list_ty = check_expr(e->u.call.args.data[0], st, ft);
            if (!is_va_list_type(&list_ty)) {
                type_free(&list_ty);
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_start first argument must be a va_list");
            }
            type_free(&list_ty);
            Type at = check_expr(e->u.call.args.data[1], st, ft);
            type_free(&at);
            set_type(e, type_make_void());
            return type_clone(e->type);
        }
        if (e->u.call.callee->kind == EX_VAR
            && runtime.strcmp(e->u.call.callee->u.var.name, "va_arg") == 0) {
            if (e->u.call.args.len != 1) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_arg takes exactly 2 arguments (va_list, type)");
            }
            Type list_ty = check_expr(e->u.call.args.data[0], st, ft);
            if (!is_va_list_type(&list_ty)) {
                type_free(&list_ty);
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_arg first argument must be a va_list");
            }
            type_free(&list_ty);
            if (e->va_arg_type.kind == TY_VOID && e->va_arg_type.width == 0
                && !e->va_arg_type.tag) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_arg second argument must be a type");
            }
            set_type(e, type_clone(e->va_arg_type));
            return type_clone(e->type);
        }
        if (e->u.call.callee->kind == EX_VAR
            && runtime.strcmp(e->u.call.callee->u.var.name, "va_end") == 0) {
            if (e->u.call.args.len != 1) {
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_end takes exactly 1 argument (va_list)");
            }
            Type list_ty = check_expr(e->u.call.args.data[0], st, ft);
            if (!is_va_list_type(&list_ty)) {
                type_free(&list_ty);
                die_at(e->loc.file, e->loc.line, e->loc.col,
                       "va_end argument must be a va_list");
            }
            type_free(&list_ty);
            set_type(e, type_make_void());
            return type_clone(e->type);
        }
        Type callee_ty = check_expr(e->u.call.callee, st, ft);
        if (e->u.call.callee->kind == EX_VAR) {
            const FunSig *sig = ftab_find(ft, e->u.call.callee->u.var.name);
            if (sig) {
                type_free(&callee_ty);
                if (sig->is_variadic) {
                    if ((int)e->u.call.args.len < sig->arity) {
                        die_at(e->loc.file, e->loc.line, e->loc.col,
                               "function '%s' takes at least %d argument%s but %zu given",
                               e->u.call.callee->u.var.name, sig->arity,
                               sig->arity == 1 ? "" : "s", e->u.call.args.len);
                    }
                } else if ((int)e->u.call.args.len != sig->arity) {
                    die_at(e->loc.file, e->loc.line, e->loc.col,
                           "function '%s' takes %d argument%s but %zu given",
                           e->u.call.callee->u.var.name, sig->arity,
                           sig->arity == 1 ? "" : "s", e->u.call.args.len);
                }
                for (size_t i = 0; i < e->u.call.args.len; i++) {
                    Type at = check_expr(e->u.call.args.data[i], st, ft);
                    type_free(&at);
                    if ((int)i < sig->arity)
                        coerce_arg_to_param(&e->u.call.args.data[i],
                                            &sig->param_types[i]);
                }
                set_type(e, type_clone(sig->ret_type));
                return type_clone(e->type);
            }
            const Sym *extern_sym = symtable_find(st, e->u.call.callee->u.var.name);
            if (extern_sym && (extern_sym->type.kind == TY_FUNC ||
                               (extern_sym->type.kind == TY_PTR &&
                                extern_sym->type.pointee &&
                                extern_sym->type.pointee->kind == TY_FUNC))) {
                const Type *fty = (extern_sym->type.kind == TY_FUNC)
                                  ? &extern_sym->type : extern_sym->type.pointee;
                type_free(&callee_ty);
                if ((int)e->u.call.args.len != fty->func_nparams) {
                    die_at(e->loc.file, e->loc.line, e->loc.col,
                           "function '%s' takes %d argument%s but %zu given",
                           e->u.call.callee->u.var.name, fty->func_nparams,
                           fty->func_nparams == 1 ? "" : "s", e->u.call.args.len);
                }
                for (size_t i = 0; i < e->u.call.args.len; i++) {
                    Type at = check_expr(e->u.call.args.data[i], st, ft);
                    type_free(&at);
                    if (fty->func_params && (int)i < fty->func_nparams)
                        coerce_arg_to_param(&e->u.call.args.data[i],
                                            &fty->func_params[i]);
                }
                Type ret = fty->func_ret ? *fty->func_ret : type_make_void();
                set_type(e, ret);
                return type_clone(e->type);
            }
        }
        Type fn_ty = callee_ty;
        if (fn_ty.kind == TY_PTR && fn_ty.pointee && fn_ty.pointee->kind == TY_FUNC) {
            fn_ty = type_clone(*fn_ty.pointee);
            type_free(&callee_ty);
        } else if (fn_ty.kind == TY_FUNC) {
            fn_ty = type_clone(callee_ty);
            type_free(&callee_ty);
        } else {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "call to non-function (callee type must be a function or function pointer)");
        }
        if ((int)e->u.call.args.len != fn_ty.func_nparams) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "function pointer expects %d argument%s but %zu given",
                   fn_ty.func_nparams,
                   fn_ty.func_nparams == 1 ? "" : "s", e->u.call.args.len);
        }
        for (size_t i = 0; i < e->u.call.args.len; i++) {
            Type at = check_expr(e->u.call.args.data[i], st, ft);
            type_free(&at);
            if (fn_ty.func_params && (int)i < fn_ty.func_nparams)
                coerce_arg_to_param(&e->u.call.args.data[i],
                                    &fn_ty.func_params[i]);
        }
        set_type(e, type_clone(*fn_ty.func_ret));
        type_free(&fn_ty);
        return type_clone(e->type);
    }
    case EX_STR: {
        Type ct = type_make_int(1, 0);
        set_type(e, type_make_array(ct, e->u.str.len + 1));
        type_free(&ct);
        return type_clone(e->type);
    }
    case EX_ADDR: {
        Type ot = check_expr(e->u.addr.operand, st, ft);
        ExprKind ok = e->u.addr.operand->kind;
        if (ok != EX_VAR && ok != EX_DEREF && ok != EX_INDEX && ok != EX_MEMBER) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "cannot take address of rvalue");
        }
        if (ot.kind == TY_PTR && ot.pointee && ot.pointee->kind == TY_FUNC) {
            set_type(e, ot);
            return type_clone(e->type);
        }
        Type res = type_make_ptr(ot);
        type_free(&ot);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_DEREF: {
        Type ot = check_expr(e->u.deref.operand, st, ft);
        if (ot.kind == TY_ARRAY) {
            Type d = type_decay(ot); type_free(&ot); ot = d;
            set_type(e->u.deref.operand, type_clone(ot));
        }
        if (ot.kind != TY_PTR) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "cannot dereference non-pointer");
        }
        Type res = type_clone(*ot.pointee);
        type_free(&ot);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_INDEX: {
        Type at = check_expr(e->u.idx.array, st, ft);
        Type it = check_expr(e->u.idx.index, st, ft);
        if (at.kind == TY_INT && (it.kind == TY_PTR || it.kind == TY_ARRAY)) {
            Expr *tmp = e->u.idx.array;
            e->u.idx.array = e->u.idx.index;
            e->u.idx.index = tmp;
            Type swap = at; at = it; it = swap;
        }
        type_free(&it);
        Type base = at;
        if (base.kind == TY_ARRAY) {
            Type d = type_decay(base); type_free(&base); base = d;
        }
        if (base.kind != TY_PTR) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "subscript on non-pointer/non-array");
        }
        Type res = type_clone(*base.pointee);
        type_free(&base);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_MEMBER: {
        if (e->u.member.obj->kind == EX_VAR
            && e->u.member.obj->u.var.pkg == ((void*)0)
            && g_sema_tu
            && tu_imports(g_sema_tu, e->u.member.obj->u.var.name)
            && !symtable_find(st, e->u.member.obj->u.var.name)) {
            char *pkg = xstrdup(e->u.member.obj->u.var.name);
            char *name = xstrdup(e->u.member.name);
            expr_free(e->u.member.obj);
            runtime.free(e->u.member.name);
            e->kind = EX_VAR;
            e->u.var.name = name;
            e->u.var.pkg = pkg;
            return check_expr(e, st, ft);
        }
        Type ot = check_expr(e->u.member.obj, st, ft);
        if (ot.kind != TY_STRUCT) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "member access '.%s' on non-struct", e->u.member.name);
        }
        const StructDef *sd = struct_registry_find_c(g_sema_structs, ot.tag);
        if (!sd) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "unknown struct 'struct %s'", ot.tag);
        }
        const StructMember *m = ((void*)0);
        for (int i = 0; i < sd->num_members; i++)
            if (runtime.strcmp(sd->members[i].name, e->u.member.name) == 0)
                { m = &sd->members[i]; break; }
        if (!m) {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "struct '%s' has no member '%s'", ot.tag, e->u.member.name);
        }
        type_free(&ot);
        set_type(e, type_clone(m->type));
        return type_clone(e->type);
    }
    case EX_INC_DEC: {
        Expr *op = e->u.incdec.operand;
        if (op->kind != EX_VAR && op->kind != EX_DEREF &&
            op->kind != EX_INDEX && op->kind != EX_MEMBER)
            die_at(op->loc.file, op->loc.line, op->loc.col,
                   "operand of '%s' must be an lvalue",
                   e->u.incdec.is_inc ? "++" : "--");
        Type ot = check_expr(op, st, ft);
        if (ot.is_const)
            die_at(op->loc.file, op->loc.line, op->loc.col,
                   "cannot increment/decrement a read-only variable");
        if (ot.kind != TY_INT && ot.kind != TY_FLOAT && ot.kind != TY_PTR)
            die_at(op->loc.file, op->loc.line, op->loc.col,
                   "operand of '%s' must be arithmetic or pointer",
                   e->u.incdec.is_inc ? "++" : "--");
        type_free(&ot);
        Type res;
        if (op->type.kind == TY_PTR)
            res = type_clone(op->type);
        else
            res = type_make_int(op->type.width ? op->type.width : 4,
                                op->type.is_unsigned);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_COMMA: {
        Type lt = check_expr(e->u.comma.lhs, st, ft);
        type_free(&lt);
        Type rt = check_expr(e->u.comma.rhs, st, ft);
        set_type(e, rt);
        return type_clone(e->type);
    }
    case EX_TERNARY: {
        Type ct = check_expr(e->u.tern.cond, st, ft);
        if (ct.kind != TY_INT && ct.kind != TY_PTR)
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "ternary condition must be scalar");
        type_free(&ct);
        Type tt = check_expr(e->u.tern.then, st, ft);
        Type et = check_expr(e->u.tern.else_, st, ft);
        if (tt.kind == TY_ARRAY) {
            Type d = type_decay(tt); type_free(&tt); tt = d;
            set_type(e->u.tern.then, type_clone(tt));
        }
        if (et.kind == TY_ARRAY) {
            Type d = type_decay(et); type_free(&et); et = d;
            set_type(e->u.tern.else_, type_clone(et));
        }
        int t_is_null_const = (tt.kind == TY_INT && tt.width == 4
                               && e->u.tern.then->kind == EX_INT_LIT
                               && e->u.tern.then->u.int_val == 0);
        int e_is_null_const = (et.kind == TY_INT && et.width == 4
                               && e->u.tern.else_->kind == EX_INT_LIT
                               && e->u.tern.else_->u.int_val == 0);
        int tt_arith = (tt.kind == TY_INT || tt.kind == TY_FLOAT);
        int et_arith = (et.kind == TY_INT || et.kind == TY_FLOAT);
        Type res;
        if (tt_arith && et_arith) {
            res = usual_arith_conv(tt, et);
        } else if (tt.kind == TY_PTR && et.kind == TY_PTR) {
            res = type_clone(tt);
        } else if (tt.kind == TY_PTR && e_is_null_const) {
            res = type_clone(tt);
        } else if (et.kind == TY_PTR && t_is_null_const) {
            res = type_clone(et);
        } else if (tt.kind == TY_STRUCT && et.kind == TY_STRUCT
                   && runtime.strcmp(tt.tag, et.tag) == 0) {
            res = type_clone(tt);
        } else {
            die_at(e->loc.file, e->loc.line, e->loc.col,
                   "ternary branches must both be arithmetic, both be pointer, "
                   "or pointer with null constant");
        }
        type_free(&tt); type_free(&et);
        set_type(e, res);
        return type_clone(e->type);
    }
    case EX_CAST: {
        Type ot = check_expr(e->u.cast.operand, st, ft);
        type_free(&ot);
        set_type(e, type_clone(e->u.cast.target));
        return type_clone(e->type);
    }
    case EX_SIZEOF_TYPE:
    case EX_SIZEOF_EXPR: {
        if (e->kind == EX_SIZEOF_EXPR) {
            Type ot = check_expr(e->u.sizeof_e.operand, st, ft);
            type_free(&ot);
        }
        set_type(e, type_make_int(8, 1));
        return type_clone(e->type);
    }
    case EX_ALIGNOF_TYPE:
        set_type(e, type_make_int(8, 1));
        return type_clone(e->type);
    case EX_INIT_LIST: {
        for (int i = 0; i < e->u.init_list.num_elements; i++) {
            Type et = check_expr(e->u.init_list.elements[i], st, ft);
            type_free(&et);
        }
        set_type(e, type_default_int());
        return type_clone(e->type);
    }
    case EX_COMPOUND_LITERAL: {
        Expr *init = e->u.compound.init;
        if (init->kind == EX_INIT_LIST)
            normalize_init_list(&e->u.compound.target_type, init, e->loc);
        for (int i = 0; i < init->u.init_list.num_elements; i++) {
            Type et = check_expr(init->u.init_list.elements[i], st, ft);
            type_free(&et);
        }
        set_type(e, type_clone(e->u.compound.target_type));
        return type_clone(e->type);
    }
    }
    return type_default_int();
}
static void check_stmt(Stmt *s, SymTable *st, FunTable *ft,
                       size_t scope_mark, int *has_return);
static int g_sema_loop_depth = 0;
static LabelSet *g_sema_labels = ((void*)0);
static void check_stmt_list(StmtArray *body, SymTable *st,
                            FunTable *ft, int *has_return) {
    size_t mark = symtable_enter_scope(st);
    for (size_t i = 0; i < body->len; i++)
        check_stmt(&body->data[i], st, ft, mark, has_return);
    symtable_leave_scope(st, mark);
}
static int is_const_init(const Expr *e, const SymTable *globals) {
    if (!e) return 1;
    if (e->kind == EX_INT_LIT) return 1;
    if (e->kind == EX_FLOAT_LIT) return 1;
    if (e->kind == EX_STR) return 1;
    if (e->kind == EX_CAST)
        return is_const_init(e->u.cast.operand, globals);
    if (e->kind == EX_UNARY
        && (e->u.un.op == UOP_NEG || e->u.un.op == UOP_POS)
        && e->u.un.operand && e->u.un.operand->kind == EX_FLOAT_LIT)
        return 1;
    long long _fold_tmp;
    if (fold_const_int(e, &_fold_tmp)) return 1;
    if (e->kind == EX_INIT_LIST) {
        for (int i = 0; i < e->u.init_list.num_elements; i++)
            if (!is_const_init(e->u.init_list.elements[i], globals)) return 0;
        return 1;
    }
    if (e->kind == EX_VAR && globals) {
        const Sym *s = symtable_find(globals, e->u.var.name);
        if (s && s->type.is_const) return 1;
    }
    if (e->kind == EX_ADDR && e->u.addr.operand
        && e->u.addr.operand->kind == EX_VAR && globals) {
        if (symtable_find(globals, e->u.addr.operand->u.var.name))
            return 1;
    }
    return 0;
}
static int init_leaf_count(Type t) {
    if (t.kind == TY_ARRAY && t.elem_type)
        return t.length * init_leaf_count(*t.elem_type);
    if (t.kind == TY_STRUCT) {
        const StructDef *sd = struct_registry_find_c(g_sema_structs, t.tag);
        if (!sd || sd->num_members == 0) return 1;
        if (sd->is_union) return init_leaf_count(sd->members[0].type);
        int total = 0;
        for (int i = 0; i < sd->num_members; i++)
            total += init_leaf_count(sd->members[i].type);
        return total;
    }
    return 1;
}
static int init_elem_may_be_aggregate(const Expr *e) {
    switch (e->kind) {
    case EX_VAR: case EX_CALL: case EX_MEMBER: case EX_INDEX: case EX_DEREF:
    case EX_COMPOUND_LITERAL: case EX_ASSIGN: case EX_TERNARY: case EX_COMMA:
    case EX_CAST:
        return 1;
    default:
        return 0;
    }
}
static void normalize_init_list(Type *target, Expr *list, SourceLoc loc) {
    int n = list->u.init_list.num_elements;
    if (target->kind == TY_ARRAY && target->length == 0) {
        int len = n;
        if (target->elem_type
            && (target->elem_type->kind == TY_ARRAY
                || target->elem_type->kind == TY_STRUCT)
            && n > 0 && list->u.init_list.elements[0]->kind != EX_INIT_LIST
            && !init_elem_may_be_aggregate(list->u.init_list.elements[0])
            && !(list->u.init_list.elements[0]->kind == EX_STR
                 && target->elem_type->kind == TY_ARRAY)) {
            int per = init_leaf_count(*target->elem_type);
            if (per > 0) len = (n + per - 1) / per;
        }
        for (int i = 0; i < n; i++)
            if (list->u.init_list.desig_kind[i] == 0
                && list->u.init_list.desig_index[i] + 1 > len)
                len = list->u.init_list.desig_index[i] + 1;
        target->length = len;
    }
    int N;
    const StructDef *sd = ((void*)0);
    switch (target->kind) {
    case TY_ARRAY: N = target->length; break;
    case TY_STRUCT:
        sd = struct_registry_find_c(g_sema_structs, target->tag);
        if (!sd)
            die_at(loc.file, loc.line, loc.col,
                   "unknown struct 'struct %s'", target->tag);
        N = sd->num_members;
        break;
    default: N = 1; break;
    }
    for (int i = 0; i < n; i++) {
        int kind = list->u.init_list.desig_kind[i];
        if (kind == 0) {
            if (target->kind != TY_ARRAY)
                die_at(loc.file, loc.line, loc.col,
                       "array index designator used on a non-array type");
            int idx = list->u.init_list.desig_index[i];
            if (idx < 0 || idx >= N)
                die_at(loc.file, loc.line, loc.col,
                       "designator index %d out of range for array of length %d",
                       idx, N);
        } else if (kind == 1) {
            if (target->kind != TY_STRUCT)
                die_at(loc.file, loc.line, loc.col,
                       "member designator used on a non-struct type");
            const char *name = list->u.init_list.desig_member[i];
            int found = 0;
            for (int j = 0; j < sd->num_members; j++)
                if (runtime.strcmp(sd->members[j].name, name) == 0) { found = 1; break; }
            if (!found)
                die_at(loc.file, loc.line, loc.col,
                       "struct '%s' has no member named '%s'",
                       target->tag, name);
        }
    }
    Expr **out = runtime.malloc(N * sizeof(Expr *));
    for (int i = 0; i < N; i++)
        out[i] = expr_new_int(0, loc);
    int cursor = 0;
    for (int i = 0; i < n; i++) {
        Expr *elem = list->u.init_list.elements[i];
        int pos;
        if (list->u.init_list.desig_kind[i] == 0) {
            pos = list->u.init_list.desig_index[i];
        } else if (list->u.init_list.desig_kind[i] == 1) {
            const char *name = list->u.init_list.desig_member[i];
            pos = -1;
            for (int j = 0; j < sd->num_members; j++)
                if (runtime.strcmp(sd->members[j].name, name) == 0) { pos = j; break; }
        } else {
            pos = cursor;
        }
        if (pos < 0 || pos >= N)
            die_at(loc.file, loc.line, loc.col,
                   "too many initializers: %d value(s) for %d slot(s)", n, N);
        Type *slot_type = ((void*)0);
        if (target->kind == TY_ARRAY) slot_type = target->elem_type;
        else if (target->kind == TY_STRUCT) slot_type = &sd->members[pos].type;
        if (slot_type && elem->kind != EX_INIT_LIST
            && (slot_type->kind == TY_ARRAY || slot_type->kind == TY_STRUCT)
            && !init_elem_may_be_aggregate(elem)
            && !(elem->kind == EX_STR && slot_type->kind == TY_ARRAY)) {
            int want = init_leaf_count(*slot_type);
            int take = 1;
            while (take < want && i + take < n
                   && list->u.init_list.desig_kind[i + take] == -1)
                take++;
            Expr **sub = runtime.malloc(take * sizeof(Expr *));
            for (int k = 0; k < take; k++)
                sub[k] = list->u.init_list.elements[i + k];
            elem = expr_new_init_list(sub, take, elem->loc);
            i += take - 1;
        }
        if (elem->kind == EX_INIT_LIST) {
            if (target->kind == TY_ARRAY)
                normalize_init_list(target->elem_type, elem, elem->loc);
            else
                normalize_init_list(&sd->members[pos].type, elem, elem->loc);
        }
        expr_free(out[pos]);
        out[pos] = elem;
        cursor = pos + 1;
    }
    for (int i = 0; i < n; i++)
        runtime.free(list->u.init_list.desig_member[i]);
    runtime.free(list->u.init_list.desig_kind);
    runtime.free(list->u.init_list.desig_index);
    runtime.free(list->u.init_list.desig_member);
    runtime.free(list->u.init_list.elements);
    list->u.init_list.elements = out;
    list->u.init_list.num_elements = N;
    list->u.init_list.desig_kind = ((void*)0);
    list->u.init_list.desig_index = ((void*)0);
    list->u.init_list.desig_member = ((void*)0);
}
static void check_init_list_shape(Type target, const Expr *list, SourceLoc loc) {
    int n = list->u.init_list.num_elements;
    switch (target.kind) {
    case TY_ARRAY:
        if (target.length > 0 && n > target.length)
            die_at(loc.file, loc.line, loc.col,
                   "too many initializers for array (expected %d, got %d)",
                   target.length, n);
        for (int i = 0; i < n; i++) {
            const Expr *elem = list->u.init_list.elements[i];
            if (elem->kind == EX_INIT_LIST && target.elem_type)
                check_init_list_shape(*target.elem_type, elem, elem->loc);
        }
        break;
    case TY_STRUCT: {
        const StructDef *sd = struct_registry_find_c(g_sema_structs, target.tag);
        if (!sd)
            die_at(loc.file, loc.line, loc.col,
                   "unknown struct 'struct %s'", target.tag);
        if (n > sd->num_members)
            die_at(loc.file, loc.line, loc.col,
                   "too many initializers for struct '%s' (expected %d, got %d)",
                   target.tag, sd->num_members, n);
        for (int i = 0; i < n; i++) {
            const Expr *elem = list->u.init_list.elements[i];
            if (elem->kind == EX_INIT_LIST && i < sd->num_members)
                check_init_list_shape(sd->members[i].type, elem, elem->loc);
        }
        break;
    }
    default:
        if (n > 1)
            die_at(loc.file, loc.line, loc.col,
                   "scalar initializer requires at most one element");
        break;
    }
}
static void check_stmt(Stmt *s, SymTable *st, FunTable *ft,
                       size_t scope_mark, int *has_return) {
    Type discard;
    switch (s->kind) {
    case ST_DECL: {
        if (symtable_has_since(st, s->u.decl.name, scope_mark)) {
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "redeclaration of '%s'", s->u.decl.name);
        }
        if (s->u.decl.type.kind == TY_VOID)
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "cannot declare variable '%s' of type void",
                   s->u.decl.name ? s->u.decl.name : "(null)");
        if (s->u.decl.storage_class == 2) {
            symtable_push(st, s->u.decl.name, s->u.decl.type, s->loc);
            break;
        }
        if (s->u.decl.type.kind == TY_ARRAY && s->u.decl.type.length == 0
            && s->u.decl.init && s->u.decl.init->kind == EX_STR
            && s->u.decl.type.elem_type
            && s->u.decl.type.elem_type->width == 1) {
            s->u.decl.type.length = s->u.decl.init->u.str.len + 1;
        }
        if (s->u.decl.init && s->u.decl.init->kind == EX_STR
            && s->u.decl.type.kind == TY_ARRAY && s->u.decl.type.elem_type
            && s->u.decl.type.elem_type->width == 1) {
            Expr *str = s->u.decl.init;
            int n = str->u.str.len + 1;
            Expr **elems = runtime.malloc(n * sizeof(Expr *));
            for (int i = 0; i < n - 1; i++)
                elems[i] = expr_new_int((unsigned char)str->u.str.bytes[i],
                                        str->loc);
            elems[n - 1] = expr_new_int(0, str->loc);
            Expr *list = expr_new_init_list(elems, n, str->loc);
            expr_free(str);
            s->u.decl.init = list;
        }
        if (s->u.decl.init && s->u.decl.init->kind == EX_INIT_LIST)
            normalize_init_list(&s->u.decl.type, s->u.decl.init, s->loc);
        symtable_push(st, s->u.decl.name, s->u.decl.type, s->loc);
        if (s->u.decl.init) {
            if (s->u.decl.init->kind == EX_INIT_LIST)
                check_init_list_shape(s->u.decl.type, s->u.decl.init, s->loc);
            discard = check_expr(s->u.decl.init, st, ft); type_free(&discard);
        }
        break;
    }
    case ST_EXPR:
        discard = check_expr(s->u.expr, st, ft); type_free(&discard);
        break;
    case ST_RETURN:
        if (s->u.value == ((void*)0)) {
            if (g_sema_ret_type.kind != TY_VOID)
                die_at(s->loc.file, s->loc.line, s->loc.col,
                       "non-void function must return a value");
        } else {
            if (g_sema_ret_type.kind == TY_VOID)
                die_at(s->loc.file, s->loc.line, s->loc.col,
                       "void function cannot return a value");
            discard = check_expr(s->u.value, st, ft); type_free(&discard);
        }
        *has_return = 1;
        break;
    case ST_IF:
        discard = check_expr(s->u.if_s.cond, st, ft); type_free(&discard);
        check_stmt(s->u.if_s.then_s, st, ft, scope_mark, has_return);
        if (s->u.if_s.else_s) check_stmt(s->u.if_s.else_s, st, ft, scope_mark, has_return);
        break;
    case ST_WHILE:
        discard = check_expr(s->u.while_s.cond, st, ft); type_free(&discard);
        g_sema_loop_depth++;
        check_stmt(s->u.while_s.body, st, ft, scope_mark, has_return);
        g_sema_loop_depth--;
        break;
    case ST_DO_WHILE:
        discard = check_expr(s->u.do_s.cond, st, ft);
        if (discard.kind != TY_INT && discard.kind != TY_PTR)
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "do-while condition must be scalar");
        type_free(&discard);
        g_sema_loop_depth++;
        check_stmt(s->u.do_s.body, st, ft, scope_mark, has_return);
        g_sema_loop_depth--;
        break;
    case ST_GOTO:
        if (!labelset_has(g_sema_labels, s->u.goto_s.target)) {
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "use of undeclared label '%s'", s->u.goto_s.target);
        }
        break;
    case ST_LABEL:
        check_stmt(s->u.label_s.stmt, st, ft, scope_mark, has_return);
        break;
    case ST_SWITCH: {
        Type ct = check_expr(s->u.switch_s.cond, st, ft);
        if (ct.kind != TY_INT)
            die_at(s->u.switch_s.cond->loc.file,
                   s->u.switch_s.cond->loc.line,
                   s->u.switch_s.cond->loc.col,
                   "switch condition must be integer");
        type_free(&ct);
        g_sema_loop_depth++;
        for (int i = 0; i < s->u.switch_s.num_cases; i++) {
            SwitchCase *arm = &s->u.switch_s.cases[i];
            for (size_t j = 0; j < arm->stmts.len; j++)
                check_stmt(&arm->stmts.data[j], st, ft, scope_mark, has_return);
        }
        g_sema_loop_depth--;
        break;
    }
    case ST_FOR: {
        size_t mark = symtable_enter_scope(st);
        if (s->u.for_s.init) {
            if (s->u.for_s.init->kind == ST_BLOCK) {
                StmtArray *blk = &s->u.for_s.init->u.block;
                for (size_t i = 0; i < blk->len; i++)
                    check_stmt(&blk->data[i], st, ft, mark, has_return);
            } else {
                check_stmt(s->u.for_s.init, st, ft, mark, has_return);
            }
        }
        if (s->u.for_s.cond) {
            discard = check_expr(s->u.for_s.cond, st, ft); type_free(&discard);
        }
        if (s->u.for_s.step) {
            discard = check_expr(s->u.for_s.step, st, ft); type_free(&discard);
        }
        g_sema_loop_depth++;
        check_stmt(s->u.for_s.body, st, ft, mark, has_return);
        g_sema_loop_depth--;
        symtable_leave_scope(st, mark);
        break;
    }
    case ST_BREAK:
    case ST_CONTINUE:
        if (g_sema_loop_depth == 0) {
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "'%s' outside of loop", s->kind == ST_BREAK ? "break" : "continue");
        }
        break;
    case ST_BLOCK:
        check_stmt_list(&s->u.block, st, ft, has_return);
        break;
    }
}
void sema_check_in_pkg(const TranslationUnit *tu_const, int require_main,
                       PkgContext *ctx) {
    TranslationUnit *tu = (TranslationUnit *)tu_const;
    g_sema_structs = &tu->structs;
    g_sema_pkg = ctx;
    g_sema_tu = tu_const;
    FunTable ft;
    ftab_init(&ft);
    int has_main = 0;
    for (size_t i = 0; i < tu->functions.len; i++) {
        FunctionDecl *fn = &tu->functions.data[i];
        const FunSig *ex = ftab_find(&ft, fn->name);
        if (ex) {
            if (fn->is_extern) {
                continue;
            }
            if (ex->is_external) {
                size_t idx = (size_t)(ex - ft.data);
                ft.data[idx].is_external = 0;
                ft.data[idx].arity = (int)fn->params.len;
                ft.data[idx].is_variadic = fn->is_variadic;
                ft.data[idx].ret_type = fn->ret_type;
                ft.data[idx].loc = fn->loc;
                for (int k = 0; k < ft.data[idx].arity && k < 16; k++)
                    ft.data[idx].param_types[k] = fn->params.data[k].type;
                if (runtime.strcmp(fn->name, "main") == 0) has_main = 1;
                continue;
            }
            die_at(fn->loc.file, fn->loc.line, fn->loc.col,
                   "redefinition of function '%s'", fn->name);
        }
        ftab_push(&ft, fn);
        if (runtime.strcmp(fn->name, "main") == 0 && !fn->is_extern) has_main = 1;
    }
    if (!has_main && require_main) {
        die_at(tu->package.loc.file, tu->package.loc.line, tu->package.loc.col,
               "no 'main' function defined");
    }
    if (g_sema_pkg && tu->package.name) {
        Package *cur = pkg_find(g_sema_pkg, tu->package.name);
        import_pkg_funcs(tu, &ft, cur);
        import_pkg_globals(tu, cur);
    }
    if (g_sema_pkg) {
        for (size_t i = 0; i < tu->imports.len; i++) {
            Package *ip = pkg_find(g_sema_pkg, tu->imports.data[i].name);
            import_pkg_globals(tu, ip);
            if (!ip) continue;
            for (size_t f = 0; f < ip->nfuncs; f++)
                tu_ensure_extern_func(tu, &ip->funcs[f]);
        }
    }
    SymTable globals;
    symtable_init(&globals);
    for (size_t i = 0; i < tu->globals.len; i++) {
        Stmt *s = &tu->globals.data[i];
        if (s->kind != ST_DECL) continue;
        if (symtable_has_since(&globals, s->u.decl.name, 0)) {
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "redefinition of global '%s'", s->u.decl.name);
        }
        if (ftab_find(&ft, s->u.decl.name)) {
            die_at(s->loc.file, s->loc.line, s->loc.col,
                   "global '%s' conflicts with a function of the same name",
                   s->u.decl.name);
        }
        if (s->u.decl.type.kind == TY_ARRAY && s->u.decl.type.length == 0
            && s->u.decl.init && s->u.decl.init->kind == EX_STR
            && s->u.decl.type.elem_type
            && s->u.decl.type.elem_type->width == 1) {
            s->u.decl.type.length = s->u.decl.init->u.str.len + 1;
        }
        if (s->u.decl.init && s->u.decl.init->kind == EX_INIT_LIST)
            normalize_init_list(&s->u.decl.type, s->u.decl.init, s->loc);
        symtable_push(&globals, s->u.decl.name, s->u.decl.type, s->loc);
        if (s->u.decl.init) {
            if (s->u.decl.init->kind == EX_INIT_LIST)
                check_init_list_shape(s->u.decl.type, s->u.decl.init, s->loc);
            if (!is_const_init(s->u.decl.init, &globals))
                die_at(s->loc.file, s->loc.line, s->loc.col,
                       "global initializer must be a constant");
            Type dt = check_expr(s->u.decl.init, &globals, &ft);
            type_free(&dt);
        }
    }
    for (size_t i = 0; i < tu->functions.len; i++) {
        FunctionDecl *fn = &tu->functions.data[i];
        if (fn->is_extern) continue;
        SymTable st;
        symtable_init(&st);
        for (size_t g = 0; g < globals.len; g++) {
            symtable_push(&st, globals.data[g].name, globals.data[g].type,
                          globals.data[g].loc);
        }
        size_t mark = symtable_enter_scope(&st);
        for (size_t j = 0; j < fn->params.len; j++) {
            if (fn->params.data[j].name && fn->params.data[j].name[0] != '\0') {
                if (symtable_has_since(&st, fn->params.data[j].name, mark)) {
                    die_at(fn->params.data[j].loc.file,
                           fn->params.data[j].loc.line,
                           fn->params.data[j].loc.col,
                           "duplicate parameter name '%s'",
                           fn->params.data[j].name);
                }
            }
            Type pty = fn->params.data[j].type;
            int own_ptr = 0;
            if (pty.kind == TY_ARRAY && pty.length == 0) {
                pty = type_make_ptr(*pty.elem_type);
                own_ptr = 1;
            }
            if (fn->params.data[j].name && fn->params.data[j].name[0] != '\0') {
                symtable_push(&st, fn->params.data[j].name,
                              pty, fn->params.data[j].loc);
            }
            if (own_ptr) type_free(&pty);
        }
        LabelSet ls;
        labelset_init(&ls);
        g_sema_labels = &ls;
        for (size_t j = 0; j < fn->body.len; j++)
            collect_labels(&ls, &fn->body.data[j]);
        g_sema_ret_type = fn->ret_type;
        int has_return = 0;
        check_stmt_list(&fn->body, &st, &ft, &has_return);
        symtable_leave_scope(&st, mark);
        symtable_free(&st);
        g_sema_labels = ((void*)0);
        labelset_free(&ls);
        if (!has_return && fn->ret_type.kind != TY_VOID) {
            die_at(fn->loc.file, fn->loc.line, fn->loc.col,
                   "function '%s' must have a return statement",
                   fn->name ? fn->name : "(nullptr)");
        }
    }
    ftab_free(&ft);
    symtable_free(&globals);
    g_sema_pkg = ((void*)0);
    g_sema_tu = ((void*)0);
    g_sema_structs = ((void*)0);
}
void sema_check(const TranslationUnit *tu, int require_main) {
    sema_check_in_pkg(tu, require_main, ((void*)0));
}
